### ISSUE TITLE
boolTheory.MONO_EXISTS and listTheory.MONO_EXISTS

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#1029]
Hi,

I found that `boolTheory` and `listTheory` each has a theorem called `MONO_EXISTS`:

```
[MONO_EXISTS]  Theorem (boolTheory)      
      ⊢ (∀x. P x ⇒ Q x) ⇒ (∃x. P x) ⇒ ∃x. Q x

[MONO_EXISTS]  Theorem (listTheory)
      ⊢ (∀x. P x ⇒ Q x) ⇒ EXISTS P l ⇒ EXISTS Q l
```

It was found when a theory using `boolTheory.MONO_EXISTS` starts to open `listTheory` and then is broken. Every (standard) theory opens `boolTheory` (by opening `boolLib`), and Boolean theorems shouldn't be override by subsequent theories. I suggest we rename `listTheory.MONO_EXISTS` to something else and fix whatever broken proofs in core theories and examples, and put it as a minor incompatibility in the next release notes.

--Chun

**Comment by mn200** [comment]
`EXISTS_SIMP` will need fixing in the same way.
