### ISSUE TITLE
Bug in types alpha renaming with qspecl_then

### ISSUE THREAD

**Issue by samsa1** [HOL-Theorem-Prover/HOL#1031]
Multiple times I encountered examples where binding a variable in a forall renames all of it's occurrences.

Here is an example

```
open HolKernel Parse boolLib bossLib term_tactic;
open listTheory;

Theorem test1:
  !L (s : num) x. MEM s L \/ \neg MEM s L
Proof
  Induct >> gvs []
QED

Theorem failing:
  !L. MEM 0 (MAP FST L) \/ \neg MEM 0 (MAP FST L)
Proof
  gen_tac >> rename1 `MAP FST L` >>
  qspecl_then [`MAP FST L`, `0`, `0`] assume_tac test1 >>
  cheat
QED
```

In interactive mode, just before before executing the `cheat` we get a warning stating that there exists 2 variables with the same name but different types : `L : (num # num) list, (num # \alpha) list`

The origin of this is that binding the type of the `x` variable of theorem `x` binds the type `\alpha` inside the theorem. But this means that it also binds it in the type of `L`. However this `\alpha` came from somewhere else.

I think I also experienced this with a lambda abstraction, I'll try to post an example below

**Comment by mn200** [comment]
In some sense this is "working as expected".  You can use `GEN_TYVARIFY` to force `test1`'s type variables away from those that occur in the goal.

**Comment by konrad-slind** [comment]
Took me a while to understand this. The problem is that the goal is more general than the lemma: in the goal `L:(num#'a) list` and in the lemma `L:(num#num)list`. Removing the type constraint in the statement of the lemma will make things work better.
