### ISSUE TITLE
EVAL floating point expression

### ISSUE THREAD

**Issue by michael-roe** [HOL-Theorem-Prover/HOL#1053]
This might not be a bug, but it's an issue I'd really like some help with.

What I'd like to do is evaluate a simple floating point expression in the logic (e.g. 1.0 + 1.0).

The reason I want it is for checking bugs in CPU floating point hardware against HOL4's fp as a gold model. e.g. if I have a test case where the spike RISCV emulator and a RISCV chip produce different results, use HOL4 to arbitrate who is right.

This is going to be something along the lines of open machineIEEE ... EVAL ...  but I cant quite figure out how to do it.

**Comment by konrad-slind** [comment]
I am interested in this too. Alas, no answers.           --Konrad.

**Comment by michael-roe** [comment]
For example, I would have expected "open binary_ieeeTheory;" to work, but I get:
poly: : error: Structure (binary_ieeeTheory) has not been declared
Found near open binary_ieeeTheory

**Comment by konrad-slind** [comment]
Last I looked there was a functor application needed to create the theory?
Probably that could/should be done at system build time.

Konrad

**Comment by michael-roe** [comment]
Yes, probably should be done at system build time.

In the meantime, do you know what I'd need to type at the prompt?

**Comment by michael-roe** [comment]
I would really, really like to have a solution to this, for a paper I am writing.

**Comment by mn200** [comment]
There are some problems with the existing floating-point code (I'm just playing with stuff in that directory now), but the selftest.sml code in `src/floating-point/native` uses `EVAL` on floating point values and passes its tests.  You might want to look there for inspiration.

**Comment by mn200** [comment]
Re: functors etc.  Interactively, you can't expect to `open fooTheory` without first calling `load "fooTheory";`.  Then calling `open` will work.   If you also load the context in the selftest file (most importantly, `binary_ieeeLib`), then you can write
```
EVAL ``float_add roundTiesToEven (POS0:half) (NEG0:half)``;
```
and get back
```
val it =
   ⊢ float_add roundTiesToEven POS0 NEG0 =
     (<|DivideByZero := F; InvalidOp := F; Overflow := F; Precision := F;
        Underflow_BeforeRounding := F; Underflow_AfterRounding := F|>,
      <|Sign := 0w; Exponent := 0w; Significand := 0w|>): thm
```

The most annoying part will probably be generating the values to test.   But if you figure out that 14 is a 32 bit float as 
```
<|Sign := 0w; Exponent := 130w; Significand := 0x600000w|>
``` 
and that 1 is 
```
<|Sign := 0w; Exponent := 127w; Significand := 0w|>
``` 
then 

```
EVAL ``float_to_real $ SND $ float_add roundTiesToEven
             (<|Sign := 0w; Exponent := 130w; Significand := 0x600000w|> : (23,8)float)
             <|Sign := 0w; Exponent := 127w; Significand := 0w|>``;
val it =
   ⊢ float_to_real
       (SND
          (float_add roundTiesToEven
             <|Sign := 0w; Exponent := 130w; Significand := 0x600000w|>
             <|Sign := 0w; Exponent := 127w; Significand := 0w|>)) =
     15: thm
```

See the body of the selftest.sml file that I'm about to add to `src/floating-point`.
