### ISSUE TITLE
(p==>q)==>(~q==>~p) tactic

### ISSUE THREAD

**Issue by michael-roe** [HOL-Theorem-Prover/HOL#1089]
I would really to have a tactic that takes a goal p ==> q and reduces it to ~q ==> ~p (sometimes the contrapositive is easier to prove).

I expect that this already exists somewhere, but I couldn't find it.

**Comment by mn200** [comment]
Possible one-liners would be 
```
CONV_TAC $ REWR_CONV $ GSYM CONTRAPOS_THM
``` 
or
```
simp[Once $ GSYM CONTRAPOS_THM]
```
or
```
ONCE_REWRITE_TAC [GSYM CONTRAPOS_THM]
```
or 
```
MATCH_MP_TAC $ iffLR CONTRAPOS_THM
```
But I'd usually do `strip_tac >> CCONTR_TAC`, or `CCONTR_TAC >> gs[]`, both of which would give you a goal that had `p` and `~q` as assumptions, and `F` as a goal.  (This is what you'd get if you applied one of the one-liners above, and then followed it up with `rpt strip_tac`.)

**Comment by binghe** [comment]
This is how I found `CONTRAPOS_THM` (and something similar) when I was needing the same thing:
```
> DB.match ["bool"] ``~q ==> ~p``;
val it =
   [(("bool", "CONTRAPOS_THM"), (|- !t1 t2. ~t1 ==> ~t2 <=> t2 ==> t1, Thm)),
    (("bool", "MONO_NOT"), (|- (y ==> x) ==> ~x ==> ~y, Thm)),
    (("bool", "MONO_NOT_EQ"), (|- y ==> x <=> ~x ==> ~y, Thm))]: public_data list
```
