### ISSUE TITLE
Configure failure on macOS: Failed to make mlyacc (Fail "Command failed")

### ISSUE THREAD

**Issue by barracuda156** [HOL-Theorem-Prover/HOL#1092]
```
--->  Configuring HOL
Poly/ML 5.9 Release

HOL smart configuration.

Determining configuration parameters: holdir OS poly polymllibdir 
OS:                 macosx
poly:               /opt/local/bin/poly
polyc:              /opt/local/bin/polyc
polymllibdir:       /opt/local/lib
holdir:             /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_HOL/HOL/work/HOL-Theorem-Prover-HOL-24d772b
DOT_PATH:           SOME /opt/local/bin/dot
MLTON:              NONE

Configuration will begin with above values.  If they are wrong
press Control-C.

Will continue in 1 seconds.

Loading system specific functions
Compiling system specific functions (sig sml)
Beginning configuration.
Making mllex
Making mlyacc
Failed to make mlyacc (Fail "Command failed")
Command failed: poly < tools-poly/smart-configure.sml
Exit code: 1
Error: Failed to configure HOL: command execution failed
```

**Comment by mn200** [comment]
If you change directory to `tools/mlyacc/src` and type
```
polyc -o mlyacc.exe poly-mlyacc.ML
```
what output do you get?

**Comment by binghe** [comment]
It seems that this is on Mac OS X 10.6 (Snow Leopard) running on old machines with PowerPC processor. I don't think PolyML supports this old platform. (If you are using MacPorts' building far, this platform can be removed from the support list.)

**Comment by barracuda156** [comment]
> If you change directory to `tools/mlyacc/src` and type
> 
> ```
> 
> polyc -o mlyacc.exe poly-mlyacc.ML
> 
> ```
> 
> what output do you get?

@mn200 I am sorry, this went forgotten. I will return to check this in a couple of days.

**Comment by barracuda156** [comment]
> It seems that this is on Mac OS X 10.6 (Snow Leopard) running on old machines with PowerPC processor. I don't think PolyML supports this old platform. (If you are using MacPorts' building farm, this platform can be removed from the support list.)

@binghe This is likely fixable. I don’t think it relies on new SDK features, at least not on those which aren’t or can’t be re-implemented.
