### ISSUE TITLE
Failure to build on Android/termux

### ISSUE THREAD

**Issue by SylNah** [HOL-Theorem-Prover/HOL#1099]
![Screenshot_2023-04-04-23-48-00-337_com termux](https://user-images.githubusercontent.com/58192133/229930874-e0c85046-7798-4111-978a-5b5e8434e529.jpg)
Hi. 
Build of mlyacc fails without explanation. 😔

**Comment by mn200** [comment]
Can you build any executables at all with `polyc`?  I suspect that is the basic issue.

**Comment by mn200** [comment]
For example, you should be able to call `polyc` on a file that looks like:
```
fun main() = print "Hello, world!\n"
```

**Comment by SylNah** [comment]
Hi! Thanks for your answers!

It does compile but SEGFAULT at the end of execution, no idea what's wrong

![Screenshot_2023-04-05-12-43-40-673_com termux](https://user-images.githubusercontent.com/58192133/230058586-ee86e87d-84c5-49d5-9011-b517cafc7f7c.jpg)

**Comment by binghe** [comment]
Obviously you need to go to PolyML mailing list first. AFAK PolyML doesn't officially support Android platform (yet).

**Comment by SylNah** [comment]
Ok. Thanks

**Comment by binghe** [comment]
By the way, HOL also supports building with Moscow ML, which is implemented in more ANSI C code. Perhaps you could have some lucks with it on Android.
