### ISSUE TITLE
Manual Makefile

### ISSUE THREAD

**Issue by fblanqui** [HOL-Theorem-Prover/HOL#1108]
Hi. When I do `make` in the directory `Manual` I get the following pdf files only: `./Logic/logic.pdf`
and `./Reference/reference.pdf`. No pdf is generated for tutorial, interaction, etc.

**Comment by mn200** [comment]
On `develop` (or `master` for that matter), there is no longer a `Makefile` in that directory at all: the expectation is that you will use `Holmake` there instead.

**Comment by fblanqui** [comment]
Thanks Michael. So what should I do to generate those pdf files?

**Comment by mn200** [comment]
Holmake or make in each directory should work.

Michael

On 23 May 2023, at 22:18, Frédéric Blanqui ***@***.***> wrote:

﻿

Thanks Michael. So what should I do to generate those pdf files?

**Comment by fblanqui** [comment]
I see. So there is no way to build all pdf's with a single command (Holmake in Manual/ fails), right?

**Comment by mn200** [comment]
Update to `develop` and do `Holmake`.  Failing that:
```
for i in * ; do if [ -d $i ] ; then pushd $i ; Holmake || make ; popd ; fi ; done
```
