### ISSUE TITLE
Proof failed but Holmake doesn't report it

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#1110]
Hi,

currently `examples/dev` (I don't know the underlying theories at all) fails to build *sometimes* with experimental kernel [1]. When I try to build locally, I found the building log of `FactScript.sml` contains some failed proofs:
```
Saved theorem _______ "FactIter_TOTAL"
Saved theorem _______ "FACT_dev"
Proof of 

(COMB (λt. (t,1)) (inp,f_1' <> f_2') ⇔ COMB (λt. t) (inp,f_1')) ∧
COMB (λt. 1) (inp,f_2')

failed.
Proof of 

(COMB (λ(p1,t). (p1,t)) (f_1'³' <> f_2'³',f_1' <> f_2') ⇔
 COMB (λ(p1,t). p1) (f_1'³' <> f_2'³',f_1')) ∧
COMB (λ(p1,t). t) (f_1'³' <> f_2'³',f_2')

failed.
Proof of 

(COMB (λ(p1,t). (p1,t,0)) (f_1'³' <> f_2'³',f_1 <> f_2 <> f_3') ⇔
 COMB (λ(p1,t). p1) (f_1'³' <> f_2'³',f_1)) ∧
COMB (λ(p1,t). (t,0)) (f_1'³' <> f_2'³',f_2 <> f_3')

failed.
Proof of 

(COMB (λ(p1,p1',t). (0,p1',t))
   (f_1'³' <> f_2'³' <> f_3'³',f_1 <> f_2 <> f_3') ⇔
 COMB (λ(p1,p1',t). 0) (f_1'³' <> f_2'³' <> f_3'³',f_1)) ∧
COMB (λ(p1,p1',t). (p1',t)) (f_1'³' <> f_2'³' <> f_3'³',f_2 <> f_3')

failed.
Proof of 

(COMB (λ(p1,p1',t). (p1 − 1,p1',p1' + t))
   (f_1'³' <> f_2'³' <> f_3'³',f_1 <> f_2 <> f_3) ⇔
 COMB (λ(p1,p1',t). p1 − 1) (f_1'³' <> f_2'³' <> f_3'³',f_1)) ∧
COMB (λ(p1,p1',t). (p1',p1' + t)) (f_1'³' <> f_2'³' <> f_3'³',f_2 <> f_3)

failed.
runtime: 0.05062s,    gctime: 0.00000s,     systime: 0.00014s.
Axioms: 0, Defs: 0, Disk: 0, Orcl: 1, Prims: 8297; Total: 8298
Saved ORACLE thm ____ "Fact_net"
runtime: 0.36608s,    gctime: 0.00659s,     systime: 0.00462s.
Saved ORACLE thm ____ "Fact_cir"
...
Exporting theory "Fact" ... done.
Theory "Fact" took 1.4s to build
```
But `Holmake` command completes successfully, and even the theory signature `FactTheory.sig` is generated.

Before fixing the proof itself, I think perhaps the meta issue that `Holmake` doesn't terminate when a theory contains failed proofs, is a more serious issue?

Regards,

Chun Tian

[1] https://github.com/HOL-Theorem-Prover/HOL/actions/runs/5206988643/jobs/9394110457

**Comment by mn200** [comment]
My suspicion is that while the output isn't being hidden, but the corresponding exception is being caught in the code. Look for example at the body of `COMB_SYNTH_CONV` in `compile.sml`.  That code should be adjusted not to call the high-level `prove` function, but to instead use `TAC_PROOF` or similar. This would make the process quieter.

**Comment by mn200** [comment]
Have fixed the real problem.

**Comment by binghe** [comment]
I think HOL builds are still randomly failing at the same theory.

**Comment by mn200** [comment]
That's probably a Poly/ML issue: I've stopped the unnecessary printing of exception messages caused by proofs failing.

**Comment by binghe** [comment]
> That's probably a Poly/ML issue: I've stopped the unnecessary printing of exception messages caused by proofs failing.

I use PolyML master in my local computer. Let's also switch to it (from 5.9.1) for the Docker image and see what happens.

**Comment by binghe** [comment]
Now I see what's happening (next): with lastest Poly/ML master HOL session crashed:

![Screenshot 2023-07-21 190106](https://github.com/HOL-Theorem-Prover/HOL/assets/163421/b6b22974-60f9-4e24-a4fe-ccaa0688c49b)
