### ISSUE TITLE
Some small typos in the doc

### ISSUE THREAD

**Issue by fblanqui** [HOL-Theorem-Prover/HOL#1133]
Hi. Later is better than never. Here are a few typos I found in the doc when I was in Göteborg in May:

In HOL-interaction.pdf:
- be default -> by default
- open a file with file with a name ending in Script.sml -> open a file with a name with suffix "Script.sml"
- section 2: it is perhaps useful to add that one needs to add in his ~/.emacs file
```
(setq hol-executable "<path-to-hol>")
```
if hol is not in the user $PATH.

In description.pdf:
- p414: they be -> not sure it is correct (but I am not a native English speaker)

In interaction-emacs.pdf:
- p8: theories has -> have

In tutorial.pdf:
- p57: Now we have created four new files: there seems to be only one file now, although some other files are hidden in some hidden directories: .hollogs, .HOLMK, .holobjs

**Comment by mn200** [comment]
Thanks for these!

Incidentally, setting the `hol-executable` variable in emacs is not necessary once one has configured HOL (first step of the build process), as the full path is set in the `.el` file at that point.

**Comment by mn200** [comment]
FWIW, I think “they be” is OK in the context where it appears, but it is needlessly archaic in tone.  I've changed it.
