### ISSUE TITLE
Annoyance with patterns in Define

### ISSUE THREAD

**Issue by SOwens** [HOL-Theorem-Prover/HOL#114]
I have a function

```
val pure_add_constraints_def = Define `
  (pure_add_constraints [s] [] [] = T) ∧
  (pure_add_constraints (s1::s2::rest) (t1::ts1) (t2::ts2) =
    (t_unify s1 t1 t2 = SOME s2) ∧
    pure_add_constraints (s2::rest) ts1 ts2) ∧
  (pure_add_constraints _ _ _ = F)`;
```

and a goal

`~pure_add_constraints s (v3::v4) []`

but SRW_TAC [] [pure_add_constraints_def]

won't solve the goal because the definition doesn't have the proper case in it:

> pure_add_constraints_def;
> val it =
>    |- (∀s. pure_add_constraints [s] [] [] ⇔ T) ∧
>    (∀ts2 ts1 t2 t1 s2 s1 rest.
>       pure_add_constraints (s1::s2::rest) (t1::ts1) (t2::ts2) ⇔
>       (t_unify s1 t1 t2 = SOME s2) ∧
>       pure_add_constraints (s2::rest) ts1 ts2) ∧
>    (∀v2 v1. pure_add_constraints [] v1 v2 ⇔ F) ∧
>    (∀v6 v19 v18. pure_add_constraints (v6::v18::v19) [] [] ⇔ F) ∧
>    (∀v7 v6 v15 v14. pure_add_constraints (v6::v7) (v14::v15) [] ⇔ F) ∧
>    (∀v7 v6 v11 v10. pure_add_constraints (v6::v7) [](v10::v11) ⇔ F) ∧
>    ∀v6 v23 v22 v11 v10.
>      pure_add_constraints [v6](v22::v23) (v10::v11) ⇔ F:
>    thm

To solve the goal, I first have to do quite a bit of Cases_on to build many similar goals that fit the patterns of the definition theorem.  Is there a better way that I am missing?

Edit:
After a bit of further thought, I'm not sure that this would have worked before, but I'll leave it open in case anyone has any good ideas about what to do here.  In this particular case, it might be nice to generate some overlapping patterns for the F case to mitigate the amount of case splitting needed, but I don't know if that kind of strategy would be helpful or feasible in general.
##

**Comment by thtuerk** [comment]
Using PMATCH case expressions gives you tighter control over which equations are created. This is discussed in the new Sec. "6.8.4 Lifting case expressions" of the description manual.

**Comment by thtuerk** [comment]
Can this issue be closed?

**Comment by mn200** [comment]
I think so.
