### ISSUE TITLE
Limits on the number of jobs for Holmake?

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#1163]
Holmake -j 15 raises Subscript where as Holmake -j 14 works fine on a server machine with 128 cores.

**Comment by mn200** [comment]
I think this is a duplicate of now fixed #1158 ; please re-open if you continue to see problems once you've merged with `develop`.

**Comment by mn200** [comment]
If you are stuck on an earlier version and can't merge forward, the workaround is to use 
```
Holmake ... | tee my-log-file
```
which turns off Holmake's attempts to be pretty.
