### ISSUE TITLE
EVAL monitoring should be able to stop the computation

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#1262]
Rather than just output the term being examined, the monitoring function should be able to examine the term and return true/false to say whether or not computation should continue.  If not, the theorem of the computation up to that point could be returned.

**Comment by mn200** [comment]
This is trickier than one might first think.  In particular, the existing “monitoring” and “stopping” infrastructure only ever sees the sub-term where a reduction is about to occur. One doesn’t really get a picture of the whole term, and that is probably the level where one would want to decide to cause an evaluation to cease.  (Note that the “stopping” stuff is there to prevent a reduction from happening at a sub-term, not to stop all of the computation.)

**Comment by someplaceguy** [comment]
Would it be easy to change `EVALn` such that `EVALn 1` is guaranteed to make at least one reduction (assuming that it's possible to make one)?

Right now, this doesn't seem to happen when I do the following:

```
> computeLib.EVALn_CONV 1 ``flr 42 = 42n``
val it = |- flr 42 = 42 <=> flr 42 = 42: thm
```

However, if I use `2` instead of `1` then it actually seems to make progress:
```
> computeLib.EVALn_CONV 2 ``flr 42 = 42n``
val it = |- flr 42 = 42 <=> T: thm
```

**Comment by someplaceguy** [comment]
Sorry, please feel free to ignore my last comment. It turns out that my feature request would not actually be useful for my purposes and it might even be detrimental (if `EVALn` becomes measurably slower as a result).

**Comment by mn200** [comment]
I'm afraid `EVAL`’s behaviour under the hood is terribly opaque, so it’s far from obvious to me what might be going on in your examples.  I’m tempted to close this issue with `EVALn` deemed good enough.

**Comment by mn200** [comment]
Closing with claim that `EVALn` is as good as it’s going to get.
