### ISSUE TITLE
New Quote syntax isn't highlighted correctly in emacs

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#1290]
In emacs, `End` is highlighted as a keyword but `Quote` is not.
```
Quote cakeml:
  fun print_list ls =
    case ls of [] => () | (x::xs) => (print x; print_list xs)
End
```
This relates to #1229 and 718d989039b65d4ab82e8b979876c68c04869da1.

**Comment by mn200** [comment]
Closed by aaa51b33c6c
