### ISSUE TITLE
Awful error in inductive relations arising from inconsistent handling of schem vars

### ISSUE THREAD

**Issue by talsewell** [HOL-Theorem-Prover/HOL#1296]
This error could be triggered recently by this simple snippet:

```
IndDefLib.Hol_reln
  `
  (! x.
    eq_reln Schema_var x x
  )
  /\
  (
    ! Schema_var x y z.
    eq_reln Schema_var x y /\
    eq_reln Schema_var y z ==>
    eq_reln Schema_var x z
  )`
```

The inner problem is how `Schema_var` is treated. It can be schematic (treated as a parameter to the whole thing rather than a variable that evolves e.g. in the induction). There is a an inner function `unschematize_clauses` that does part of the work for this. Unfortunately it gets confused by the forall wrapped around Schema_var in the second clause, and this leads to it generating partly adjusted clauses that disagree about the type of the final relation. It's a bit too complicated for me to quickly understand and submit a PR. I might get to it eventually.

The outer problem is that the error that is created is inscrutable, and a fairly experienced user (i.e. me) couldn't spot the pattern in an hour of trying.

**Comment by mn200** [comment]
I'm going to change the behaviour here to accept the definition and have it not make it schematic: the `eq_reln` isn't consistently applied to a common prefix of free variables, so a schematic definition shouldn't be attempted at all.

**Comment by talsewell** [comment]
Thanks, looks good!
