### ISSUE TITLE
srw_ss silently rewrites x.field if record x is big

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#131]
Hitting the big_record_size limit changes behaviour of srw_ss even for
just simple record reads like `x.field`. Surely, the change of
underlying representation shouldn't be exposed to the user here?

Example:

val _ = (Datatype.big_record_size := 4);

val _ = Hol_datatype `
  test_record = <| field1 : num ;
                   field2 : num ;
                   field3 : num ;
                   field4 : num |>`;

val _ = let
  val t1 = `x.field1` |> rator
  val t2 = `x.field1` |> QCONV (SIMP_CONV (srw_ss()) [])
                        |> concl |> rand |> rator
  in if aconv t1 t2 then ()
     else failwith "srw_ss modified record read" end

(\* replacing 4 by 5 at the top avoids the HOL_ERR *)
##

**Comment by mn200** [comment]
Closed because "big records" are no longer a thing at all.
