### ISSUE TITLE
Quote syntax parses incorrectly

### ISSUE THREAD

**Issue by dnezam** [HOL-Theorem-Prover/HOL#1313]
Consider the difference between the "old" syntax, and the presumably equivalent, "new" syntax:
```sml
val _ = (append_prog o process_topdecs)
  `fun strcat_foo_old r = r := !r ^ "foo"`

Quote cakeml:
  fun strcat_foo_new r = r := !r ^ "foo"
End
```

with the parse result being:

```sml
> (DB.fetch "-" ("strcat_foo_old" ^ "_v_def"));
val it =
   ⊢ strcat_foo_old_v =
     Recclosure (merge_env cf_examples_env_24 init_env)
       [("strcat_foo_old","r",
         Let (SOME " v0") (App Opapp [Var (Short "!"); Var (Short "r")])
           (Let (SOME " v1")
              (App Opapp
                 [App Opapp [Var (Short "^"); Var (Short " v0")];
                  Lit (StrLit "foo")])
              (App Opapp
                 [App Opapp [Var (Short ":="); Var (Short "r")];
                  Var (Short " v1")])))] "strcat_foo_old": thm


> (DB.fetch "-" ("strcat_foo_new" ^ "_v_def"));
val it =
   ⊢ strcat_foo_new_v =
     Recclosure (merge_env cf_examples_env_25 init_env)
       [("strcat_foo_new","r",
         Let (SOME " v0")
           (App Opapp
              [App Opapp [Var (Short "!"); Var (Short "r")];
               Lit (StrLit "foo")])
           (App Opapp
              [App Opapp [Var (Short ":="); Var (Short "r")];
               Var (Short " v0")]))] "strcat_foo_new": thm
```
In particular note that the new version does not make any mention of `^`.

**Comment by dnezam** [comment]
Fully updating to the new Quote syntax depends on https://github.com/HOL-Theorem-Prover/HOL/issues/1313 - in particular, there is at least once instance in `characteristic/examples/cf_examplesScript.sml` that is affected by this.

**Comment by mn200** [comment]
The implementation of `Quote` expects you to double the bare caret character in order to have it transform into just one, so you'd have to write
```
Quote cakeml: 
  fun strcat_foo_new r = r := !r ^^ "foo"
End
```
but this now seems kinda dumb to me (particularly given the inconsistency you've identified), so perhaps I should change it so that you only need to double carets to escape them when they occur before parentheses and alphabetic characters.
