### ISSUE TITLE
Holmake hangs

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#1353]
At current `master` (i.e. 01016dcf0e02558d270fce008fce672df8cdbbf7)

Running `Holmake` in a directory containing only the file `bugScript.sml` with the following contents
```
open HolKernel boolLib bossLib

val _ = new_theory"bug";

Definition bug_def:
  bug = nothing to see here
Termination
  cheat
QED

val _ = export_theory();
```

seems to go into an infinite loop.

**Comment by mn200** [comment]
Thanks for the bug report!

**Comment by mn200** [comment]
@digama0 might be best placed to fix this.
