### ISSUE TITLE
Incorrect types in listTheory.EL

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#1356]
```
> EL;
val it =
   ⊢ (∀(l :α list). EL (0 :num) l = HD l) ∧
     ∀(l :β list) (n :num). EL (SUC n) l = EL n (TL l): thm
```

**Comment by digama0** [comment]
for comparison, on master:
```
> EL;
val it =
   ⊢ (∀(l :α list). EL (0 :num) l = HD l) ∧
     ∀(l :α list) (n :num). EL (SUC n) l = EL n (TL l): thm
```

**Comment by binghe** [comment]
> for comparison, on master it used to be:
> 
> ```
> > EL;
> val it =
>    ⊢ (∀(l :α list). EL (0 :num) l = HD l) ∧
>      ∀(l :α list) (n :num). EL (SUC n) l = EL n (TL l): thm
> ```

But why the type has changed? Is it possible that there are other unknown theorems suffering the same type changes. (But I admit the type inference behavior makes sense, both the old and the new.)
