### ISSUE TITLE
thy_addons unable to parse constants from theory

### ISSUE THREAD

**Issue by konrad-slind** [HOL-Theorem-Prover/HOL#1370]
If one uses `adjoin_to_theory` to add code to an exported theory, that code does not seem to be able to parse constants from that theory. I ran across code in the `examples/acl2/ml` directory that depends on this, so the current behavior seems to have diverged from the past.  In the following, the declared constant `c` is a number, but parsing it in the generated theory file shows it to be polymorphic.

```
open HolKernel boolLib

val _ = new_theory"bug";

val _ = new_definition ("def", “c = 1n”);

val _ =
 adjoin_to_theory
 {sig_ps = SOME (fn _ => PP.add_string "val ctm : term"),
  struct_ps =
    SOME(fn _ => PP.add_string ("val ctm = Parse.Term ‘c’;\n\n"))
 };

val _ = export_theory();
```

After `Holmake bugTheory`, one can see the problem:

```
> load "bugTheory";
load "bugTheory";
<<HOL message: inventing new type variable names: 'a>>
val it = (): unit
> type_of bugTheory.ctm = alpha;
type_of bugTheory.ctm = alpha;
val it = true: bool
```

But of course, parsing ``c`` in the interactive session does give the desired constant, so this is a parser problem, not a problem with installing the constant into the signature.

**Comment by konrad-slind** [comment]
Seems like the grammar additions of the theory are not installed before executing the add-on code.

**Comment by mn200** [comment]
Interesting one!  Will have a look.

**Comment by mn200** [comment]
(It's gross style of course, but while we retain `adjoin_to_theory` I guess we shouldn't be recklessly breaking things.)

**Comment by konrad-slind** [comment]
What’s the recommended way of doing add ons?

**Comment by mn200** [comment]
There's no recommended way of putting stuff directly into theory signatures the way this code does (I don't think it's a good idea in general).  Of course, in your case, if you have a lot of code that really depends on being able to write `fooTheory.c_tm`, then you have to do something like the above and the my "modern" opinion on style doesn't help.

(There's a feature request here though: we could imagine making theory files automatically include these bindings for all of its constants, as long as the binding wasn't already taken by a theorem name.)  

The "nice" (though arduous) thing to do would be to write the appropriate `fooSyntax.{sig,sml}` files and use the bindings there.

**Comment by konrad-slind** [comment]
Yes, I agree that having xTheory be purely a container for the theory
segment itself plus grammar additions, leaving other shenanigans to xSyntax
and xLib files is the correct way to structure things. Problem is that I am
trying to follow what Mike and Matt did a while ago, and just want to get
their stuff working again without rewriting much.

Re: the possible feature request: I had the thought that there could be an
"export_syntax" analogue to "export_theory", which would auto-generate
xSyntax with the standard constructors, destructors, and recognizers. One
would probably still want to manipulate that too, via something like
thy_addons, a "syntax_addons" or some such thingy.

**Comment by mn200** [comment]
Huh.  See 0801c6f2263fc for where I explicitly add the ability to adjoin "after completion", precisely to allow for parses to work.  I'm closing this now because there's a workaround: use `adjoin_after_completion` for the `structure` code but keep the other call to fiddle with the `signature`.  It's not 100% clear to me why we might want to keep the ability to insert _before_ completion, or why we can't allow the `adjoin_after_completion` to also adjust the signature but I'm loth to change anything, because this idiom is so gross that we should make it painful to use :)

**Comment by konrad-slind** [comment]
Thanks Michael! I wonder if it's worth expunging adjoin_to_theory. It was
originally created to add a couple of rewrites from pairTheory to the
implicit rewrites used by REWRITE_{CONV,RULE,TAC}. And then got used in a
few places, but it's certainly not heavily used.
