### ISSUE TITLE
Wildcards in pretty-printing for case ... of ...

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#165]
I often define datatypes with quite a few constructors, e.g.

```
Datatype `foo = A | B | C | D num | E num num | F | G`
```

Typing case statements of the form,

```
``case f x of 
  | D n => n
  | A => 7
  | y => 8``
```

the pretty-printer responds with a much larger print out:

```
case f x of
  A => 7
| B => 8
| C => 8
| D n => n
| E v4 v5 => 8
| F => 8
| G => 8
```

Could the pretty-printer be made to notice that 8 is the RHS of more than one case and print the term instead using a wildcard-catch-all as follows?

```
case f x of
  A => 7
| D n => n
| _ => 8
```
##

**Comment by xrchz** [comment]
Using ```examples/deep_matches``` is another workaround.

**Comment by thtuerk** [comment]
`case2pmatch` in `examples/deep_matches/deepMatchesLib.sml` is essentially such an optimising pretty-printer. It it based on the stuff in the HOL pretty printer, but does fancy optimisations including removing redundant rows, reordering rows and introducing wildcards. However, in `deep_matches` it is produces `PMATCH` based term and then the equivalence is checked. Even though, there is a flag to turn these optimisations off. I'm not sure I would be feeling confident having such complicated code in the standard pretty-printer.

**Comment by xrchz** [comment]
I'd say if #285 gets done, then we can close this one as irrelevant.

**Comment by mn200** [comment]
Agreed.

**Comment by thtuerk** [comment]
Meanwhile, issue #285 got closed. Therefore, I believe, this one can now be closed as well.

There are now two options looking at the original example. One can use the classical decision tree case expressions with the issues described above or `PMATCH` based ones and preserve the input structure. Even converting to PMATCH` is able to remove the clutter.

````
> open patternMatchesLib
> val _ = ENABLE_PMATCH_CASES()
> val _ = Datatype `foo = A | B | C | D num | E num num | F | G`

> val t0 = ``dtcase f x of 
  | D n => n
  | A => 7
  | y => 8``
val t0 =
   ``dtcase f x of
    A => 7
  | B => 8
  | C => 8
  | D n => n
  | E v4 v5 => 8
  | F => 8
  | G => 8``:
   term

> val t1 = ``case f x of 
  | D n => n
  | A => 7
  | y => 8``
val t1 = 
   ``case f x of D n => n | A => 7 | y => 8``:
   term

> val t0' = case2pmatch true t0
val t0' =
   ``case f x of A => 7 | D n => n | _ => 8``:
   term

> val thm0 = PMATCH_INTRO_CONV t0
val thm0 =
   |- (dtcase f x of
      A => 7
    | B => 8
    | C => 8
    | D n => n
    | E v4 v5 => 8
    | F => 8
    | G => 8) =
   case f x of A => 7 | D n => n | _ => 8:
   thm

````
