### ISSUE TITLE
Allow fully qualified names for type abbreviations

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#168]
Mark Batty showed me some Lem-generated HOL code that HOL refuses to
accept. The code he gave HOL defined a type abbreviation, say
`mystring`, in `fooTheory` and then, in a different theory, Lem referred
to the type abbreviation using a fully qualified name:

    :foo$mystring

I request that such fully qualified type abbreviations should be supported in HOL4.

**Comment by xrchz** [comment]
:+1: and this should also let us more precisely remove particular type abbreviations

**Comment by xrchz** [comment]
#148 and #124 are also probably related

**Comment by xrchz** [comment]
I'll accept the bounty claim once the HOL and CakeML regression tests pass.
