### ISSUE TITLE
list_compset on MEM performs badly, because IN_CONV deals badly with variables

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#182]
The list compset includes both `MEM` and `LIST_TO_SET_THM`. Since `MEM` is an abbreviation for membership in a `LIST_TO_SET` of something, the latter rewrite interferes with the simple recursion equations rewrite for `MEM`, leaving evaluation of membership in a concrete list at the mercy of evaluation of membership in a concrete set.
The latter usually gets done by `pred_setLib.IN_CONV`, which doesn't seem to work very well on a term like `x IN {t1;t2;...;tn}` if `x` is a variable. (At least, using the rewrites at the list level without going down to the sets seems much faster.)

Either `IN_CONV` should be improved, or the list compset should be made to somehow not apply the `LIST_TO_SET_THM` rewrite when evaluating `MEM` terms (but continue to apply it otherwise).
##

**Comment by xrchz** [comment]
Unfortunately I don't have a good example to hand at the moment, but I thought I should mention that this is what I typically use as a workaround whenever I am using `list_compset`:
```
fun MEM_CONV eval =
  (REWR_CONV(CONJUNCT1 listTheory.MEM)) ORELSEC
  (REWR_CONV(CONJUNCT2 listTheory.MEM) THENC eval)

fun fix_list_compset c =
  let
    val () = computeLib.scrub_const c ``set``
    val () = computeLib.scrub_thms [listTheory.MEM] c
    val () = computeLib.add_conv(``$IN``,2,
      MEM_CONV (computeLib.CBV_CONV c)) c
  in () end
```

**Comment by mn200** [comment]
No evidence that this is a problem.
