### ISSUE TITLE
overloads interact badly with antiquotation and print depth

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#234]
The following script file creates an unloadable theory:
```
open HolKernel bossLib boolLib Parse
val _ = new_theory"bug"
val _ = Globals.max_print_depth := 5
val _ = overload_on("foo",``λt1. ^(snd(dest_abs(rhs(concl AND_DEF))))``)
val _ = export_theory()
```

The only relevant feature of ```AND_DEF``` is that it is long enough to be affected by the change to the print depth.

When attempting to load:
```
> load"bugTheory";
Don't expect to find a . in this position after a .
at frag 0 row 0 col 47 and at frag 0 row 0 col 46.
Exception- HOL_ERR {message = "at frag 0 row 0 col 46:\nDon't expect to find a . in this position after a .\nat frag 0 row 0 col 47 and at frag 0 row 0 col 46.\n", origin_function = "Absyn", origin_structure = "Absyn"} raised
Exception-
   HOL_ERR
  {message =
  "at frag 0 row 0 col 46:\nDon't expect to find a . in this position after a .\nat frag 0 row 0 col 47 and at frag 0 row 0 col 46.\n",
  origin_function = "Absyn", origin_structure = "Absyn"} raised
```

**Comment by mn200** [comment]
Great catch.  Work on #231 would resolve this situation properly because the printer used in the theory file would be completely independent of the parsing machinery.  For the moment, there is an easy fix, which is to set the `print_depth` back to `~1` before printing in theory files.

**Comment by mn200** [comment]
Incidentally, anti-quotation has nothing to do with it.  You might as well have written the large term out by hand.
