### ISSUE TITLE
UTF8 decoding allows invalid inputs

### ISSUE THREAD

**Issue by RobArthan** [HOL-Theorem-Prover/HOL#237]
I can't imagine anyone cares, but [RFC3629](http://tools.ietf.org/html/rfc3629) forbids UTF-8 encodings that use more characters than are necessary: e.g., 0xC080 is not a valid encoding of 0. However, the HOL4 implementation does:

    > (UTF8.getChar o implode o map chr) [0xC0, 0x80];
    val it = SOME (("\192\128", 0), ""): ((string * int) * string) option

(Apologies for what is probably the saddest HOL4 issue report ever!)

**Comment by mn200** [comment]
Now you've implanted the sort of nagging irritation in my heart that just won't go away...

What's the nice way of detecting the problem, if there is one?  (The not-so-nice way is to know how many bytes should be taken for each range of values and to check after decoding that you've consumed that many bytes.)

**Comment by RobArthan** [comment]
I don't know of any pretty way of doing it, but you do know how many bytes you plan to consume, so after consuming them you just need to check that the final result is large enough that many bytes. So you need to apply something like the following as a check on the result inside the function UTF8.getChar:

    fun rangeCheck cnt (res as ((_, i), _)) = 
        if case cnt of 2 => 0x80 <= i | 3 => 0x800 <= i | 4 => 0x10000 <= i andalso i <= Umax | _ => true
        then res
        else raise BadUTF8 s

**Comment by mn200** [comment]
Thanks for this.  I've used your code (except the fall through in the `case` should be to `false`, at least in the way I've used your code.

**Comment by RobArthan** [comment]
Michael,

On 23 Mar 2015, at 01:51, Michael Norrish <notifications@github.com> wrote:

> Thanks for this.
> 
My pleasure!  

> I've used your code (except the fall through in the case should be to false, at least in the way I've used your code.
> 
> 
Yes, false is better in your code. That branch is unreachable in my ProofPower version.

Regards,

Rob.
