### ISSUE TITLE
Subtle problems in TeX emitter

### ISSUE THREAD

**Issue by ptroja** [HOL-Theorem-Prover/HOL#242]
Perhaps I do not understand the motivation behind the current solutions, but:
* function composition should be printed as ```\HOLTokenCompose{}``` and not as the letter ```o```
* ```\HOLTokenBar``` (which is used to display set builder-notation, i.e. ```{x | P x}```) should be defined as ```\ensuremath{\med}``` and not ```\texttt{|}```
* when printing set-builder notation there should be extra spaces (```\,```) after ```{``` and before ```}``` (see TeXbook, page 174).

First two seem easy to fix, the third can be more tricky.

**Comment by xrchz** [comment]
For ```\HOLTokenBar```, I think it depends on whether you're using ```alltt``` environments to display HOL or normal math environments. Depending on your choice you can ```\renewcommand``` as necessary.

**Comment by mn200** [comment]
The first bullet point is something we should deal with.   Numbers two and three can be handled by the user if the printing is not happening in `alltt`.  In particular, the `overrides` file can update the maps for `|` and `{` and `}` to insert different spacing, and to use `\mid`.
