### ISSUE TITLE
Inconsistent description of `Induct_on`

### ISSUE THREAD

**Issue by ptroja** [HOL-Theorem-Prover/HOL#245]
The _DESCRIPTION_, paragraph _Strong Induction Principles_, says that ```Induct_on``` uses the strong induction principle, which for relation ```R``` is stored in the ```R_strongind``` theorem. But section _Proofs with Inductive Relations_ (just 2 pages later) says that ```Induct_on``` is a "slightly more high-level approach [to ```HO_MATCH_MP_TAC R_ind```]", which relies on another induction principle, which is stored in ```R_ind``` theorem.

**Comment by mn200** [comment]
Good point.  I'll fix this.  The difference comes about depending on whether you are inducting on a datatype theorem, or an inductive relation.

**Comment by mn200** [comment]
Err, at least, I think the language is too vague.
