### ISSUE TITLE
Tex_notation cannot be undone

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#248]
If I depend on a theory that makes a call to ```TexTokenMap.TeX_notation```, but I do not want to use the TeX notation for the HOL token specified in that call, my only option is to make a new call to ```TeX_notation``` where I explicitly specify what would have been the default output (and then see warning messages about updating the map). It would be nicer if I could just delete the unwanted mapping.

**Comment by mn200** [comment]
Not so: you can use the `overrides` file that is passed as a parameter to the munger to undo such bindings.  For example, if I have

    ∀ 3 foo

in the `overrides` file then

    \HOLtm{!x. P x}

turns into

    \HOLinline{\HOLSymConst{foo}\HOLBoundVar{x}. \HOLFreeVar{P} \HOLBoundVar{x}}

The symbol-merging happening there is not ideal of course.  You have to override the token that the pretty-printer is actually going to output, so handling `!` won’t work in this case.

**Comment by mn200** [comment]
You can also do it *per* call to `\HOLtm` *etc* by using the `//` substitution:

    \HOLtm[foo//∀]{!x. P x}

gives the same output as above.

**Comment by xrchz** [comment]
I was in fact already using an ```overrides``` file and it was not giving the desired effect. To be more concrete about my problem, I have a theory, A, which defines an overload on the token "<:". My pretty-printing theory has both A and bagTheory as ancestors. My ```overrides``` file includes 3 overrides: one for "<:", one for "\HOLTokenIn{}:" and one for "∈:"; they all map to my desired output "\lessdot". My pretty-printing theory also has another "override", namely, a call to ```TeX_notation``` trying to undo the one made in bagTheory. With any combination of those 4 overrides, I do not get the desired output in the generated ```.tex``` file. I always get the unwanted "\HOLTokenIn{}:" output specified in bagTheory.

**Comment by mn200** [comment]
Can you turn this into a test-case in `src/TeX/theory_tests` please?

**Comment by xrchz** [comment]
I added a test case, which tries lots of things to get the desired output at the same time (but none work). When this issue is resolved it would probably be better to have more specific variations on the test that don't try lots of redundant things at once.

**Comment by mn200** [comment]
There is no bug here.  You can see what's going on by running hol and loading your `pp248Theory`.  If you do:

    > load "pp248Theory";
    <<HOL warning: TexTokenMap.TeX_notation: Theory pp248 overrides "<:" (was "("\\HOLTokenIn{}:", 2)"); now "("\\ensuremath{\\lessdot}", 1)">>
    val it = (): unit

    > ``foo b a``;
    val it = ``a ⋲ b``: term

That binary operator symbol `⋲` is what you have to override, either using an `overrides` file, or by using a `TeX_notation` command.  Note that `bagScript` does this, and note further that this symbol is not a standard epsilon.

TeX overriding works at the token level, after the pretty-printer has finished doing its thing.  In fact, there are now *three* ways of adjusting overriding: 

1. An `overrides` file, passed as an argument to the munger
2. Using `TeX_notation` commands
3. Using the `//` substitution command within a `\HOLtm`, `\HOLthm` command *etc*

As you didn't use one of these to handle `⋲` specially, you got the substitution from `bagTheory`.
