### ISSUE TITLE
Q.PAT_ABBREV_TAC should do type instantiation

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#252]
Q.PAT_ABBREV_TAC often fails when the given pattern fails to match only because of a too general type. I think functionality would be strictly better if, instead of failing, it tried a match that did not require matching types.

**Comment by mn200** [comment]
I don't understand the issue.  If you have a pattern with a general type, it does instantiate:

    Q.MATCH_ABBREV_TAC `P x` ([], ``y * 6 < 10``);
    val it =
       ([([``Abbrev (x = 10)``,
           ``Abbrev (P = $< (y * 6))``],
          ``P x``)], fn) : goal list * validation

And if the goal has a more general type than the pattern, I don't understand what you'd want to see.

**Comment by xrchz** [comment]
I'm talking about `PAT_ABBREV_TAC`, not `MATCH_ABBREV_TAC`

**Comment by mn200** [comment]
D'oh!  I'm not even sure I know what `PAT_ABBREV_TAC` does.

**Comment by xrchz** [comment]
Maybe you could reimplement `Q.PAT_ABBREV_TAC` in terms of `Q.MATCH_GOALSUB_ABBREV_TAC` (although I just noticed that that doesn't exist).

**Comment by mn200** [comment]
It's an easy fix in fact.  Commit coming.
