### ISSUE TITLE
fol_type_to_hol ignores theory

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#259]
I don't have a small example of this yet, but I get this exception:
```
Exception- HOL_ERR {message = "proof translation error", origin_function = "fol_thms_to_hol", origin_structure = "folMapping"}
```
after seeing many warnings of the form 
```
<<HOL warning: Type.mk_type: more than one possibility>>
```

**Comment by xrchz** [comment]
If anyone has a small example that generates the warning
```
metis: proof translation error: trying again with types.
```
I can probably turn it into a small example of this issue. I haven't been able to find one myself.

**Comment by mn200** [comment]
I guess the typed f.o.l. versions of the terms should encode the theory into them so that the translation is injective.  The code in `folMapping` is pretty clearly fixable along these lines.  Try the forthcoming commit and see if it make the problem go away.

**Comment by xrchz** [comment]
Yes, I think that solves it. Thanks!
