### ISSUE TITLE
cannot create same-name record and field in different theory

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#260]
I'm not sure whether this is intentional, but I would prefer if this were allowed (or to know the rationale for disallowing it):
`fooScript.sml`:
```
open HolKernel bossLib;
val _ = new_theory"foo";
val _ = Datatype`foo = <| f : bool |>`;
val _ = export_theory();
```
`barScript.sml`:
```
open HolKernel bossLib fooTheory;
val _ = new_theory"bar";
val _ = Datatype`foo = <| f : bool |>`;
val _ = export_theory();
```
```
Exception raised at Datatype.Hol_datatype:
at Term.create_const:
not a type match
Exception- HOL_ERR {message = "at Term.create_const:\nnot a type match", origin_function = "Hol_datatype", origin_structure = "Datatype"} raised
Holmake: Failed script build for barScript - exited with code 1
```

**Comment by mn200** [comment]
It should be allowed.  Curiously, though I get warning messages when I try this, I don't get failures.   I will commit my test-case (and try to make the code more robust such that it doesn't give me `mk_const` warnings; what the heck is `create_const`?)

**Comment by xrchz** [comment]
I saw the exception on 1ee64d3. I'll try updating to see if it turns into just a warning...

**Comment by xrchz** [comment]
still get the exception at HEAD (abc8e74)

**Comment by mn200** [comment]
Can you adjust the test-case so as to demonstrate the bug please?  I still can't reproduce (and nor can the regression machines so far).

**Comment by mn200** [comment]
Don't worry; I've got a local reproduction.
