### ISSUE TITLE
PAT_ABBREV_TAC should avoid abbreviating quantified variables

### ISSUE THREAD

**Issue by tanyongkiam** [HOL-Theorem-Prover/HOL#262]
I think PAT_ABBREV_TAC currently applies to the first pattern that matches, even if there are quantified variables in that match.

For example with the goal:
~~~
∀ls.∃x. do_work ls x = y
~~~

Applying the tactic:

~~~
qpat_abbrev_tac`z = do_work A B` 
~~~
gives: 

~~~
Abbrev (z = do_work ls x)
~~~
 which is not very useful

**Comment by mn200** [comment]
I think I can see an easy way to stop it ever matching against bound variables, making it just fail in your example above.  This is what I'll implement.
