### ISSUE TITLE
choosing beween overloaded type abbreviations

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#265]
I would like functions analogous to `Parse.bring_to_front_overload` and friends for types as well as terms. Currently I believe the only way to get the type you mean when the parser is preferring another one (or an abbreviation) with the same name is to fully qualify with the theory name. This can become tedious. Related to #168.

**Comment by mn200** [comment]
It is indeed related: without #168 implemented, there is no masking happening at all one way or the other.

**Comment by xrchz** [comment]
#148 would be an alternative solution to some of the problems solved by this issue.

**Comment by xrchz** [comment]
Is this already done as part of #168, or does the hook still need to be added?

**Comment by mn200** [comment]
I think that making a call to `Parse.temp_thytype_abbrev` will effectively bring a particular theory's abbreviation to the front.  There should perhaps be a permanent version of the same.  And some documentation.  Note that an abbreviation is either *privileged* (able to be used without theory qualification), or not.  Masking for printing happens based on degree of specificity but once an abbreviation is chosen it will be printed with or without qualification depending on whether it is privileged/preferred.

**Comment by mn200** [comment]
I believe this is implemented by e9827f1462d

**Comment by xrchz** [comment]
I think this is not working: I have a theory where using thytype_abbrev does not seem to make the unqualified name refer to the correct (privileged) type.
