### ISSUE TITLE
overload_on and uoverload_on can produce unloadable theories

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#268]
For example, consider the following theory. It builds fine, but when you try to load it, you get errors.
```
open HolKernel bossLib boolLib Parse
val _ = new_theory"bug";
val _ = xHol_reln"tr"`
  (▷ x 0) ∧
  (▷ (SUC x) (SUC y) ⇒ ▷ x y)`;
(* either *)
val _ = Unicode.uoverload_on("\226\150\183*",``RTC ▷``);
(* or *)
val _ = overload_on("\226\150\183*",RTC ▷``);
(* -- *)
val _ = export_theory();
```
The error looks like:
```
Exception- HOL_ERR {message = "Bad decode for unicodedata (O13.\\226\\150\\183*29.relation$RTC bug$\\226\\150\\183)", origin_function = "temp_encoded_update", origin_structure = "Theory"} raised
Exception-
   HOL_ERR
  {message =
  "Bad decode for unicodedata (O13.\\226\\150\\183*29.relation$RTC bug$\\226\\150\\183)",
  origin_function = "temp_encoded_update", origin_structure = "Theory"}
   raised
```
or
```
Exception- HOL_ERR {message = "on frag 0 row 0, between cols 14 and 20:\nLexical error - \226 cannot begin a valid constant name", origin_function = "Absyn", origin_structure = "Parse"} raised
Exception-
   HOL_ERR
  {message =
  "on frag 0 row 0, between cols 14 and 20:\nLexical error - \226 cannot begin a valid constant name",
  origin_function = "Absyn", origin_structure = "Parse"} raised
```

At the very least, the functions should fail earlier. Ideally, there shouldn't be any errors when loading.

**Comment by mn200** [comment]
I agree that this is buggy.  The problem is that you've managed to create a constant with a non-ASCII name, which I've always imagined to be a violation of an invariant.  I think the fix will be to outlaw this much more drastically.  You will have to define `tri` or similar in your call to `Hol_reln`, and then overload `▷` to this.

**Comment by xrchz** [comment]
Is there any way I can do as you suggest without having to write `tri` (instead of `▷`) all through the quotation I give to `Hol_reln`? I suppose I could use a string-replace function at the very least.

**Comment by mn200** [comment]
Try this before making the definition:

    add_rule { block_style = (AroundEachPhrase, (PP.CONSISTENT, 0)), 
               fixity = Closefix, paren_style = OnlyIfNecessary, pp_elements = [TOK "▷"], 
               term_name = "tri"};

This gives you a concrete-syntax-level mapping of the token `▷` into the name `tri`, which is then subject to overload resolution *etc*.
