### ISSUE TITLE
new_specification fails for existentially quantified definitions

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#277]
If the defining property of the constants to be defined by specification is an existentially quantified proposition, `new_specification` fails. It incorrectly attempts to define constants for every existentially quantified variable, when it should instead look to the list of names for the number of constants to define.
Example:
```
open HolKernel boolLib bossLib
val _ = new_theory"bug";
val th = METIS_PROVE[]``∃x y z. x ⇒ z ∧ z ⇒ y``;
val pq_def = new_specification("pq_def",["p","q"],th);
val _ = export_theory();
```
```
Exception- HOL_ERR {message = "different length lists", origin_function = "map2", origin_structure = "Lib"} raised
```

**Comment by mn200** [comment]
Is this a regression introduced by hcddr?

**Comment by xrchz** [comment]
Yes. I'm attempting to fix it now.

**Comment by xrchz** [comment]
@mn200 can you review and merge the pull request? I also have a selftest snippet that makes a few calls to `new_specification` checking this bug is fixed, but not sure where to put it (depends on `pairLib`, so probably can't go in `1/theory_tests`) - I could add that to the pull request first if you like (just say where)

**Comment by mn200** [comment]
Yes, it would be nice to have the test in the PR (which looks OK).  Putting it into `src/pair/src` seems fine to me.
