### ISSUE TITLE
Quantifier Heuristics Lib

### ISSUE THREAD

**Issue by thtuerk** [HOL-Theorem-Prover/HOL#282]
I tend to use the quantifier heuristics library a lot and find it very useful. However, not many people seem to know and use it. I was wondering, whether it is worth trying to promote it a bit.

I often have terms with quantifiers that are just about out of the reach of the unwind instantiation methods used by ``bool_ss``. For example, I really like being able to simplify terms like

````
|- (∃x. ∀y. (x = 7) ∧ P x y) ⇔ ∀y. P 7 y
|- (∀x z. ∃g. (x = 7) ∧ Q g ⇒ P x) ⇔ ∃g. Q g ⇒ P 7
````

I love the support for partially instantiating variables of product type.

````
|- (∀p. (x = FST p) ⇒ Q p) ⇔ ∀p_2. Q (x,p_2):
|- (∃v. (λ(pa,pb,pc). P pa pb pc) v) ⇔ ∃pa pb pc. (λ(pa,pb,pc). P pa pb pc) (pa,pb,pc):
|- (∃v. (v,X) = Z) ⇔ (X = SND Z)
````

I use frequently matching to find instances automatically

````
|- (∃x. (f (8 + 2) = f (x + 2)) ∧ P 10) ⇔ P 10:
````

And of course the quantifier heuristics can do much more than just these simple, but common examples (using context, datatype definitions, records, some simple arithmetic stuff, special list support, ...). 

So, how about making sure, they are included in the default HOL image? This would lower the hazzle of using them a bit. Perhaps we could even consider adding some default simpset like e.g.
``QUANT_INST_ss [std_qp]`` to ``bossLib`` and perhaps something like ``QUANT_INSTANTIATE_TAC [std_qp]`` to ``lcsymtacs``? On the other hand, I don't want to add to much clutter. I would appreciate a discussion on this.

**Comment by xrchz** [comment]
Is it too expensive to include `QUANT_INST_ss [std_qp]` in `lcsymtacs.simp`?

I presume it wouldn't cause any unwanted side-effects in goals, so the only downside might be that `simp` gets slower (plus updating existing proofs if necessary). How much slower would it get?

A low-cost thing that could help is just to add `quantHeuristicsLib` to `bossLib`. And of course this is the kind of thing that should go into #275.

**Comment by mn200** [comment]
I would be happy to see a couple of useful "default" fragments added to `bossLib`.  The same entry-points could be added to `lcsymtacs`. The experiments Thomas has done offline indicate that we probably can't include these by default in any standard simpsets, but I certainly don't mind promoting useful defaults to a more visible library.

**Comment by thtuerk** [comment]
I believe adding some useful defaults is probably the best way forward. I will make some suggestions and create a pull request. However, the experiments Michael mentions, seem to point to a few features that might be annoying. I would like to play around with them a bit more and turn them off for the defaults. An example is

````!x. (?y. P y /\ x = f y) --> Q x````

which is converted to

````!y'. (?y. P y /\ f y' = f y) --> Q (f y')````

Sometimes this is handy, but mostly this is disturbing and essentially introduces one extra quantifier, we can't easily get rid of. I would like to eliminate this like this in the default settings. So, my proposal might take a few more days.

**Comment by thtuerk** [comment]
The discussed changes got into the master branch via pull-request #284.
