### ISSUE TITLE
Holmake -n

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#283]
It would be nice to have a "dry-run" option to `Holmake` that will show just what it is going to build, without going off and destroying the cache information. This would sometimes help me avoid long rebuilds.

**Comment by xrchz** [comment]
This option often does not work. For example `Holmake -n` fails:
```
> Holmake -n
{0}: ./balanced_mapScript_ttt.sml(0) [Succeeded] : <no command>
Holmake failed with exception: Path
Raised from: ./basis/OS.sml: 580:0 - 580:0
```
where `Holmake` without `-n` succeeds.

**Comment by mn200** [comment]
I have made this a separate bug report issue (#611) rather than a reopening of the original feature request.
