### ISSUE TITLE
New Representation for Pattern Matches - Integration

### ISSUE THREAD

**Issue by thtuerk** [HOL-Theorem-Prover/HOL#288]
This is a subtask of issue #285.

Make sure that tools like `std_ss` contain tools to handle the new pattern matches. Especially be careful about cyclic dependencies and about performance. This might need some testing and profiling. In particular we might need to play around with some congruence rules to stop evaluating too much.

Also make sure the pattern representation works well with `emit`.
##

**Comment by xrchz** [comment]
I would list integration with `EVAL` here too (as discussed in some of the comments at #286), or perhaps you would like to make a separate issue for that.

**Comment by thtuerk** [comment]
Yes, integration with`EVAL` belongs here too.

**Comment by thtuerk** [comment]
Short status update: in branch master there is the integration with `EVAL`, `std_ss` and `EmitML` now. Waiting for changes to parsing before integrating further.

**Comment by thtuerk** [comment]
I believe this is all done now. Closing this issue...
