### ISSUE TITLE
Cope with Poly/ML installations that haven't used --enable-shared

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#292]
This will require us to use `polyc` to build our various executables.

**Comment by mn200** [comment]
Still to do:
* resolve use of `polyc` for building heaps (with `buildheap`)
* provide nice syntax/idiom for using `polyc` in Holmakefiles.

**Comment by mn200** [comment]
Should perhaps use `PolyML.SaveState` structure to implement heaps rather than executables.

**Comment by xrchz** [comment]
Is `--enable-shared` still recommended, or is it now irrelevant?

**Comment by mn200** [comment]
I think it should now be irrelevant.  Have yet to fully test this though.

**Comment by mn200** [comment]
Yes, it's irrelevant.
