### ISSUE TITLE
Minimal build sequence.

### ISSUE THREAD

**Issue by talsewell** [HOL-Theorem-Prover/HOL#293]
I'm trying to deploy a project[1] that uses the decompiler[2] which builds on HOL4. I'd like to minimise the amount of time spent in bin/build in the initial stages[3].

The -h option to bin/build suggests that other build sequences are available. So, ideally, I'd like to do a minimal build in the first instance, and then use Holmake later to build the decompiler and its dependencies[3].

There's three problems with using build sequences:
  - bin/build doesn't actually suggest what a sequence file is, or where to find one. Eventually I found tools/sequences.
  - bin/build defaults to building everything. I have to leave it to the user [3] to configure HOL4, so the presence of non-default modes which are hard to find doesn't really help.
  - nearly all of the sequences in tools/sequences seem to fail with the same error:

/home/tsewell/dev/HOL4/bin/Holmake: *** Remote dependency /home/tsewell/dev/HOL4/sigobj/Overlay.ui doesn't exist.  Stop.

The exception is tools/sequences/kernel, which does something and then finishes like this:

Writing HOLPage
Generating theory-graph and HTML theory signatures; this may take a while
  (Use build's -nograph option to skip this step.)
/home/tsewell/dev/HOL4/bin/hol: 5: /home/tsewell/dev/HOL4/bin/hol: /home/tsewell/dev/HOL4/bin/hol.builder: not found
*** Theory graph construction failed.

Hol built successfully.

I don't know what hol.builder is, but its absence seems to be blocking Holmake pretty much everywhere else, so it's highly debatable whether "Hol built successfully." is a valid summary.

Some of these steps just need fixing, I guess.
I also think that the full build is an unusual default, but that might just reflect my biases.

[1] https://github.com/seL4-projects/graph-refine
[2] https://github.com/HOL-Theorem-Prover/HOL/tree/master/examples/machine-code/graph
[3] The real problem is that the deployment process has a few phases.

The user is given most of the software they need by repo ( see https://github.com/seL4/verification-manifest ) but has to configure various things themselves, including Isabelle and HOL4. I provide a script/Makefile that will build everything once the key tools are configured.

The problem is that bin/build is one of the things that the user will be doing, and they'll have to wait for it before they can get on to configuring other tools. It's no problem that the subsequent Holmake takes ages, because that's all part of the script, which takes hours anyway.

**Comment by xrchz** [comment]
If you're going to be building the decompiler eventually, I don't think you'll save much by omitting things in the default build sequence (i.e., what you get if you don't give build the -seq argument).

I think you should aim to also get bin/build called by your script that takes hours and calls Holmake etc.

**Comment by mn200** [comment]
You need to produce a sequence file that looks like the one in `tools/build-sequence`.  This sequence file refers to the sub-sequences you found in the `sequences` directory.  In particular, you will absolutely need `kernel` and `core-theories`.  That much will get you the `hol.builder` that you need.  There's more documentation on sequence files in `tools/build-sequence`. 

This is somewhat documented in the new developers' manual.

**Comment by mn200** [comment]
I've written more about sequences file in the developers' manual (507ec74ff024)
