### ISSUE TITLE
type_abbrev merging causes pain

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#294]
If one theory sets up a type abbreviation for string `"foo"` mapping to type `ty1`, and another theory sets up an abbreviation for the same string but to a different type `ty2`, then 

1. One abbreviation is arbitrarily preferred when parsing (`"foo"` will map to `ty1` say)
2. It is now impossible to turn off printing for the `ty2` abbreviation

**Comment by xrchz** [comment]
I think it's worth noting that this bug would probably have been picked up or made redundant by solving #148, #168, and/or #265.

**Comment by mn200** [comment]
Oh indeed.

**Comment by mn200** [comment]
I have a fix in the works for just this problem, and may soon be able to deal with those others as well (but they are more complicated).
