### ISSUE TITLE
confusing error message from parsing with pattern-matching and records

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#299]
Consider:
```
val _ = Datatype`bug = <| var : num |>`;

val fine =
``case opt of SOME bug_var => <| var := 0 |> | NONE => <| var := 1|>``;
```
Now, suppose I didn't know `bug_var` was silently defined by the `Datatype` command. Then the following error message from the attempted declaration of `fine` is very helpful:
```
Exception- HOL_ERR {message = "Pattern bug_var is not a constructor or variable",
origin_function = "mk_case", origin_structure = "Pmatch"} raised
```

However, if I had instead made a similar-looking declaration:
```
val help =
``case me of SOME bug_var => <| var := bug_var |> | NONE => <| var := 1|>``;
```
I would be treated to this rather confusing message:
```
Type inference failure: unable to infer a type for the application of

bug_var_fupd :(num -> num) -> bug -> bug

on line 2, characters 32-37

to

(K bug_var :num -> bug -> num)

in compiler-generated text

which has type

:num -> bug -> num

unification failure message: unify failed
```

**Comment by mn200** [comment]
This is nothing to do with pattern matching.  You will get exactly the same confusing message if you take the record expression from the second example and enter it on its own.

**Comment by mn200** [comment]
This example might be an argument for not putting the special constants (`bug_var` and friends) into the standard namespace at all.  But that's a different issue.  Once you have a constant of that unfortunate type, then attempting to use it in a record expression is always going to give you a painful error mentioning a `fund` constant.
