### ISSUE TITLE
EmitTeX turnstile token has fixed width

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#307]
When using the LaTeX munger with math-mode spacing, the spacing for `\HOLTokenTurnstile{}` is wrong in two ways.

Firstly, `\HOLTokenTurnstile{}` is defined in `holtexbasic.sty` to start with two spaces (`\:\:`), which is not great for math mode. However, this is easily fixed in LaTeX using `\renewcommand`. I don't think this has to change, although it is perhaps a strange default.

The second problem is more severe in that there is no neat workaround. The pretty-printer prints the turnstile token in `EmitTeX.sml` line 567, with a fixed width of `2`. I think it needs to be more like `4` to achieve correct spacing in math-mode (where each space is `\;`). I don't know how to override this (on a per-document basis) apart from manually changing the source of `EmitTeX.sml`, which is not good at all.

**Comment by mn200** [comment]
I think one way to fix this would be to have the printing of the turnstile controlled by the overrides map, which maps a token to a width and a piece of TeX.  I would prepopulate the overrides map with a reasonable default, keyed off a string that can't be a normal token (`($EMITTEX_TURNSTILE$)` say).  Then the code in `EmitTeX` would just look up the information in the overrides map (which could be adjusted in a user-supplied `overrides` file) when it came to print the turnstile.  Note that the special token can't include any spaces if it's to be something that an `overrides` file can tweak.
