### ISSUE TITLE
MATCH_ABBREV_TAC should respect underscores

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#312]
It would be nice to be able to abbreviate parts of a pattern, while leaving other parts unabbreviated without having to spell them out. The analogous functionality for renaming tactics is accomplished by using underscores. But abbreviating tactics treat the underscores as normal variables and introduce abbreviations for them. I claim this is a bug and they should ignore the underscored parts of a match.

**Comment by mn200** [comment]
`Q.PAT_ABBREV_TAC` takes an equation of the form `v = pattern`, and introduces a single abbreviation on variable `v`.  I don't think it makes sense to put an underscore in the `v` position, and underscores in the pattern are fine. 

The issue does make sense in `MATCH_ABBREV_TAC` though where multiple abbreviation bindings can be introduced.

**Comment by xrchz** [comment]
Yes you are right. Sorry, I didn't think hard enough about what I was writing. This is for `MATCH_ABBREV_TAC` and variants thereof.

**Comment by mn200** [comment]
Closed by 923e92e2eb7
