### ISSUE TITLE
Build failure with PolyML 5.6, in `libpolyml/processes.cpp:712`

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#323]
I got this repeated error while building the current HOL4 with the current PolyML, which is PolyML 5.6 (on Ubuntu 14.04 32 bits):

    unquote: ../../polyml.git/trunk/libpolyml/processes.cpp:712: virtual void Processes::ThreadExit(TaskData*): Assertion `index < taskArraySize && taskArray[index] == taskData' failed.
    Aborted (core dumped)

The same message occurs multiple times.

Sometime it occurs during `poly < tools/smart-configure.sml`, sometimes not and I can go on to `bin/build` which fails.

**Comment by mn200** [comment]
Thanks for the report.  I hope it is a problem with Poly/ML that we can get fixed.

**Comment by xrchz** [comment]
The Poly/ML website (http://polyml.org) says the current version is 5.5.2. I'm not sure where to find version 5.6 - is there a corresponding commit in the Poly/ML git repository? I would also suggest raising this issue there (https://github.com/polyml/polyml).

**Comment by Hibou57** [comment]
@xrchz version 5.6, is the one from the master branch at GitHub. They don't use release tags, they use release branches instead. Also, 5.6 was said to be “5.6 Testing” when I executed it from the command line.

Here is what was said about this error:
> This looks like a problem with the interpreted version. I've fixed a bug with Thread.Thread.exit in 
> the interpreted version but it produced a segfault rather than an assertion fault. It's likely it's the
> same bug. I'm going to close this but please reopen if it is still present especially if it shows up in 
> the native code version.

So since INSTALL now says to not build Poly/ML with `--with-portable`, that's not an HOL4 issue any more, as it's specific to the portable version.

**Comment by mn200** [comment]
Thanks for reporting this to the Poly/ML developer.  It certainly seems as if we don't need to worry about it.
