### ISSUE TITLE
Build fails with PolyML 5.5.2

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#324]
Building with PolyML 5.5.2 (on Ubuntu 14.04 32 bits), ends with this error:

    Linking boolScript.uo to produce theory-builder executable
    Poly/ML 5.5.2 Release
    Exception- InternalError: fixupConstantLoad: constant too distant (16-bit offset) raised while compiling
    
    Exception- InternalError: fixupConstantLoad: constant too distant (16-bit offset) raised while compiling

**Comment by xrchz** [comment]
This thread might be relevant, but I don't know: 
http://lists.inf.ed.ac.uk/pipermail/polyml/2013-April/001252.html

It looks like a Poly/ML bug to me, and it's not one I've seen before. Maybe try the fixes-5.5.2 branch of Poly/ML?

**Comment by Hibou57** [comment]
I could figure what makes it went wrong: when configuring Poly/ML, I was mislead by the `--with-portable` option name, which I erroneously though was to build two compilers (a native one and a portable one). I though later again about this option, reconfigured Poly/ML 5.5.2 without it, recompiled it, then tried to recompiled HOL4 again, and it just finished with no errors.

So, as a conclusion: there is a bug in Poly/ML (well, two bugs, if I count another) and the HOL4 INSTALL file may tell about this potential issue, suggesting to try to use a Poly/ML built without `--with-portable`, if ever building HOL4 failed.

As a side note, I feel the INSTALL file should explicitly tell there is no install procedure after the build, and so HOL4 needs to be built in place, in its final directory location.

I don't know if I should close this report or not. I'm living this decision to your own will.

**Comment by Hibou57** [comment]
Additionaly, it not already done, I will forward this report to the Poly/ML repository.

**Comment by mn200** [comment]
Thanks for forwarding the report to Poly/ML. I will adjust the `INSTALL` file and other installation instructions in line with your comments.
