### ISSUE TITLE
Possible omission in DESCRIPTION on page 124

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#326]
Page 124 of description says:

> The system chooses to make the arguments corresponding to variables appear in the
> order given by the dictionary ordering of the variables’ names. Thus, in the example
> given, the ’a of (’a,’b)sum will be the Left argument because left comes before
> right in the standard (ASCII) dictionary ordering.

It's a bit ambiguous in the sense it does not say if the order is case sensitive or case insensitive.

**Comment by mn200** [comment]
Well, in some sense, ASCII is case-sensitive in that `A` is a different character to `a`, and as `A` is character 65 and `a` is 97, so `A` comes before `a`.  But I can certainly add a comment to this effect in the manual.

**Comment by mn200** [comment]
But the example is super-confusing as it stands, I agree, because it mentions not only `'a`, but `Left` and `left`!
