### ISSUE TITLE
Technology to record interactive sessions for documentation purposes

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#327]
Using the `PolyML.compiler` function, some custom filter analogous to the TeX munger should be possible here.

**Comment by konrad-slind** [comment]
I wonder if it could be used to record inputs for building "goal trees"
in src/proofman/goalTree. Not being able to record the concrete syntax
of tactics was one of the impediments to further development of
this proof manager.

Konrad.

**Comment by mn200** [comment]
It's not necessarily feature complete, but this has basically been done, as of ec15f9deab.
