### ISSUE TITLE
listTheory.TAKE_SUM has an unnecessary precondition

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#330]
I think it can be proved without the `LENGTH` assumption.

**Comment by jeremydaw** [comment]
I'm sure it can.  
Similar results for DROP are DROP_DROP and DROP_DROP_T.
Nomenclature for DROP_DROP_T is because it's derived using TL_T (Total TL),
using DROP_FUNPOW_TL
I couldn't see an equally easy way to prove the result for TAKE, so let it lie.
(These are in rich_list, not list)
