### ISSUE TITLE
`aconv`'s name

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#331]
I may be wrong with this, just tell …

Why is `aconv` named so, instead of something like `alpha_equiv`? After the HOL4 Guidebook, `aconv` seems to be a predicate, although it's named like as to suggest it's a function returning a new term after alpha‑conversion. A name like `alpha_equiv` would more suggest what it is, a predicate.

Unless I've missed something, the actual name is a bit misleading.

**Comment by xrchz** [comment]
I would say it stands for "alpha-convertible?", which is fine as a predicate.

More generally: many things in HOL might suffer from this kind of problem... an easy thing to do would be to export `alpha_equiv` as a synonym.

**Comment by mn200** [comment]
You can also use `Term.compare` and check for the result being `EQUAL`.
