### ISSUE TITLE
Build process hiccups when using polyml

### ISSUE THREAD

**Issue by andry-tino** [HOL-Theorem-Prover/HOL#337]
1. I am operating on a Unix machine running CentOS.
2. I have successfully forked and build [PolyML](https://github.com/polyml/polyml).
3. I have followed indications [here](https://github.com/HOL-Theorem-Prover/HOL/blob/master/INSTALL) for building HOL.
4. Ran `polyml < tools/smart_configure.sml`.
5 Ran `./bin/build`.
6. I could actually SUCCESSFULLY build.

The problem is that when running `./bin/build`, sometimes the build process would fail with this message when building a specific library in the list:

> Building directory src/temporal/src [23 Apr, 19:20:18]
> Temporal_Logic    : Holmake: Fail exception: Unknown result status
> Build failed in directory /home/myuser/Git/HOL/src/temporal/src (exited with code 1)

This happened many times. When this happened, I would call `./bin/build` again which would skip all built parts and resume building from where he had the last failure. All until I could build everything.

Why the build process suffers from this hiccups behavior?

**Comment by xrchz** [comment]
Unfortunately, this is a known bug with [PolyML](https://github.com/polyml/polyml) that has been reported [here](http://lists.inf.ed.ac.uk/pipermail/polyml/2016-April/001839.html) (although maybe @dcjm would like a GitHub issue to be made at the PolyML repo too?)

**Comment by andry-tino** [comment]
Yes I agree that this thing is to be properly reported to PolyML in their repo! Thanks!
