### ISSUE TITLE
Holmake -r

### ISSUE THREAD

**Issue by acjf3** [HOL-Theorem-Prover/HOL#338]
The -r option to Holmake seems to be broken?

`Holmake -r cleanAll` gives

   Don't know how to build necessary target(s): cleanAll

and `Holmake -r` does a regular make.

**Comment by mn200** [comment]
I think (hope!) `Holmake -r` only ever did a regular make.  I agree that there's a bug in the behaviour wrt `cleanAll` and friends.

**Comment by acjf3** [comment]
I only recall it doing a regular make. However, the help entry for -r says "clean recursively", which kind of indicates that it will always do a clean. If the "-r" option is pointless in the absence of a clean target then it could be a good idea to change the description and/or the behaviour? For example, one option would be to make "-r" default to "-r clean" and document it with something like `clean recursively [default target is "clean"]`.

**Comment by mn200** [comment]
Yeah, that's a nice idea. I'll create a fresh issue along those lines.
