### ISSUE TITLE
spurious "Failed to handle quotations" errors

### ISSUE THREAD

**Issue by hannesm** [HOL-Theorem-Prover/HOL#340]
I am using FreeBSD(-CURRENT) and polyml-5.6, HOL master (80833d88845a505c44b78f9a200e1e32d84166f8) and get (also with earlier HOL master versions) some strange issues with unquote, sometimes it runs forever (>10 minutes with 100% CPU), sometimes it errors out with:
`Failed to handle quotations in file: ~/devel/HOL/src/bag/bagTheory.sml`

Re-running `Holmake` (or `bin/build`) again solves the issue...

Anyone else has experienced that? (I know FreeBSD is not a tier1 platform for HOL, but it would be nice to have it working without trouble).

**Comment by hannesm** [comment]
..passing `-j 1` to `Holmake` seems to fix this issue...

**Comment by mn200** [comment]
I'd be interested to hear if a844c1d fixes your problem.

**Comment by hannesm** [comment]
it does. thank you!
