### ISSUE TITLE
Unify toto$cpn and prelim$ordering

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#343]
What looks like pretty much the same datatype is defined in both `src/ring/src/prelimScript.sml` and `src/enumfset/totoScript.sml`. Since it clearly is desirable in multiple places, shouldn't it move to an ancestor?
##

**Comment by xrchz** [comment]
On closer inspection it seems more like `prelimTheory` should just be replaced with things from `enumfset`.

**Comment by mn200** [comment]
Sounds plausible.  I think the early bits these developments have in common should be moved to `src/sorting`.  The `enumfset` stuff in its entirely wants to refer to integers, and I think the integers development in turn depends on the stuff in `ring`.
