### ISSUE TITLE
Provide easy way to include case-equality theorems

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#345]
There are “case equality” theorems for all algebraic types. For example

```
(option_CASE opt n f = v) <=> (opt = NONE /\ n = v \/ ?u. opt = SOME u /\ v = f u)
```

There should be an easy way to include all of these in a simplifier invocation, perhaps like the way abbreviations and AC-theorems are included, such as 

```
simp[use_case_eqs]
```

where `use_case_eqs` is a theorem value with a special form that prompts the simplifier to do the right thing. 
##

**Comment by thtuerk** [comment]
I hope full request #380 addresses this issue.
