### ISSUE TITLE
Memory consumption of HOL4/PolyML

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#362]
When I am building (build -j 1) a modified HOL4 on a server,  
it does allocate more than 10 GB of memory (upto 32 GB in a modified version.)
I tried using (ulimit -v 8000000) but this option interrupts the build at some point.
On my laptop that has only 4GB ram and 4GB swap, 
it manages to finish the build but freezes at different points, which is a bit annoying.
Do I need to buy a new laptop ? :(
##

**Comment by barakeel** [comment]
I forgot to precise that I am using PolyML.5.5.1 if anyone want to reproduce the behavior.

**Comment by mn200** [comment]
I guess you should upgrade to Poly 5.6 as a first step.  I've never seen memory consumption like that for a normal build.

**Comment by xrchz** [comment]
@barakeel did upgrading Poly/ML work? Can this issue be closed if so?

**Comment by barakeel** [comment]
Yes it did work.
