### ISSUE TITLE
Emacs mode: support Unicode quotation marks

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#370]
The goal and sub-goal commands both rely on finding quotations (or terms) delimited by back-quotes. This should be changed to allow for the Unicode quotations, so that

    Q.prove(‘x < x + 1’, simp[])

can be set up as a new goal as readily as 

    Q.prove(`x < x + 1`, simp[])

**Comment by thtuerk** [comment]
Hopefully, 2ec75a1 implements this feature.

**Comment by mn200** [comment]
I think the general treatment of "terms" should skip-forward and backward to look for the double quotation mark as well as the singles (*i.e.*, look for `“` and `”` as well as `‘` and `’`).  In essence, we need to support `M-h g` for 

    prove(“P x ==> Q x”, tactic) 

as well as

    Q.prove(‘P x ==> Q x’, tactic)
