### ISSUE TITLE
Allow INCONSISTENT line breaks when pretty-printing datatypes

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#372]
Currently, the style forces type declarations to be rendered

    foo = C1 num 
        | C2 bool
        | C3 string
        ...
        | Cn (num -> bool)

which can be rather space-wasteful.  It should be possible to set a trace to instead get

    foo = C1 num | C2 bool | C3 string 
        | ... | Cn (num -> bool)

**Comment by tanyongkiam** [comment]
Here was my (incomplete) hack at something like this for a paper:
Replace https://github.com/HOL-Theorem-Prover/HOL/blob/master/src/TeX/EmitTeX.sml#L416

`    fun pp_constructor_spec (n, l) = let
      val PT0 = if !print_datatype_names_as_types then pp_type_name else PT
      (*Stabilizes the sorting algorithm*)
      val enum_l = enumerate 0 l
      val tylen = length o strip_type o type_of
      val l = map snd (sort (fn (xi,x) => fn (yi,y) =>
        if tylen x = tylen y then xi < yi else tylen x < tylen y) enum_l)
    in
        (BB PP.INCONSISTENT 2;
         PT0 n; S " "; S "="; BR(1,2);
         app (fn x => (pp_clause x; BR(1,0); S "|"; S " "))
             (List.take(l, length l - 1));
         pp_clause (last l);
         EB())
    end`
