### ISSUE TITLE
Tactics in Q are slow

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#383]
Since `Q_TAC` was modified to try all possible parses (around 81e277147c9160fb85f6b8c8a997ba481bc6f029), tactics built with `Q_TAC` have become much slower. While we would expect a small slowdown because more work is being done, could the implementation be improved in any way to recover performance in the common case?

**Comment by mn200** [comment]
Let me know if you think 2817e17 fixes the problem.  It certainly seems to make a number of example and core scripts within HOL go much quicker.

**Comment by xrchz** [comment]
I think @myreen might have some examples to test. I would be happy to close this issue (based on a look at the diff, and that it makes the HOL build faster) and reopen if necessary when I next run into unexpected slowdowns.

**Comment by mn200** [comment]
Sounds good.
