### ISSUE TITLE
Printing of case expressions

### ISSUE THREAD

**Issue by acjf3** [HOL-Theorem-Prover/HOL#400]
There is a bug when pretty-printing case expression. For example, with the following declarations:

val () = Datatype `dt = C1 (num # num) | C2 num`

val df_def = Define`
  fd x =
  case x of
     C1 (i1, i2) => if i1 + 1 = 0 then 0 else 1
   | C2 i3 => 2`

the definition df_def prints as

!x. fd x = case x of 0 => 0 | C1 (i1,i2) => 1 | C2 i3 => 2

which doesn't make sense.

**Comment by thtuerk** [comment]
I could confirm this bug. I believe it is due to some comparably easily fixable bug in Pmatch. Pull request #401 tries to fix it.

**Comment by acjf3** [comment]
Thanks. The fix looks to have worked.
