### ISSUE TITLE
Building with --otknl fails on int_arith

### ISSUE THREAD

**Issue by cmr** [HOL-Theorem-Prover/HOL#408]
Here's the log I get:

```
Uploading files to /home/cmr/proj/HOL/sigobj
Building directory src/integer [02 Apr, 15:18:49]
integerTheory                                                                OK
integer.art                                                                  OK
OmegaTheory                                                                  OK
integerRingTheory                                                            OK
int_arithTheory                                                         FAILED!
 Saved theorem _____ "NOT_INT_DIVIDES_POS"
 Saved theorem _____ "le_context_rwt1"
 Saved theorem _____ "le_context_rwt2"
 Saved theorem _____ "le_context_rwt3"
 Saved theorem _____ "le_context_rwt4"
 Saved theorem _____ "le_context_rwt5"
 Saved theorem _____ "eq_context_rwt1"
 Saved theorem _____ "eq_context_rwt2"
 Exporting theory "int_arith" ... done.
 Theory "int_arith" took 1.6s to build
Omega.art                                                              M-KILLED
int_arith.art                                                          M-KILLED
integerRing.art                                                        M-KILLED
Build failed in directory /home/cmr/proj/HOL/src/integer (exited with code 1)
```

Not very descriptive. I also had some other seemingly non-deterministic failures (cleaning the directory the error was in and retrying one or two times made them go away), but this one seems quite sticky. Any way to get more information?

**Comment by mn200** [comment]
Which version of Poly/ML are you using?

**Comment by cmr** [comment]
Current git master: https://github.com/polyml/polyml/commit/096d446e45fb88dd6dae7e62f2f06d03eedf524a

**Comment by mn200** [comment]
Hmm, can you try with 5.6, or a point “release” above that?  I'm not sure how to get the repo SHAs for the later revisions (I should ask the mailing list), but [this Ubuntu page](https://launchpad.net/ubuntu/+source/polyml/5.6-2) has sources for something they're calling 5.6-2. 

I certainly find that working on polyml/polyml@167eaf7d28 seems pretty reliable on MacOS.

I think the basic issue is that the implementation of exit-codes and/or `wait` is making `Holmake` think there is a failure when there isn't really.

Failing all else, try `Holmake -j1` in the affected directories, or just `build -j1` to do everything that way.

**Comment by cmr** [comment]
I'm getting various other (seemingly spurious) failures now, trying to narrow down...

**Comment by cmr** [comment]
So none of the errors I've come across survive one or two `git clean`s of the relevant directories and trying again. I'm using `-j1` exclusively, which seems to have fewer problems (but that might also just be that the build is going a few times slower).

**Comment by cmr** [comment]
I can't seem to get any reasonable root cause here. Even without otknl, sometimes builds fail for seemingly no reason, and rerunning `./bin/build` causes it to progress past the file it just failed on.

**Comment by xrchz** [comment]
I presume this is still with `-j1`. When it fails, can you see what's in the .hollogs directory for the directory that failed?

**Comment by xrchz** [comment]
I saw one of these random failures just now too. Strange. This is at 6374be884 and using Poly/ML fixes-5.6.

**Comment by xrchz** [comment]
It's been a few weeks now...

**Comment by cmr** [comment]
I have a button too!
