### ISSUE TITLE
Holmake recursively re-interprets -I command-line option

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#413]
Hello everyone,

I tried to separate my code into two directories src and src/utils
Then I tried the following command in src: Holmake -I utils.

Recursively calling Holmake in utils
Recursively calling Holmake in utils/utils
Holmake failed with exception: SysErr ("No such file or directory", SOME ENOENT)

Is this the intended result?

Thanks,

**Comment by mn200** [comment]
The `-I` flag has a bug; you should adjust the `INCLUDES` line in your Holmakefile instead.
