### ISSUE TITLE
Hol replacing a quoted, bound variable by another

### ISSUE THREAD

**Issue by rmonat** [HOL-Theorem-Prover/HOL#416]
Hi everyone,

I stumbled upon a weird behavior of HOL. I reduced my example to something smaller, that does not really make any sense now. When defining the _test_ function below, I wanted to enforce m' = m in the case of the Downcast constructor.
```sml
open HolKernel bossLib;

val _ = Datatype `exp = Const num num | Downcast num exp`;

val test_def = Define `
  test (e:exp) (map: exp -> num option) : bool =
    case e of
     | Const m n => (case map e of
                      | SOME m' => m = m'
                      | NONE => F)
     | Downcast m e1 => (case map e, map e1 of
                           | SOME m', SOME m1 => (m' = m) /\ test e1 map
                           | _, _ => F)
     | _ => F`;
```

However, when giving this to HOL, this constraint is not forced anymore, and has been replaced by m'' = m''.

```
val test_def =
   |- ∀map e.
     test e map ⇔
     case e of
       Const m n => (case map e of NONE => F | SOME m' => m = m')
     | Downcast m' e1 =>
         case (map e,map e1) of
           (NONE,v1) => F
         | (SOME m'',NONE) => F
         | (SOME m'',SOME m1) => (m'' = m'') ∧ test e1 map:
   thm
```

Have I missed something or is this a bug? I am using HOL4 Kananaskis 11.

**Comment by konrad-slind** [comment]
It's a bug. Not a soundness bug, but the pattern-match expansion is
capturing a variable
it shouldn't.

Konrad.

**Comment by thtuerk** [comment]
I believe pull request #426 fixes this issue

**Comment by thtuerk** [comment]
closing after #426 got merged
