### ISSUE TITLE
HOL/examples/formal-languages build failure

### ISSUE THREAD

**Issue by SOwens** [HOL-Theorem-Prover/HOL#417]
I've just updated to PolyML 5.7, and charsetTheory fails to build.
          (Different type constructors)
 Found near if ~>> (w, ... ...) = 1 then orb (w, IntInf.<< (...)) else w
 /Users/sao/HOL/examples/formal-languages/regular/WordOps.sml:28: error: Type error in function application.
    Function: Word.fromInt : Int.int -> Word.word
    Argument: width : int
    Reason:
       Can't unify Int.int (*In Basis*) with int (*In Basis*)
          (Different type constructors)
 Found near if ~>> (w, ... ...) = 1 then orb (w, IntInf.<< (...)) else w
 Static Errors

**Comment by konrad-slind** [comment]
Probably the regexp library hasn't been upgraded to the downgrade from the
paradise of IntInf = Int. Anthony had pinged me about this awhile ago, but
I hadn't
gotten to it. He may have fixes already, if my memory is right.

Konrad.

**Comment by acjf3** [comment]
I do have a fix. However, it may be best to put it on a fresh branch? The original library authors will need to test it and check that it works as expected.

**Comment by acjf3** [comment]
You can try the commit c9bc095.

**Comment by konrad-slind** [comment]
Thanks Anthony! --Konrad.

**Comment by SOwens** [comment]
It's worth noting that CakeML depends on this example building, so it's worth getting the fix onto master soon.

**Comment by xrchz** [comment]
I made a pull request for it (#420). I think the original authors are @konrad-slind and/or @mn200 - and clearly Konrad is OK with this fix?

**Comment by konrad-slind** [comment]
Bit busy at the moment (paper deadlines). I promise to have a look tomorrow.
Anthony made the fixes BTW.

Konrad.

**Comment by xrchz** [comment]
#420 was merged, so closing this
