### ISSUE TITLE
unquote hangs, causing Holmake to hang

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#424]
Unfortunately this is sporadic and hard to reproduce, but when using Poly/ML 5.7 and recent (e.g., 6b8bb52) HOL, running `Holmake` sometimes hangs and looking at `top` suggests it is stuck inside an `unquote` process.

**Comment by xrchz** [comment]
This is possibly related to this CakeML issue https://github.com/CakeML/cakeml/issues/268

**Comment by mn200** [comment]
As of 99c4765128, no part of a Holmake build will use a separate `unquote` process.
