### ISSUE TITLE
Q.GENL generalises in wrong order

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#428]
As reported by Chun Tian (@binghe): 

> Recently I found that, GENL and Q.GENL has different generalization orders:

````
GENL [``x``, ``y``, ``z``] (SPEC_ALL EQ_TRANS);
val it =
   |- ∀x y z. (x = y) ∧ (y = z) ⇒ (x = z):
   thm

Q.GENL [`x`, `y`, `z`] (SPEC_ALL EQ_TRANS);
val it =
   |- ∀z y x. (x = y) ∧ (y = z) ⇒ (x = z):
   thm
````

> see the differences: “!x y z” and “!z y x”. It seems that Q.GENL processes the variable list in a reverted order.

**Comment by binghe** [comment]
To "fix" this issue, it seems enough to change the current definition of Q.GENL (in src/q/Q.sml) from this:

`val GENL = rev_itlist GEN;`

into this:

`val GENL = itlist GEN;`

But I don't understand why SPECL works correctly with a similar definition:

`val SPECL = rev_itlist SPEC;`

Can you see the reason?

--Chun

**Comment by mn200** [comment]
I'm fixing this in the way you suggest (though I'm using `foldr` rather than `itlist` because `foldr` is a standard name (from the Basis Library).  The reason is that `SPECL` is taking a theorem apart from the outside, while `GENL` is assembling it from the inside.
