### ISSUE TITLE
HOL doesn't build all theories on Linux after commit c13df66

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#440]
Hi,

I'd like to report some issues I met, after the commit c13df66 [1] which has introduced MLton for building `Holmake`, etc.

In my Linux box (Ubuntu 16.04, self-built Poly/ML 5.7), if I have MLton (system package) installed, then many theories (e.g. src/real/*) do not build as part of the HOL building process. If I uninstall MLton, everything works fine then.   But `Holmake` itself seems working fine: If I manually go to those unbuilt folders and manually call `Holmake`, it does trigger the building process on theories in that folder.

On Mac OS X (10.11, Poly/ML 5.7 and MLton installed by Homebrew), HOL builds correctly with MLton. (however, I met minor issues as described in the comments of [1])

Regards,

Chun Tian

[1] https://github.com/HOL-Theorem-Prover/HOL/commit/c13df6633d2ff24ea4a3cce48d6daff4eecfe1ac

**Comment by binghe** [comment]
The issue also happens in "Bash on Ubuntu on Windows 10" (Ubuntu 16.04), when mlton is uninstalled, HOL building goes back to normal.

But the issue doesn't happen on Debian 7 (with older mlton, maybe)

**Comment by mn200** [comment]
Does the config-override technology allow you to set 
````
   val MLTON = NONE;
````
to workaround the problem?

**Comment by binghe** [comment]
Yes, with your latest commits I can override MLTON to NONE.

**Comment by binghe** [comment]
Hi Michael, I confirm this issue has been fixed by your commit a53703d, thanks.
