### ISSUE TITLE
Get THEN1 to report location of error

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#457]
Interactively, I think it should be possible for the emacs mode (at least) to turn `>-` into `>>- linenum ??` where we have
````
infix >>- ??
fun (t1 >>- n) = fn t => t1 >- t handle HOL_ERR _ => print message with line number n
fun t ?? t0 = t t0
````

**Comment by mn200** [comment]
This was done in 468179c5845.

**Comment by barakeel** [comment]
I am relying on the unquote binary to record tactics, and I would like to not record linenum inside my tactics. Could you make a flag to turn this option off if it is part of the unquote binary?

**Comment by mn200** [comment]
If you call it in the following way
````
unquote inputfile outputfile
````
it shouldn't add the line numbers.
