### ISSUE TITLE
Parallel Holmake random failures

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#461]
On occasion, `Holmake` (without `-j1`) will report a built theory as `FAILURE` despite having successfully got to the end. Running `Holmake` again treats that theory as already built.

**Comment by xrchz** [comment]
I have observed this on both `fixes-5.6` and `fixes-5.7` branches of Poly/ML, on Linux 4.13.11 with gcc 7.2.0

**Comment by xrchz** [comment]
This may be fixed by Poly/ML 5.7.1

**Comment by mn200** [comment]
That'd be awesome if so!

**Comment by xrchz** [comment]
No longer observed in Poly/ML 5.7.1, so closing this.

**Comment by xrchz** [comment]
I still occasionally see this on 5.7.1 under heavy load - just less frequently than before.
