### ISSUE TITLE
Major Defn difference between stdknl and expk

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#462]
The following script produces very different `fooTheory.sig` files depending on whether it is run with HOL built on `stdknl` versus `expk`. In particular, on `expk`, the theory produces theorems containing the select constant (`@`) but not on `stdknl`. (I managed to get this down to under 40 lines from a much larger example.)

While I accept that `expk` might produce different generated variable names than `stdknl`, I think generating theorems with different constants is an unacceptable difference between the kernels.

```
open HolKernel boolLib bossLib listTheory optionTheory;

val _ = new_theory"foo";

val _ = Hol_datatype`
  exp = Lit of num | Log of exp => exp`;

val _ = Hol_datatype `
 exp_or_val = Exp of exp | Val of num`;

val _ = Define `
 (do_log v e=
 ((case v of
      1 => SOME (Exp e)
    | 0 => SOME (Val v)
    | _ => NONE)))`;

val eval_defn = Defn.Hol_defn"eval"`
  (eval st [] = (st, SOME [])) /\
  (eval st (e1::e2::es) =
    (case eval st [e1] of
      (st', SOME v1) =>
        (case eval st' (e2::es) of
          (st'', SOME vs) => (st'', SOME (HD v1::vs))
        | res => res)
      |res => res)) /\
  (eval st [Lit n] = (st, SOME [n])) /\
  (eval st [Log e1 e2]=
   ((case eval st [e1] of
      (st', SOME v1) =>
        (case do_log (HD v1) e2 of
          SOME (Exp e) => eval st' [e]
        | SOME (Val v) => (st', SOME [v])
        | NONE => (st', NONE))
    | res => res)))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn eval_defn;

val _ = export_theory();
```

**Comment by xrchz** [comment]
@konrad-slind any thoughts on this?

**Comment by konrad-slind** [comment]
Ah, I missed seeing this! Will have  a look. --Konrad.

**Comment by konrad-slind** [comment]
Before getting to the actual problem you mention, something else seems
fishy.
    The definition for "eval" gets made, but then some mechanism seems to
delete
    it. (It depends on a oldified definition.) If I do a Theory.scrub(),
the rules for "eval"
   get deleted, which should happen. However, if I do an "export_theory"
the rules
   for eval do get put in the theory. I am very confused.

Konrad.

**Comment by mn200** [comment]
If you do a `git log .` in the `src/tfl/src` directory you will see that I was messing about with that sort of stuff a while ago (though more with parsing than oldification I think).  Perhaps that will be helpful.  None of that has anything to do with per-kernel differences, but there may be other weirdnesses happening.

**Comment by xrchz** [comment]
@konrad-slind thanks for your work on this! I believe 0169ffb10 solves it.

**Comment by mn200** [comment]
Can we have a regression test for this please?

**Comment by konrad-slind** [comment]
On its way ...

**Comment by konrad-slind** [comment]
Sorry it took so long. In the end, the difference stems from obscure
alpha-renaming
behaviour.  If

  vbool = ``v:bool``;
  vind = ``v:ind``;

then

   mk_abs(vbool,
     mk_abs(vind, pairSyntax.mk_pair(vbool,vind)));

is renamed at construction time in one kernel, but not the other. The same
difference is seen when creating "foralls".

My bug came from a theorem where there were two universally quantified
variables
with the same name but different types. In one kernel, the same names
weren't allowed,
so SPEC_ALL didn't rename; in the other kernel, the same names were
allowed, but then
SPEC_ALL renamed, which derailed a later GENL inference step.

Konrad.

**Comment by mn200** [comment]
Ick!

**Comment by konrad-slind** [comment]
Ick indeed. I think it's a carry-over from mimicking hol88 behaviour.

Example (possibly can be shortened, since the core problem shouldn't have
anything to do with nested recursion).
In the following, the problem goes away if v1 (or v) is renamed to
something else, like "u". That's because
TFL likes to genvar variables that start with "v".


(*---------------------------------------------------------------------------*)
(* From Ramana, who says that *on expk* this generates definition/thms
with  *)
(* occurrences of (@) while stdk doesn't have that.
  *)
(*---------------------------------------------------------------------------*)

open HolKernel boolLib bossLib listTheory optionTheory;

val _ = new_theory"foo";

val _ = Hol_datatype
  `exp = Lit of num
       | Log of exp => exp`;

val _ = Hol_datatype
  `exp_or_val
      = Exp of exp
      | Val of num`;

val do_log_def = Define `do_log v e = ARB`;

val eval_defn =
Defn.Hol_defn
 "eval"
 `(eval st [Log e1 e2] =
    case eval st [e1]
     of (st', SOME v1) =>
          (case do_log (HD v1) e2
     of SOME (Exp e) => eval st' [e]
              | SOME (Val v) => (st', SOME [v])
              | NONE => (st', NONE))
      | res => res) /\
  (eval st other = ARB)`;


val _ = Defn.save_defn eval_defn;


val _ = export_theory();

**Comment by konrad-slind** [comment]
Michael:

  I couldn't simplify the example to get rid of nested recursion. So the
one I sent will have
to do as a test case.

Konrad.
