### ISSUE TITLE
Conflict between documentation and actual behavior for UNDISCH_TAC

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#466]
The document REFERENCE for Kananaskis-11 says  “UNDISCHarging `v` will remove all assumptions which are identical to v, but those which are alpha-equivalent will remain.”. However, actually it removes all _α_-equivalent assumptions:

```
> UNDISCH_TAC “∀w. P w” ([“(∀x. P x)”, “R:bool”, “(∀y. P y)”], “Q:bool”);
<<HOL message: inventing new type variable names: 'a>>
<<HOL message: inventing new type variable names: 'a>>
<<HOL message: inventing new type variable names: 'a>>
val it =
   ([([``R``],
      ``(∀w. P w) ⇒ Q``)],
    fn): goal list * validation
```

`UNDISCH_TAC` inherits this behavior from `term_eq` in `src/0/Term.sml`. `Q.UNDISCH_TAC` inherits the same behavior from `UNDISCH_TAC`.

It appears more useful to match all alpha-equivalent terms instead of only identical terms. Thus, I suggest that the documentation is changed to reflect the current behavior, instead of the other way.

**Comment by mn200** [comment]
You're right that this is a bug in the documentation.  I'd happily take a pull request fixing it :-)

**Comment by marioxcc** [comment]
I will be working on it.
