### ISSUE TITLE
Simplifier loop with arith_ss

### ISSUE THREAD

**Issue by bacam** [HOL-Theorem-Prover/HOL#473]
The simplifier can loop on a simple expression containing `dimindex` when using `arith_ss`:

    ---------------------------------------------------------------------
           HOL-4 [Kananaskis 11 (stdknl, built Thu Oct 05 13:10:20 2017)]
    
           For introductory HOL help, type: help "hol";
           To exit type <Control>-D
    ---------------------------------------------------------------------
    [Use-ing configuration file /home/bcampbe2/.hol-config.sml]
    > load "wordsTheory";
    val it = (): unit
    > SIMP_CONV arith_ss [] ``n + dimindex (:'a) + dimindex (:'b) - 1``;
    Exception- Interrupt raised

The problem appears to be that part of the simpset in `src/num/arith/src/numSimps.sml` uses a term comparison function that ignores types, and the two appearances of `dimindex` differ only in their types.  Changing the comparison to `Term.compare` appears to work, but I don't know if there's some reason for using the particular ordering that's in numSimps.

**Comment by mn200** [comment]
Thanks for the bug report!  I think you're right that we can simply replace the poor comparison in `numSimps`.
