### ISSUE TITLE
Tactic changes behaviour unexpectedly.

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#477]
tactic1 is the proof of the goal.
A call to tactic2 before tactic1 changes the behaviour of tactic1 in the following code 
and makes the proof fails.
Suprisingly, if you call tactic1 then tactic2 and again tactic1 on the same goal, 
tactic1 still works on the second call.

load "integer_wordTheory";
show_types := true;
val goal = dest_thm integer_wordTheory.INT_BOUND_ORDER;

val tactic1 = bossLib.SRW_TAC [ bossLib.ARITH_ss ] [ wordsTheory.BOUND_ORDER ];
val tactic2 = bossLib.SRW_TAC [ bossLib.ARITH_ss ] [ integerTheory.INT_SUB ];   

tactic2 goal;
tactic1 goal;

**Comment by xrchz** [comment]
Here's a version of this problem that doesn't use the stateful simplifier:
```
load "integer_wordTheory";
load "intSimps";
val goal = dest_thm integer_wordTheory.INT_BOUND_ORDER;

val tactic1 = bossLib.RW_TAC (intSimps.int_ss ++ bossLib.ARITH_ss)
  [ integer_wordTheory.INT_MAX,
    integer_wordTheory.INT_MIN,
    integer_wordTheory.UINT_MAX,
    integer_wordTheory.INT_ZERO_LT_INT_MIN,
    integer_wordTheory.INT_ZERO_LT_UINT_MAX,
    wordsTheory.BOUND_ORDER ];
val tactic2 = bossLib.RW_TAC (intSimps.int_ss ++ bossLib.ARITH_ss)
  [ integer_wordTheory.INT_MAX,
    integer_wordTheory.INT_MIN,
    integer_wordTheory.UINT_MAX,
    integer_wordTheory.INT_ZERO_LT_INT_MIN,
    integer_wordTheory.INT_ZERO_LT_UINT_MAX,
    integerTheory.INT_SUB ];

tactic2 goal;
tactic1 goal;
```

**Comment by xrchz** [comment]
My current hypothesis is that this is a bug in `ARITH_ss`, because it is built using a cache (`RCACHE`) which calls a function `is_arith` for which there is a comment saying there may be bugs.

**Comment by xrchz** [comment]
Confirmed that it is an issue to do with caching in `ARITH_ss`: the following works:
```
val _ = app load ["integer_wordTheory","intSimps"]
val goal = dest_thm integer_wordTheory.INT_BOUND_ORDER;

val tactic1 = bossLib.RW_TAC (intSimps.int_ss ++ bossLib.ARITH_ss)
  [ integer_wordTheory.INT_MAX,
    integer_wordTheory.INT_MIN,
    integer_wordTheory.UINT_MAX,
    wordsTheory.BOUND_ORDER ];
val tactic2 = bossLib.RW_TAC (intSimps.int_ss ++ bossLib.ARITH_ss)
  [ integer_wordTheory.INT_MAX,
    integer_wordTheory.INT_MIN ];

tactic2 goal;
numSimps.clear_arith_caches();
tactic1 goal;
```
but fails if you don't call the cache clear.

**Comment by barakeel** [comment]
Thanks for the tip. I can fix the evaluation of TacticToe in integer_wordTheory now.

**Comment by mn200** [comment]
This is proving quite an interesting bug to fix!
