### ISSUE TITLE
TeX notation on Unicode chars doesn't work any more

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#480]
Currently in HOL's source code, there're two ways to define TeX notation for constants, e. g.

```
val _ = unicode_version {u = UChar.forall, tmnm = "!"};
val _ = TeX_notation {hol = "!", TeX = ("\\HOLTokenForall{}",1)}
val _ = TeX_notation {hol = UChar.forall, TeX = ("\\HOLTokenForall{}",1)}
```

But I think currently the last line using Unicode chars doesn't work any more.  As a result, all TeX notations defined on only Unicode chars  cannot generate any TeX notation any more, e.g. in `relationTheory`:

```
val _ = Unicode.unicode_version {u = UnicodeChars.union ^ UnicodeChars.sub_r,
                                 tmnm = "RUNION"}
val _ = TeX_notation { hol = UnicodeChars.union ^ UnicodeChars.sub_r,
                       TeX = ("\\HOLTokenRUnion{}", 1) }
```

But the two ways for defining TeX notations are not fully equivalent: if the Unicode symbol is defined as a prefix or suffix while the original logical constant is not, then setting TeX notation on the original logical constant will cause the TeX symbol appeared as wrong position. Thus sometimes it's necessary to set TeX notation on Unicode chars.

Can this issue be confirmed and fixed? Thanks.

**Comment by mn200** [comment]
If I create a munger, and run it on `\HOLtm{R1 RUNION R2}`, I get the desired output.  Similarly, if I write `\HOLtm{R1 ∪ᵣ R2}` I also get the desired output.  I’m not sure what you think the problematic behaviour is. 

Do you have a concrete test-case of something behaving “not the way you’d expect”?

**Comment by binghe** [comment]
What I saw for the same RUNION example is different:

I first created the following `Holmakefile` to save relationTheory into a heap and then make the `munge.exe`:

```
ifdef POLY
HOLHEAP = heap
OBJNAMES = relationTheory
DEPS = $(patsubst %,$(dprot $(SIGOBJ)/%.uo),$(OBJNAMES))

all: $(HOLHEAP)

$(HOLHEAP): $(DEPS) $(dprot $(HOLDIR)/bin/hol.state0)
	$(protect $(HOLDIR)/bin/buildheap) -o $@ $(OBJNAMES)
endif

all: $(TARGETS) munge.exe

munge.exe: 
	$(HOLDIR)/bin/mkmunge.exe relationTheory

.PHONY: all
```

then I created a Makefile for building my LaTeX test file:

```
MUNGE = ./munge.exe

all: test.pdf

test.pdf: test.htex $(MUNGE)
	$(MUNGE) < test.htex > test.tex
	pdflatex test
	pdflatex test

clean:
	@rm -f *.aux *.blg *.log *.tex *.bbl *.out

.PHONY: all
```

And this is my test file:

```
\documentclass[12pt, a4paper, twoside]{report}

% HOL support
\usepackage{holtexbasic}
\usepackage{alltt}

\begin{document}

\begin{alltt}
\HOLtm{!P Q. P ==> Q}
\end{alltt}

\begin{alltt}
\HOLtm{R1 RUNION R2}
\end{alltt}

\end{document}
```

When I execute `Holmake` and then `make` I'll get a PDF in which the relation union symbol doesn't show up at all. But to check the issue you can simply see the content in the `test.tex` file outputed by `munge.exe`, it is like this:

```
\documentclass[12pt, a4paper, twoside]{report}

% HOL support
\usepackage{holtexbasic}
\usepackage{alltt}

\begin{document}

\begin{alltt}
\HOLinline{\HOLSymConst{\HOLTokenForall{}}\HOLBoundVar{P} \HOLBoundVar{Q}. \HOLBoundVar{P} \HOLSymConst{\HOLTokenImp{}} \HOLBoundVar{Q}}
\end{alltt}

\begin{alltt}
\HOLinline{\HOLFreeVar{P} \HOLSymConst{∪ᵣ} \HOLFreeVar{Q}}
\end{alltt}

\end{document}
```

See, we have `\HOLSymConst{∪ᵣ}` here, the Unicode symbol `∪ᵣ` directly wrapped by `HOLSymConst`, but several months ago this was `\HOLTokenRUnion`, which has the following definitions in `holtexbasic.sty`:

```
\newcommand{\HOLTokenRUnion}{\ensuremath{\cup_r}}
```

Can you reproduce the issue with the same steps? or if my steps were wrong somehow.

Regards,

Chun Tian

**Comment by mn200** [comment]
Some comments:
* the `heap` you build in the `Holmakefile` does not seem to get used 
* you could put your Makefile commands for building the PDF into your `Holmakefile`
* Your dependency for building your hol-heap should be `hol.state` (not `hol.state0`) as the former is the default base heap.  If you do want to use `hol.state0` as your base, you need a `-b hol.state0` command-line option to `buildheap`
* `mkmunge`'s default base is also `hol.state`, which includes `relationTheory`, so you don't need to pass `relationTheory` as an argument to `mkmunge`.

I can't reproduce, with the following (slightly simpler) `Holmakefile`:
````
HOLHEAP = heap
CLINE_OPTIONS = -j1

MUNGER = $(HOLDIR)/bin/mkmunge.exe
OBJS = $(dprot $(SIGOBJ)/relationTheory.uo)

.PHONY: all output
all: heap munge.exe output

heap: $(OBJS)
	$(protect $(HOLDIR)/bin/buildheap) -o $@ $<

munge.exe: $(dprot $(MUNGER)) $(OBJS)
	$(protect $(MUNGER)) -o $@ relationTheory

output: munge.exe
	echo '\HOLtm{R1 RUNION R2}' | ./munge.exe


EXTRA_CLEANS = output heap
````

(I've included the building of a HOL heap though I think it should be unnecessary.)

When I run Holmake I get:
````
$ ~/mosHOL/bin/Holmake 
echo '\HOLtm{R1 RUNION R2}' | ./munge.exe
\HOLinline{\HOLFreeVar{R\sb{\mathrm{1}}} \HOLSymConst{\HOLTokenRUnion{}} \HOLFreeVar{R\sb{\mathrm{2}}}}
````
which is what I'd expect. 

Do you still see your buggy behaviour with the Holmakefile above?  (Are you on the most recent git commit?)

**Comment by binghe** [comment]
Thanks for the comments.

Strange ... I can't reproduce the issue any more (after rebuilding HOL from the very recent git commit), even with my previous steps and Makefiles.   I have to close this issue.
