### ISSUE TITLE
Unexpected behavior of SIMP_CONV

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#483]
In the following case, REWRITE_CONV gives the expected conversion while SIMP_CONV inserts a spurious λ-abstraction. Tested in Kananaskis-11 and a slightly modified 39fc24540:

```
> SIMP_CONV pure_ss [GSYM FUN_EQ_THM] “!x. f y x = g x”;  
<<HOL message: inventing new type variable names: 'a, 'b, 'c>>
val it =
   |- (∀x. f y x = g x) ⇔ ((λx. f y x) = g):
   thm
> REWRITE_CONV [GSYM FUN_EQ_THM] “!x. f y x = g x”;
<<HOL message: inventing new type variable names: 'a, 'b, 'c>>
val it =
   |- (∀x. f y x = g x) ⇔ (f y = g):
   thm
```

**Comment by mn200** [comment]
This is a side effect of the fact that `SIMP_CONV` uses higher-order pattern matching, whereas `REWRITE_CONV` is using first-order matching. There is an `ETA_ss` simpset fragment (in `boolSimps`) that can be used to eta-reduce the `(\x. f y x)` to `f y`.
