### ISSUE TITLE
tactictoe has no license

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#485]
tactictoe just states Copyright. Without a license, this [default to all rights reserved](https://www.gnu.org/licenses/license-list.html#NoLicense) (so it can no be legally distributed, modified, etc.):

```
(* ========================================================================== *)
(* FILE          : tacticToe.sml                                              *)
(* DESCRIPTION   : Automated theorem prover based on tactic selection         *)
(* AUTHOR        : (c) Thibault Gauthier, University of Innsbruck             *)
(* DATE          : 2017                                                       *)
(* ========================================================================== *)
```

There is some more code like that in HOL4 but I am opening an issue for this one specifically because it is actively developed and so there is an opportunity to correct this before the author eventually becomes unreachable.

**Comment by xrchz** [comment]
(I don't know if @barakeel looks at these issues regularly, but maybe they'll be notified by my mention.)

**Comment by barakeel** [comment]
I added a copyright notice to the tactictoe directory.

**Comment by marioxcc** [comment]
Thanks.
