### ISSUE TITLE
Document mp_then

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#489]
Here is a start

`mp_then` can be used when you have a theorem with some assumption (lhs of implication) that can be discharged by some other theorem/assumption you have. This is often the case with inductive hypotheses. It's great because it abstracts away from the low-level details of exactly where the assumption is located and instead does finding/matching for you (in a controllable way).

`mp_then <pos> <ttac> <th1> <th2>` is a tactic in the usual `_then` fashion which produces a theorem then applies the `<ttac>` continuation. `<th1>` and `<th2>` are the two theorems: one contains the implication, and the other has a conclusion matching one of the antecedents of the implication. `<pos>` indicates how to find the antecedent. It can be `Any`, which tells `mp_then` to search for anything that works. It can be `Pat <q>` which means find anything matching `<q>` that works. Or it can be `Pos <fn:term list -> term>` which uses the supplied function (often `(el <n>)`) on the list of all antecedents to pick the right one.

In practice, there are some common patterns for obtaining `<th1>` and `<th2>`. Apart from the fully applied version above, you might also see these:

`<sel>_assum (mp_then <pos> <th1>)`

`<sel>_assum (<sel>_assum o mp_then <pos> )`

`disch_then(<sel>_assum o mp_then <pos>)`, etc.

where `<sel>` = is something in `first`/`last`/`qpat`/`goal` possibly with an `_x` - the usual ways of obtaining theorems from the current goal.

(I'm less sure about this part - might be confusing myself.) `goal_assum` is worth special mention since it's especially useful with `mp_then`: it turns an existentially quantified goal `?x. P x` into the assumption `!x. P x ==> F` thereby providing a theorem with antecedents to match on. In conjunction with `mp_then` it has the effect of instantiating the existential quantifier in order to match a provided subterm (similar to `part_match_exists_tac` or `asm_exists_tac`).

**Comment by mn200** [comment]
Looks good to me.  We might refine to make it clear that the implication is the first theorem.  (You just say one is the implication, the other is the thing that matches an antecedent.)

**Comment by xrchz** [comment]
yes - that was unclear because I didn't know which was which :)
