### ISSUE TITLE
let-parsing does not fail on `let (h::t = [3;4]) in h`

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#496]
Reported by Joseph Chan.

**Comment by xrchz** [comment]
Why should it fail?

**Comment by mn200** [comment]
`let pat = e1 in e2` is supposed to be equivalent to `(\pat. e2) e1`.  We have no support for lambdas with cons arguments. The only allowed form for `pat` is what is in various places called a `varstruct`, which is basically a variable or a tuple.

**Comment by mn200** [comment]
I now better understand why this is happening: it's legitimate to write

    let f x y = x + y in f 3 2

and the parser interprets `let h::t = [3;4] in h` as an attempt to locally rebind `::` (read it as `let CONS h t = [3;4] in h`, *i.e.*, a local version of `CONS` that ignores its arguments and just returns the list `[3;4]`). 

Given this, I think the right behaviour is to emit a warning to the effect that the expression is rebinding a known constant.  (I don't think it should be illegal to do this.)

**Comment by mn200** [comment]
Actually, the rebinding of constants as bound variables has always been permitted, and is not remarked on by any part of the parsing process, so I think this can be entirely left alone.
