### ISSUE TITLE
The free instance of “x” in “∀x::{x}. T” is shown as bound

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#503]
In the command line interface of Kananaskis-11 and a recent development version (7389ca089) “∀x::{x}. T” and “RES_FORALL {x} λx. T” are printed as “∀x::{x}. T” with _both_ instances of “x” shown in green (i.e.: bound). I tested this in Emacs with the HOL interface in Kananaskis-11 and the result is the same (both instances of “x” shown in green).

**Comment by mn200** [comment]
Thanks for the bug report!
