### ISSUE TITLE
TheoryLexer issues

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#507]
I keep running into problems like this:
`... [too many lines to scroll back] ...
162%12@2%102@%12@2%46%89%116%33%33%34%34%33%34%34%34%33%34%33%33%34%141@15%116%34%33%33%141@5%12@2%46%30%31%67%51%116%33%33%33%141@5%162%116%34%33%34%33%33%34%34%34%34%33%33%34%141@18%102@%12@2%46%30%31%67%100%91@%116%34%34%141@4%27%116%33%34%34%141@5%162%116%34%33%33%33%33%33%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%34%141@70%102@%12@2%46%30%31%67%29%127%97@%116%33%33%33%141@5%116%33%33%33%141@5%116%33%141@7%102@%12@2%46%30%31%67%29%40%121@%116%34%141@3%116%34%34%34%141@5%122%116%34%34%34%141@10%102@%12@2%46%30%31%67%29%40%24@%116%33%33%33%141@5%116%33%33%33%141@5%122%116%34%141@8%102@%12@2%46%30%31%67%29%127%98@%116%34%34%141@4%116%34%34%141@4%116%33%34%33%141@9%102@%12@2%46%30%31%67%29%40%24@%116%33%33%33%141@5%116%33%33%33%141@5%122%116%34%34%141@9%102@%12@2%46%30%31%67%100%91@%116%33%33%33%141@5%27%116%33%33%33%141@5%162%116%34%33%33%141@10%102@%12@2%46%30%31%67%51%116%34%34%141@4%162%116%34%33%141@8%102@%12@2%46%30%31%67%29%40%24@%116%34%33%34%141@5%116%34%33%34%141@5%66%162%116%34%33%33%34%33%141@13%102@%12@2%46%88%68%87%116%33%33%33%34%34%33%33%34%33%33%33%141@13%12@3%162%12@2%102@%12@2%46%89%116%33%33%34%34%33%34%34%34%33%34%33%33%34%141@15%116%33%34%33%141@5%12@2%104@169%109@5093\"\n", origin_function = "lex_thydata", origin_structure = "TheoryLexer"} raised`
which led me to investigate `TheoryLexer.sml`. I notice a few issues there:
- `lex_thydata` handles all exceptions (with underscore pattern). I think this is bad style (one should at least let `Interrupt` pass through, right?)
- `lex_thydata` calls `explode` on a potentially very long string. This wastes memory. It would be better if the other code operated on a `substring` rather than a `char list`.

This issue is to fix the above two problems.

**Comment by xrchz** [comment]
Mentioning @barakeel just for reference.

**Comment by xrchz** [comment]
A little investigation revealed that it is probably in fact `Interrupt` getting handled in my case.

**Comment by barakeel** [comment]
Indeed, the underscore should be replaced `HOL_ERR _`,  it should catch the exception raised by `lex_helper` for easier debugging.

**Comment by barakeel** [comment]
The same problems appear in `TheoryReader`. One handle should be replaced. And the memory consumption is even a bigger problem since the whole file is stored in memory where as `lex_thydata` is only reading one line at a time.

**Comment by mn200** [comment]
This code should probably be using `mllex` and `mlyacc`.
