### ISSUE TITLE
DB.print_find has vanished, but the emacs mode expects it 

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#509]
The emacs mode command `hol-db-find` (bound to `M-h f`) emits a call to `DB.print_find`, which no longer exists. 

Commit 797ee1e5fa6a60c35715261030b9869d13b53e6e broke this. I think the right fix is probably to provide a PrettyDB or similar that comes later in the build sequence than `Parse`, and which can therefore do the pretty-printing that `DB` used to be able to.

**Comment by thtuerk** [comment]
Having something like `PrettyDB` sounds nice. It sounds like some work though. As a quick fix, however, I renamed `DB.print_find` in `hol-mode.src` to `Hol_pp.find_find` with commit bed25f076a9fd87fd9c9313ac25da7f998ab9586. This is where `DB.print_find` moved to in 797ee1e. A similar fix for `DB.print_match` was already used aef539970859818e1be2103154b44144cc2304ab.

P.S.: @mn200 I hope you don't mind me applying this tiny change without a pull request

**Comment by mn200** [comment]
Thanks Thomas!  I didn't realise this was available; I think what's now in `Hol_pp` subsumes what I imagined landing in `PrettyDB`, so this closes the issue.  Thanks again.
