### ISSUE TITLE
Extra RETURN with help request

### ISSUE THREAD

**Issue by jhlchan** [HOL-Theorem-Prover/HOL#516]
I notice recently that in a HOL session (a terminal session in a MacBook), typing:
help "topic-name";
requires an extra RETURN key to obtain the help information. This seems not to be the usual behavior.  This is just a bit annoying, especially for novices who don't realize an extra RETURN will work.

**Comment by marioxcc** [comment]
I have noticed this as well in GNU/Linux.

**Comment by mn200** [comment]
Thank you both for the reports.
