### ISSUE TITLE
Applied monad doesn't pretty-print properly

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#522]
With `errorStateMonadTheory` providing the `monad_bind` (making the types sensible), the following prints as itself rather than with `do ... od`:

    monad_bind m f s

**Comment by marioxcc** [comment]
Is the “do” syntax of theory `state_transformer` theory documented?

**Comment by mn200** [comment]
No.  Good catch — there's another issue there.

**Comment by mn200** [comment]
See now issue #523
