### ISSUE TITLE
Sign releases with OpenPGP

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#545]
For security, to avoid the possibility of Github tampering with in HOL4 releases without detection.

**Comment by binghe** [comment]
How can HOL4 releases be tampering with source-only releases? Some hackers (who is eager publishing papers on ITP conferences) could modify the HOL kernel so that even fake theorems can be proved? ^_^

**Comment by marioxcc** [comment]
GitHub or an unrelated third party with cooperation with a certification authority (to get a fake HTTPS certificate) can insert malware that will run with user privileges when somebody downloads the tarball and compiles HOL4. The malicious modifications are obviously not limited to making HOL4 unsound.

**Comment by mn200** [comment]
I already sign the tag-commit corresponding to the release.  I can also provide checksums for the generated tar balls that we make available as release downloads.

**Comment by marioxcc** [comment]
@mn200 I do not mean checksums per-se. My recommendation is that you publish OpenPGP signature files along with the tarballs as is standard practice. The command is `gpg --sign FILE_NAME`.

**Comment by mn200** [comment]
Of course, the check-sum has to be distributed via an alternative channel: signed e-mail to the mailing list, on our web-page, on the Github page, and on the SourceForge page.
