### ISSUE TITLE
“match_term” returns spurious matches when type instantiation aliases variables

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#546]
Tested in 4f2fc0f852c2307a with experimental kernel:
> val t = list_mk_comb (“f: 'a -> 'b -> 'c”, [“x:'a”, “x:'b”]);
val t = “(f :α → β → γ) (x :α) (x :β)”: term
> match_term t “(g :'a -> 'a -> 'b) a b”;
val it =
   ([{redex = “(f :α → α → β)”, residue = “(g :α → α → β)”},
     {redex = “(x :α)”, residue = “(a :α)”},
     {redex = “(x :α)”, residue = “(b :α)”}],
    [{redex = “:γ”, residue = “:β”}, {redex = “:β”, residue = “:α”}]):
   (term, term) Term.subst * (hol_type, hol_type) Term.subst

Edit: added type annotations to output.

**Comment by xrchz** [comment]
Could you say more about what is spurious/incorrect about this? It looks like a correct result to me, but I haven't looked hard.

**Comment by marioxcc** [comment]
The instantiation returned does not work because notionally it is a type instantiation followed by a term instantiation. The type instantiation makes both occurrences of «a» in «g a a» equal. The subsequent term instantiation would require different instances of the same variables to be substituted by different terms and therefore is inconsistent.

The terms in this example (and similar examples) that intuitively match could be made to actually match if “match_term” was allowed to return a term instantiation followed by a type instantiation followed by another term instantiation. That would allow the first term instantiation to be used to rename variables that would otherwise become the same after type instantiation.

**Comment by konrad-slind** [comment]
Standard kernel gives same answer. The generated substitution looks OK to
me. Type substitutions generally get applied before term substitutions.

Konrad.

**Comment by marioxcc** [comment]
Konrad: Look at it again with type annotations enabled. It is inconsistent even applying type instantiation first.

**Comment by konrad-slind** [comment]
Yes, I see it now. Thanks.

**Comment by xrchz** [comment]
I agree that this is a bug. At the least it's a bug in the documentation, which could be amended to note that the property `match_term`'s return value may not hold if `pat` contains variables with the same name but different types. The next simplest thing might be for the implementation to warn in this case.

**Comment by marioxcc** [comment]
The implementation should change to fit the current documented specification, not vice-versa, because a lot of code has been written assuming that the result of `match_term` can be passed to `INST_TY_TERM` (or equivalent) and your proposed change would break that code. Instead `match_term` should fail in this and other cases where matching is not possible using `INST_TY_TERM`.

**Comment by mn200** [comment]
I agree it's reasonable for the call to `match_term` to fail in this situation.

**Comment by mn200** [comment]
Actually, I'm not so sure that I want to change this.  This function is used a lot (which is why it is in the kernel (despite not needing to be there when viewed purely logically)) and I don't want to slow down something that is the workhorse of basic rewriting. I think I'd prefer to document the fact that it will give effectively unusable results if called with patterns that have the identified problem.

**Comment by konrad-slind** [comment]
I was going to have a go at re-implementing this, but I agree that the
replacement should not run measureably slower.

Konrad.

**Comment by konrad-slind** [comment]
BTW I have a branch going where I fixed this problem in term matching.
Minor changes to the libraries etc required. I did run into a problem when
building CakeML examples: one of the CF tactics didn't do the right thing.
I have not yet sorted that.

Konrad.
