### ISSUE TITLE
Define disallows underscores on the rhs, even in patterns

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#58]
(* fails *)
    val foo_def = Define`
      (foo ls = MAP (λ(_,n). n) ls)`
    (* works *)
    val foo'_def = Define`
      (foo' ls = MAP (λ(_u,n). n) ls)`
    (* for comparison, this works *)
    val mapthis_def = Define`
      mapthis (_,n) = n`

**Comment by acjf3** [comment]
This seems to have been fixed.
