### ISSUE TITLE
String literals no longer support non-UTF8 strings

### ISSUE THREAD

**Issue by bacam** [HOL-Theorem-Prover/HOL#632]
The string theory provides arbitrary 8-bit strings and until recently you could use escape sequences to put arbitrary characters into character and string literals.  Now the parser requires them to be legal UTF-8 sequences:
```
> ``#"\175"``;
Exception- BadUTF8 "\175" raised
> ``(^(stringSyntax.fromMLchar #"\175"))``;
val it = “#"\175"”: term
> “#"\175"”;
Exception- BadUTF8 "\175" raised
> ``"abcde\175fgh"``;
Exception- BadUTF8 "\175" raised
> ``^(stringSyntax.fromMLstring "abcde\175fgh")``;
val it = “"abcde\175fgh"”: term
> “"abcde\175fgh"”;
Exception- BadUTF8 "\175" raised
```
As you can see, they can still be supplied by antiquotations, but cut-and-pasting the output does not work.

I encountered this issue in Lem's test suite, although I don't know if any Lem developments actually use it.  If there's no enthusiasm for getting the parser to accept these literals I could make Lem produce the antiquotation workaround for difficult strings instead.

**Comment by myreen** [comment]
This looks like a HOL bug to me, since the term parser ought to be able to parse whatever the term pretty printer produces. In this case, the parser rejects the pretty printer's output:

    > ``CHR 177``;
    val it = “#"\177"”: term
    > “#"\177"”;
    Exception- BadUTF8 "\177" raised

I'm marking this as a bug and hope it if fixed so that Lem can again be used for HOL development.

**Comment by mn200** [comment]
Definitely a bug — thanks for the report.

**Comment by bacam** [comment]
Thanks, but there still problems with more complex terms:
```
> ``("abcde\175fgh")``;
Exception- BadUTF8 "\175" raised
> ``~ (#"\175" = #"\^^@")``;
Exception- BadUTF8 "\175" raised
```
Curiously, adding spaces around the literals helps.

**Comment by mn200** [comment]
Ha.  Thanks for this. I should have tested more thoroughly.  Indeed, spaces ensure that the problematic bits and pieces get isolated into a single “pre-token”.
