### ISSUE TITLE
Holmake dependencies in included directories

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#633]
`Holmake` currently fails to build dependencies whose recipes are in included directories. I don't know what the intended behaviour is; I consider this a bug, but one could consider it a feature request that `Holmake` not fail in these situations. It does not come up as often as it might because the targets of included directories usually get built during recursion.

Concrete example:
```
> Holmakefile
INCLUDES = bar
cp-bar.txt: bar/bar.txt
        $(CP) $< $@
EXTRA_CLEANS = cp-bar.txt

> cat bar/Holmakefile
foo.txt:
        echo "foo" >$@
bar.txt:
        echo "bar" >$@
EXTRA_CLEANS = foo.txt bar.txt

> Holmake
Working in bar
foo.txt                                                                         OK
Working in .
Don't know how to build necessary target(s): bar/bar.txt
```

The desired behaviour would be to do the equivalent of `Holmake bar.txt` in `bar` before attempting to build the `cp-bar.txt` target.

**Comment by mn200** [comment]
There is no way to implement this in a nice way without having implemented #382, which subsumes it, so I will close this as redundant.
