### ISSUE TITLE
DECIDE performance bug on disjunctions of equalities

### ISSUE THREAD

**Issue by konrad-slind** [HOL-Theorem-Prover/HOL#652]
Exponential slowdown on examples designed to be false.

fun testcase n =  (* generates false formula *)
 let val evens = filter (fn x => x mod 2 = 0) (upto 0 n)
     val v = mk_var("v",numSyntax.num)
 in
    ``v < 256 ==> 
       ^(list_mk_disj(map (fn n => mk_eq(v,term_of_int n)) evens))``
 end;

fun test n = (time DECIDE (testcase n); ()) handle _ => ();
 
List.app test (upto 2 30);

**Comment by konrad-slind** [comment]
... actually it has nothing to do with whether the formula is false.

... as a workaround for this class of formulas I have been using 

     REPEATC(numLib.BOUNDED_FORALL_CONV EVAL)

**Comment by mn200** [comment]
This is a duplicate of #474.

The issue is the conversion to DNF. A workaround would be to spot if the equalities can be replaced with an upper and lower bound: `(x = 10) \/ (x = 11) \/ ... \/ (x = 25)` turns into `(10 <= x) /\ (x <= 25)`.

**Comment by konrad-slind** [comment]
Right, it does seem to be a duplicate. In my scenario, I am testing
membership of x in a set (not more than 256 elements) so trying to find
interval bounds isn't going to help.
