### ISSUE TITLE
Remove superseded lcsymtacs structure

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#666]
Given implementation of issues such as #274 and #275, the `lcsymtacs` module in `src/boss` seems unnecessary.  (All it does by way of implementation is `open` a bunch of other modules.)

**Comment by arolle** [comment]
Before creating a pull request I have one question:
Are there any severe implications from simply removing an `open lcsymtacs` statement from a theory script in `src` (if it compiles without it), e.g. from `src/new-datatype/NDDB.sml`?

**Comment by mn200** [comment]
No, there shouldn't be any issues with doing that.  — Thanks!

**Comment by mn200** [comment]
Closed by 5417af9
