### ISSUE TITLE
Possible omission in Description at 1.1 (pp. 18)

### ISSUE THREAD

**Issue by ahmedwaqar** [HOL-Theorem-Prover/HOL#669]
By executing the following command in the HOL shell returns exception

mk_thy_type{Tyop="bool", Thy="bool", Args=[]} 

Exception-
   HOL_ERR
     {message =
      "the type operator \"bool\" has not been declared in theory \"bool\".",
      origin_function = "mk_thy_type", origin_structure = "Type"} raised

This is because the type 'bool' is defined in theory 'min'. By making this correction, the issue is resolved

mk_thy_type{Tyop="bool", Thy="min", Args=[]};
val it = “:bool”: hol_type

I also found that there is a missing "]" at the end in 

mk_thy_type{Tyop="fun", Thy="min",
                     Args=[mk_vartype "’a",
                                mk_thy_type{Tyop="bool", Thy="bool", Args=[]}**]**}

**Comment by mn200** [comment]
Thanks for this—now fixed.

**Comment by ahmedwaqar** [comment]
Thanks. Please, also make the same change at 1.3 pp. 20.

**Comment by mn200** [comment]
Fixed in 03bd32ffe; thanks!

**Comment by ahmedwaqar** [comment]
Thanks!
