### ISSUE TITLE
`bin/build` fails on `FinalThm.ui`

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#683]
`bin/build` fails with this message:

    Building directory src/0 […]
    Don't know how to build necessary target(s): /…/sigobj/FinalThm.ui
    Build failed in directory /…/src/0 (exited with code 1)

Prior to this, it said:

    Using kernel spec --stdknl from earlier build command

There was no error during `poly < tools/smart-configure.sml`.

Using latest PolyML, latest MLTon and latest HOL.

**Comment by Hibou57** [comment]
Either it was me, either it works when using the ZIP archive instead of a repository clone. I prefer to close this issue, since it may be irrelevant.

**Comment by ahmedwaqar** [comment]
Try using polyml 5.7...

**Comment by xrchz** [comment]
I doubt the problem has to do with Poly/ML. I would guess that you didn't start from a clean state. You can clean first with `bin/build cleanAll`, or to be even more sure use a fresh clone or use `git clean -xdf` on your existing clone.
