### ISSUE TITLE
building set_mtime.exe fails with "Signal B"

### ISSUE THREAD

**Issue by samuelgruetter** [HOL-Theorem-Prover/HOL#687]
I tried to install HOL by following https://github.com/CakeML/cakeml/blob/master/build-instructions.sh and https://hol-theorem-prover.org/#get and https://github.com/HOL-Theorem-Prover/HOL/blob/master/INSTALL. Installing poly succeeded, and running HOL's `tools/smart-configure.sml` succeeded as well, but `bin/build` failed.

Poly version: master
HOL version: tried both master and kananaskis-12
OS: Fedora 29

```
$ export PATH=/home/sam/installs/polyml-889f7c37/bin:$PATH

$ declare -x LD_LIBRARY_PATH=/usr/local/lib:/home/sam/installs/polyml-889f7c37/lib/

$ poly < tools/smart-configure.sml 

Poly/ML 5.8 Release (Git version v5.8-21-g889f7c37)

HOL smart configuration.

Determining configuration parameters: holdir OS poly polymllibdir 
OS:                 linux
poly:               /home/sam/installs/polyml-889f7c37/bin/poly
polyc:              /home/sam/installs/polyml-889f7c37/bin/polyc
polymllibdir:       /home/sam/installs/polyml-889f7c37/lib
holdir:             /home/sam/src-for-install/HOL
DOT_PATH:           SOME /usr/bin/dot
MLTON:              NONE

Configuration will begin with above values.  If they are wrong
press Control-C.

Will continue in 1 seconds.

Loading system specific functions
Compiling system specific functions (sig sml)
Beginning configuration.
Removing old quotation filter from bin/
Making mllex
Making mlyacc

Number of states = 95
Number of distinct rows = 47
Approx. memory size of trans. table = 6063 bytes
Making Holmake

Number of states = 1020
Number of distinct rows = 847
Approx. memory size of trans. table = 1734656 bytes
Making unquote.
Making holdeptool
Making build
Making heapname
Making buildheap
Making genscriptdep
Making hol-mode.el (for Emacs/XEmacs)
Making tools/vim/*
Generating bin/hol.

Finished configuration!
val it = (): unit

$ bin/build cleanAll
Cleaning out /home/sam/src-for-install/HOL/sigobj
/home/sam/src-for-install/HOL/sigobj cleaned

$ bin/build 
*** Using kernel spec --stdknl from earlier build command;
    use one of --expk, --stdknl, --otknl to override
Cleaning out /home/sam/src-for-install/HOL/sigobj
/home/sam/src-for-install/HOL/sigobj cleaned
Building directory tools/set_mtime [03 Apr, 10:43:05]
set_mtime.exe                                                                                        FAILED! <Signal B>
Build failed in directory /home/sam/src-for-install/HOL/tools/set_mtime (exited with code 1)
```

On the other hand, if I manually do

```
$ polyc tools/set_mtime/set_mtime.sml
$ ./a.out ./a.out std.prelude 
```

I can use the created program to set the file modification time of `a.out`, so it seems that compiling `set_mtime.sml` works on my system, but somehow the make process thinks it does not work. Any idea what's going wrong?

**Comment by Hibou57** [comment]
I remember I got a similar message too. I can just tell I did not get it building from the ZIP archive. Also, although not sure it’s related, be sure to build from a clean directory, that is, to delete any prior HOL4 installation before building the new one.

Not sure it will help, but may be …

**Comment by mn200** [comment]
Can you try with an older version of PolyML please (5.7, or 5.7.1)?

**Comment by mn200** [comment]
Also, does `build -j1` work?

**Comment by samuelgruetter** [comment]
So I downgraded to PolyML 5.7.1 and built with `-j1`, and it worked, thanks for your help!

**Comment by mn200** [comment]
Testing those two things independently would also be useful.  I.e., can you build with 5.8 and `-j1`, and can you build normally (actually `-j4`) with 5.7?

**Comment by minchaowu** [comment]
@mn200 5.8 I had the same problem and can confirm that 5.8 with `-j1` worked.

**Comment by mn200** [comment]
Thanks for this.  I think there's something broken in 5.8's handling of the fork/exec stuff in Holmake under 5.8.

**Comment by mn200** [comment]
To get parallel Holmake back, try installing `mlton` and making sure that the configure step sees that you have `mlton` installed.  Configure will then compile Holmake with `mlton` rather than poly and the segmentation faults should stop.

**Comment by mn200** [comment]
I believe this is now fixed on Poly/ML’s master branch.

**Comment by samuelgruetter** [comment]
Thanks for the fix, so I just tested various combinations:

* poly 5.7.1 works with parallel build
* poly 889f7c37 (master of Mar 29) works with `-j1` but not with parallel
* poly ad32de7f (master of Apr 7) works with parallel build

So everything is fine and corresponds to your expectations, if I understood correctly.

**Comment by mn200** [comment]
Many thanks @samuelgruetter for putting in the time to test these various combinations!  

That is indeed what I was expecting/hoping to see.
