### ISSUE TITLE
Fix TacticToe (Possibly provide a better sml lexer)

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#690]
From Yassmeen:

- tactictoe should support the following character.
Exception-
    HOL_ERR
      {message = "\\r", origin_function = "lex_helper", origin_structure =
       "smlLexer"} raised

- Use `maxint` to determine the prime number in the hash function in `aiLib` to avoid 32bit integer overflow.

I also experienced a recent error during recording:
TacticToe: ttt_rewrite_thy: sum
  /home/thibault/HOL/src/coretypes/sumScript.sml
Exception-
   HOL_ERR
     {message = "", origin_function = "wait_endquote", origin_structure =
      "smlLexer"} raised

**Comment by barakeel** [comment]
The unquote binary gives the wrong result on the new Theorem-Proof syntax and I am relying
on it to pre-parse the file. (Disclaimer: I merge my developments from develop)

For example in sumScript.sml, it returns:

Theorem SUM_MAP_o:\n\
\  (f ++ g) o (h ++ k) = (f o h) ++ (g o k)"],

**Comment by mn200** [comment]
If you are running it in the 
```
  unquote infile outfile
```
style, you need to add a `-i` flag to get the `Theorem` syntax to be translated.  (You can be confident that the `unquote` tool must work: it is used by the Moscow ML implementation, and that is tested every night.)

Alternatively, if you run it as a filter, e.g.,
```
  unquote < sumScript.sml > myoutput
```
it will do the “interactive”-mode translation by default.

**Comment by barakeel** [comment]
In numpairScript.sml:

val tri_def = Define[QUOTE " (*#loc 14 22*)\n\
\  (tri 0 = 0) /\\\n\
\  (tri (SUC n) = SUC n + tri n)\n\
\"];
I don't think the second " should be escaped. 
It was running unquote -i. I'll try running unquote < file > file.

**Comment by barakeel** [comment]
Is it possible that backslash after a newline cancel the newline and should be handle as a special case?

**Comment by barakeel** [comment]
It seems the problem is that I am printing out the output of unquote to a file and when reading the file the characters \  " are read as \ ".

**Comment by mn200** [comment]
SML backslashes in string literals can be used to escape arbitrary sequences of whitespace, including new lines.  Thus:
    “Hello, \       \world”
or even
    “Hello, world\      \”

**Comment by barakeel** [comment]
Thanks for your help Michael, now TacticToe works again. 
I updated the branch thibault-wip and the update will be soon push into develop.
