### ISSUE TITLE
Regression and performance tests for TacticToe and Hol(y)hammer.

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#691]
Regressions tests should be implement for TacticToe and HolyHammer so that the
functionnality and performance does not degrade over time. 
Indeed, the TacticToe recording is quite sensible to changes in the code base.

Possible issues:
The evaluation of TacticToe on the full standard library may take several hours/days depending 
on the parameters. The evaluation of Holyhammer depends on external tools such as Eprover.

**Comment by mn200** [comment]
I can arrange to run regression tests more infrequently (once per week, say) for long tests, which could be labelled as test-level 4.  (Or a custom build sequence could be used that didn't do the `theorem-prover` and `machine-code` examples and did test TacticToe and HolyHammer.)

I'd also strongly suggest that small unit tests of important functions might be plausible without doing full evaluations.

**Comment by barakeel** [comment]
For now, i will evaluate them manually on the Prague server every 3 to 6 months or so.
I may run an evaluation just before the release too. General results are posted on my website but should also include results for a few selected theories to be able to see the effects of changes to tacticToe and holyHammer.
