### ISSUE TITLE
Remove eqtype in FinalType-sig.sml

### ISSUE THREAD

**Issue by immler** [HOL-Theorem-Prover/HOL#695]
This is somewhat similar to the work on removing the eqtype constraint from terms (https://github.com/HOL-Theorem-Prover/HOL/pull/643).
In contrast to terms, ML-equality of types is perfectly fine.

But it is thinkable that one wants to implement a kernel where type is not an eqtype (which is e.g., the case for types in Isabelle).

**Comment by immler** [comment]
@Jonas-R and I would be willing to work on this.
Are there arguments against such a change?

**Comment by mn200** [comment]
I'm not very keen — it would break existing code unnecessarily, and also remove a facility that future programmers might want to use.  (For better or worse, equality is a privileged operation in SML, and having to work wrt other notions of equality *is* painful.  In the case of terms, I think the pain is necessary.)

**Comment by konrad-slind** [comment]
Agree with Michael. There's a staggering amount of equality checks on types.
