### ISSUE TITLE
Confusing message from Holmake

### ISSUE THREAD

**Issue by konrad-slind** [HOL-Theorem-Prover/HOL#699]
I get the following behaviour from an invocation of Holmake :

$~/Projects/HOL/bin/Holmake
*** Switching to execute /home/guardol/bin/Holmake
*** (Honouring last Holmake call in this directory)

So although I have explicitly selected which Holmake to run, I get a message telling me that a (possibly) different Holmake is being executed instead. Since the switched-to Holmake is identical (because of a symbolic link) to the designated Holmake, there is no harm in this case. But in general it seems like the "switched-to" Holmake could be unwanted.

**Comment by mn200** [comment]
I will update to tell user about `--no_lmbc` flag.

**Comment by konrad-slind** [comment]
Ah! The --no_lmbc flag .... actually the --nolmbc flag to us pedants.

Enjoy Sweden. I wish I were going.

Konrad.

**Comment by mn200** [comment]
Those pedants are no fun!
