### ISSUE TITLE
Function that provides single-line definition theorems

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#704]
There is a tool in the CakeML translator that takes multi-line definitions that contain pattern matches on the left-hand side of equations, such as:

    foo (SUC n) = if n = 0 then 4:num else foo (n-1)

It produces theorems that describe the same constants with equations that only have `const var1 var2 ... varN` on the left-hand side.

    ⊢ ∀x.
         (?n. x = SUC n) ⇒
         (foo x = case x of
                  | 0 => ARB
                  | SUC n => if n = 0 then 4:num else foo (n-1))

Note that `?n. x = SUC n` had to be added as an assumption to make the proof go through.

It would be nice if this functionality was provided by HOL. I suspect TFL already has part of the required functionality.

The current implementation used by CakeML is a hacked up monstrosity that was developed because HOL lacked this important functionality!

**Comment by mn200** [comment]
This is now implemented by `DefnBase.one_line_ify`.
