### ISSUE TITLE
Parse time of long compound tactic.

### ISSUE THREAD

**Issue by talsewell** [HOL-Theorem-Prover/HOL#714]
I've just done some exploration of a tactic from CakeML that took nearly 2 minutes to parse. I've checked that it's really parsing, at the SML level. The quote filter finishes instantly and by copying out some of the inner tactic compositions into separate declarations I can drop the parse time by an order of magnitude (1m53s -> 9s reported on my machine).

The proof actually takes about 1 minute to run. The wasted time is mildly annoying by default, and extra annoying if you're playing with --fast or Tactic.set_prover to restore your working state when moving between machines.

The tactic proves compile_exps_correct in clos_to_bvlProof
( https://github.com/CakeML/cakeml/blob/master/compiler/backend/proofs/clos_to_bvlProofScript.sml )

The approximate shape of the tactic is:
```
  ho_match_mp_tac induct_rule
  THEN1 (* NIL case *) ( ... )
  THEN1 (* CONS case *) ( ... )
  ... 10 more THEN1's comprising 2000-odd lines of steps
  (* last case *)
  \\ step
  \\ step
  ... 400 more lines of steps
  \\ metis_tac []
```

It happens that I could cut the parse time enormously by parenthesising the tactic composition for the final case. (1m51s -> 18s reported on my machine) Are the precedences for the infix operators ambiguous in a way that forces PolyML to think too much? Or is it just the case that enormous combinator scripts are terrible and need to be handled with care?

**Comment by mn200** [comment]
Wow, that's interesting.  Can you try to reproduce it with less HOL context and send it to David Matthews?

**Comment by mn200** [comment]
I have a similar example where the suffix is just 4 lines (6 `THEN`s), but the case-split is 75-way (it's the PEG completeness proof). When you say "parsing", you mean just that, I take it?  It's not type checking?  Precedence parsing should not be slow, but the parsing of everything else that happens before the precedences are resolved, and realising where the infix operators are might well be.

**Comment by mn200** [comment]
Some of this may also be due to too much evaluation/work happening before the tactic is actually applied.  For example: 
```
ho_match_mp_tac TRUTH >> qx_gen_tac `pt`
```
gives
```
Exception-
   HOL_ERR
     {message = "Bad theorem", origin_function = "HO_MATCH_MP_TAC",
      origin_structure = "Tactic"} raised
```
demonstrating that `ho_match_mp_tac` is doing work too early.  Similarly, `simp[th1,th2]` may do work before it sees a goal (I'll have to look into this).

On the other hand, this doesn't explain why reassociating should make a difference.

**Comment by mn200** [comment]
More notes: `ASM_SIMP_TAC` is fine, but `simp` builds its simpset (using `++`) before the goal is seen.  In particular, every call to `simp` applied to arguments folds in the arithmetic decision procedure to the stateful simpset.  This does represent some work:
```
> time simp [];
```
gives me back elapsed times of ~0.001s.  Now even in a 2000 line tactic, that should only be a couple of seconds though.

**Comment by mn200** [comment]
More notes: evaluating a 200 line tactic, once lexed/parsed/compiled, takes 0.05s, but total time elapsed, which would include all those other things, takes 0.25s.

**Comment by mn200** [comment]
I attempted to derive a demonstration of the problem in PolyML/PolyML#137 (and Phil Clayton followed up with similar PolyML/PolyML#138), and both are now apparently fixed.

**Comment by binghe** [comment]
I think the building time of some HOL core theories (those with large proofs) is greatly shortened after the fixes of Poly/ML:

- measureTheory, before: 31s, after: 23s (`CARATHEODORY_SEMIRING` and its lemmas)
- borelTheory, before: 35s, after: 24s (constructions of `lborel`)
- martingaleTheory, before: 66s, after: 48s (`EXISTENCE_OF_PRODUCT_MEASURE` and `TONELLI`)
- probabilityTheory, before: 85s, after: 50s (`SLLN_uncorrelated` and `WLLN_uncorrelated`)

--Chun

**Comment by mn200** [comment]
Yes, over the whole core distribution I think I see a 109s improvement in theory build times (915s down to 806s).   I'm confident it will greatly help with CakeML, where proofs tend to be very large.  For example, on a couple of script files I just tested there, I get reductions from 128s to 40s, and from 257s to 128s.
