### ISSUE TITLE
Make Q.SPEC_THEN do type instantiation

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#718]
Having to occasionally use `Q.ISPEC_THEN` is a pain, and its implementation is arguably buggy in that it is not guided by free variables in the argument theorem's assumptions.

**Comment by AndreasLoow** [comment]
On a related note, there's a bug in `ISPEC` (and `ISPECL`). We have the following code in `ISPEC`:

```
SPEC t (INST_TYPE inst th)
handle HOL_ERR _ => err "type variable free in assumptions"
```

But `INST_TYPE` never fails.

What I did to fix this was the following:

```
fun ty_in_hyp_tyvars inst th = let
  val tys = map #redex inst
  val hyp_tys = hyp_tyvars th
in
  exists (curry HOLset.member hyp_tys) tys
end

[...]

if ty_in_hyp_tyvars inst th then
  err "type variable free in assumptions"
else
  SPEC t (INST_TYPE inst th)
```

But maybe there are more efficient ways to do it...
