### ISSUE TITLE
Reorient "bad" equalities in simplifier

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#721]
Implement a conversion that flips equalities which have `l = r` where `l` has no free variables and `r` does. I think this conversion could then be on by default in the stateful simpset.

**Comment by arolle** [comment]
I implemented `REORIENT_EQ_CONV` (in a08046e60e23a69fd8f7b455f8d84b5143f643a0). In which script file should the stateful simpset be extended?

**Comment by mn200** [comment]
Please embed the conversion in a simpset fragment (something like `REORIENT_EQ_ss`) in `boolSimps` and then separately add that fragment into the stateful set up in `BasicProvers`.

Make sure the conversion and the fragment have names so that they can be readily removed.

**Comment by arolle** [comment]
`boolSimps.NORMEQ_CONV` and `boolSimps.NORMEQ_ss` seem to already implement this functionality.

**Comment by mn200** [comment]
Closed by #794 and follow-up work.
