### ISSUE TITLE
Emacs mode doesn't like term inside antiquotation in goal

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#723]
When my cursor is at the beginning of the line starting `^` in the following, 
```
Theorem foo:
  ^(K ``T`` ``T``)
Proof
  simp []
QED
```
and I press `M-h g` in Emacs to load the goal, I get the following error message:
```
> # Exception-
   HOL_ERR
     {message = "at line 1, character 7:\nParse failed", origin_function =
      "Absyn", origin_structure = "Parse"} raised
> Exception- NO_PROOFS raised
```

I note that this works:
```
Theorem foo:
  ^(K T T)
Proof
  simp []
QED
```

The first example also works if I just select the whole `Theorem ... QED` region and press `M-h M-r`.

**Comment by mn200** [comment]
The `M-h g` command is not clever enough to parse that term and gets confused by things that it thinks are delimiters.  However, there is a solution already: highlight the region you want to send, and use the prefix command to stop it from worrying about delimiters.  Thus: highlight 
```
  ^(K ``T`` ``T``)
```
and type `C-u M-h g`
