### ISSUE TITLE
Hol_pp.html_theory generates theorems and definitions in descending order

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#725]
Hi,

I ever learnt to use `Hol_pp.html_theory` to generate HTML files for my theory scripts, but I found that, in these generated HTMLs, all definitions and theorems are sorted in case-insensitive alphabet **descending** order, i.e. from zZ to aA. Maybe this is not a bug, but I feel quite unnatural reading these HTML files ...  for instance, if you built the CCS example, there're such HTML files generated in the same folder.

The other command `Hol_pp.print_theory_to_file`, on the other hand, generates TXT files in which all definitions and theorems are in case-insensitive alphabet **ascending** order, which looks much better.

Is this possible that `Hol_pp.html_theory` can be fixed by generating theorems and definitions also in **ascending** order?

--Chun

**Comment by mn200** [comment]
I totally agree that this seems silly.

**Comment by binghe** [comment]
Thanks!
