### ISSUE TITLE
drule shouldn't move around quantifiers

### ISSUE THREAD

**Issue by AndreasLoow** [HOL-Theorem-Prover/HOL#727]
I just noticed the following, not sure if it's new `drule` behaviour or if I just haven't noticed it before. I have the following assumption (last):

```
   98.  ∀cenv' nl min max.
            sum_foldM cell_run cenv'' nl = INR cenv' ∧
            netlist_ok min max nl ∧ si_lt bsi min ⇒
            ∀var.
                cell_inp_run cenv' (cget_net bsi var) =
                cell_inp_run cenv'' (cget_net bsi var)
```

and when I do `first_x_assum drule` I get the following goal:

```
(∀min max var.
             netlist_ok min max fnl ∧ si_lt bsi min ⇒
             cell_inp_run cenv'³' (cget_net bsi var) =
             cell_inp_run cenv'' (cget_net bsi var)) ⇒ [...]
```

Notice how the quantifier for `var` has been moved to the top. I think it would be better if `drule` did not move around quantifiers like that. (Moving around quantifiers like that will make using `impl_tac` impossible afterwards a series of `drule`s sometimes.)

**Comment by mn200** [comment]
It's not new; the normalisation done by `mp_then`, which is what implements `drule`, will move variables out in this way.  This gives `mp_then` uniform access to all of the theorem's hypotheses. Unfortunately for `drule`, this will unnecessarily move the `var` quantification out in your case. 

You can renormalise the theorem that `drule` puts into the goal with

     drule_then (mp_tac o SIMP_RULE bool_ss [RIGHT_FORALL_IMP_THM])

We might also think about making `impl_tac` smarter: when it sees `(!x. P ==> Q x) ==> R`, it could give you `P` to prove...

**Comment by AndreasLoow** [comment]
Thanks for the info, the more general `impl_tac` seems like a good idea, and that would also be useful in other situations. (The very best thing would be to not have `drule` move around things, but I'm not familiar with the implementation of `drule` and I'm sure there are good reasons for the current behaviour. Now at least I know that it's not a bug.)
