### ISSUE TITLE
Make Holmake show build times by default

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#729]
Currently, `Holmake` produces output such as:
```
targetPropsTheory                                                CHEATED
closPropsTheory                                                  CHEATED
stackPropsTheory                                                 CHEATED
README.md                                                             OK
bvlPropsTheory                                                        OK
wordPropsTheory                                                       OK
```
I miss the timing information that one used to get before `Holmake` was parallel (and that one gets now with `-j1`). Example:
```
Theory "flat_to_closProof" took 40.2s to build
```
I suspect showing build times will make some people produce faster files. 

Would it be possible to have build times shown by default in current Holmake output? Suggestion:
```
targetPropsTheory                                           0.1s CHEATED
closPropsTheory                                             0.3s CHEATED
stackPropsTheory                                            5.3s CHEATED
README.md                                                   0.1s      OK
bvlPropsTheory                                             55.2s      OK
wordPropsTheory                                            90.5s      OK
```

**Comment by mn200** [comment]
Good idea.  The information is present in the logs written to the `.hollogs` directory, so it shouldn't be too hard to extract it and present it.

**Comment by mn200** [comment]
In fact, Unix (and the SML Basis's POSIX library) allows for elapsed cpu time to be queried for children (presumably a call to something like `getrusage`), so I can do this without having to grep through log-file output.
