### ISSUE TITLE
HOL Theory Hierarchy (clickable) disappeared...

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#749]
Hi (Michael),

I don't know which recent commit caused this, but the HOL Theory Hierarchy (clickable), or Theory Graph, like those in [1], disappeared. In another words, the generated SVG picture (`theories.svg`) from `theories.dot`, although still contains all information*, now it's not clickable or viewable from the HTML page `theories.html`.

Can you reproduce this strange issue?

--Chun

[1] https://hol-theorem-prover.org/kananaskis-13-helpdocs/help/theorygraph/theories.html
* If I open the SVG file by Adobe Illustrator, I can still see the theory graph. If I chose to generate a PDF from the `.dot` file, the PDF looks perfect.

**Comment by AndreasLoow** [comment]
Strange! If I replace `scale` in this element:

```
<g id="graph0" class="graph" transform="scale(4.48 4.48) rotate(0) translate(4 4423.4)">
```

such that I get the following:

```
<g id="graph0" class="graph" transform="scale(0.223446 0.223446) rotate(0) translate(4 4423.4)">
```

I get the graph back (the scale values are based on an old graph that works). But I don't see anything in the `.dot` file that relates to scaling, so I'm not sure what is causing this strangeness.

**Comment by AndreasLoow** [comment]
If I remove the `size` attribute in the `.dot` file the graph can be generated correctly (although, the graph is very big if you open in directly in your browser, but I guess this does not matter much as you can simply scale it when you include it in the HTML documentation page). Might be a bug in the dot program, not sure?

**Comment by binghe** [comment]
I did some tests by adjusting `theories.dot` and `theories.html`, and the best solution I found is the following:

1. All size & space restrictions (except the font size) in `theories.dot` are removed, i.e. the following three lines are removed: (their units are inch)

```
     size = "16,16"
     ranksep = 1.0
     nodesep = 0.30
```

2. In `theories.html`, I added an attribute `style="width: 100%;"` to the `<object>` block containing the SVG file, making sure its width is always the *same* as the current page width (i.e. the width of your browser window):

```
<object data="theories.svg" type="image/svg+xml" style="width: 100%;">HOL Theory Map</object>
```

In this way, the SVG picture in the resulting HTML page, without any scaling, is still readable.

--Chun

**Comment by binghe** [comment]
> If I remove the `size` attribute in the `.dot` file the graph can be generated correctly (although, the graph is very big if you open in directly in your browser, but I guess this does not matter much as you can simply scale it when you include it in the HTML documentation page). Might be a bug in the dot program, not sure?

I think the essential reason is, the dot program tries to put the ever-increasing number of theory nodes inside a 16-inch square box and it eventually failed.  Increasing `size` or just removing it partially solves the problem, but the resulting SVG becomes too big and it's not scaled when displaying in HTML.   My solution above is to get the dot problem enough flexibility and then let HTML to do the rest scaling work.

P. S. The `fontsize=30` in dot file is necessary for reducing the margins between node texts and node boxes, because the default node fontsize is 14.

**Comment by binghe** [comment]
Hi Machael,

the issue is still there. Does my proposed fix make sense to you? I didn't submit a PR only because I don't know which code files to modify (to change the generated the `.dot` and the `.html` file )...

Regards,

Chun

**Comment by mn200** [comment]
Change `help/src-sml/DOT`.

**Comment by AndreasLoow** [comment]
@binghe: Maybe it would make sense to report this as a dot bug as well? Becuase what happens here seems like broken behaviour to me. But maybe it's common that dot does this/difficult to find a small example that reproduces this/something else... Just wanted to add this anyhow.

**Comment by binghe** [comment]
> @binghe: Maybe it would make sense to report this as a dot bug as well? Becuase what happens here seems like broken behaviour to me. But maybe it's common that dot does this/difficult to find a small example that reproduces this/something else... Just wanted to add this anyhow.

I don't think this is a bug of `dot` program. As I explained, the previous configuration in `theories.dot` file generated by HOL, has `size = "16,16"` which ask `dot` program to find a way to put all theory nodes inside a 16x16 inch square box. But as the number of core theories keeps growing, eventually this configuration becomes impossible.

**Comment by AndreasLoow** [comment]
Sure, but a more understandable behaviour from dot would be to exit with some kind of error than generate nonsense output if it cannot place the input nodes in a reasonable manner.

**Comment by AndreasLoow** [comment]
(And IIRC increasing size here does not help.)

**Comment by binghe** [comment]
> (And IIRC increasing size here does not help.)

Not entirely true. The following parameters, together with the scaling at HTML side, produces even better outputs than my previous idea:

```
     size = "100,100"
     ranksep = 1.0
     nodesep = 0.20
```

It's even readable on relatively small screen size (1440x900) (I attached a screenshot from Windows/Edge).

Graphviz has more than 1,000 open issues [1] and has "almost no maintainers of the code any more" [2], including some bug reports specific to SVG outputs. I'll file an issue there later, but I don't expect to get any answer shortly.

[1] https://gitlab.com/graphviz/graphviz/issues
[2] https://gitlab.com/graphviz/graphviz/issues/1627

![2019-12-17 10 15 44 am](https://user-images.githubusercontent.com/163421/70982116-b91c5580-20b6-11ea-9a84-a065b7b3d414.png)

**Comment by binghe** [comment]
I reported an issue [1] to Graphviz, feel free to comment if my issue description there is not precise enough.

[1] https://gitlab.com/graphviz/graphviz/issues/1639

**Comment by binghe** [comment]
People from Graphviz community said [1] that that was a bug of dot [2] introduced in graphviz between 2.38 and 2.43 and was fixed about one month ago.

I was using 2.43 but now I downgraded to 2.40 and it works. Thus there's no need to merge anything. Closing the issue. Thanks to @AndreasLoow for the suggestion of submitting bug report to Graphviz.

[1] https://gitlab.com/graphviz/graphviz/issues/1639#note_261928195
[2] https://gitlab.com/graphviz/graphviz/issues/1605

**Comment by mn200** [comment]
Perhaps we could try feeding our DOT files into different tools (ones that are still being developed). For example, the [gephi tool](http://gephi.org) might be one such (though it's focus is not quite the same as graphviz’s).

**Comment by binghe** [comment]
> Perhaps we could try feeding our DOT files into different tools (ones that are still being developed). For example, the [gephi tool](http://gephi.org) might be one such (though it's focus is not quite the same as graphviz’s).

This is the "typesetting" result of Gephi, in which you can use mouse point to move those black dots (each corresponding to one theory) ...

![2019-12-19 02 00 18 pm](https://user-images.githubusercontent.com/163421/71175526-14da1080-2268-11ea-9030-afdda36e09df.png)

**Comment by mn200** [comment]
Hmm; perhaps not such a great choice for our needs :)
