### ISSUE TITLE
make set_name_variant reusable

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#75]
See notes on 898866f.
The code in src/experimental-kernel/Term.sml for set_name_variant gets roughly duplicated a lot. Its basic functionality should be in Lib. As a first reaction, I think the "next name function" should be an argument, with reasonable choices, like append the number, made available in Lib, and the set should be a HOLset (since lists turn into them easily).
##

**Comment by mn200** [comment]
`Lexis.gen_variant` does this in a functional way.
