### ISSUE TITLE
HOL4 prints an empty unification error

### ISSUE THREAD

**Issue by HeikoBecker** [HOL-Theorem-Prover/HOL#751]
When I apply the following patch to CakeML ([https://github.com/CakeML/cakeml/commit/987b37051c029745a275d6f9d8bc8bf542777d20](https://github.com/CakeML/cakeml/commit/987b37051c029745a275d6f9d8bc8bf542777d20)) I get an empty unification error.

Patch:

    diff --git a/characteristic/cfAppScript.sml b/characteristic/cfAppScript.sml
    index c41b987e7..e8312e572 100644
    --- a/characteristic/cfAppScript.sml
    +++ b/characteristic/cfAppScript.sml
    @@ -701,7 +701,7 @@ Proof
       \\ first_x_assum drule
       \\ fs[evaluate_ck_def]
       \\ fs[POSTv_cond,SPLIT3_emp1,PULL_EXISTS]
    -  \\ disch_then( qspec_then`ARB with
    +  \\ disch_then( qspec_then`empty_state with
             <| refs := refs; |>` mp_tac)
       \\ rw [] \\ instantiate
       \\ rename1 `SPLIT (st2heap p st1) _`

I am running HOL4 on commit `4f67f38e1314dcb1488b3925ddbbc4bbd80795bf`. Running `Holmake` in the CakeML directory `characteristic` prints `unification error: ??` when compiling `cfAppScript.sml`.

Running interactively prints

    Type inference failure: the term
    
    <term>
    
    between line 704, character 23 and line 705, character 26
    
    which has type
    
    <hol_type>
    
    can not be constrained to be of type
    
    <hol_type>
    
    unification failure message: ???
    
    Exception raised at Thm_cont.DISCH_THEN:
    
    Exception-
       HOL_ERR
         {message = "", origin_function = "DISCH_THEN", origin_structure =
          "Thm_cont"} raised

**Comment by mn200** [comment]
I think this is the same issue as #754 and so will close this.  When I fix #754, if you think you are still seeing the same problem, please reopen this issue and let me know.
