### ISSUE TITLE
New theory declaration syntax that hides output from open

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#757]
This is a request for new syntactic sugar along the lines of:
```
Theory foo:
  open wordsTheory;
  open wordsSyntax;
Parsing: arithmetic, list
Begin
```
that expands to something like the following:
```
val _ = HOL_Interactive.set_quietdec true;
open HolKernel Parse boolLib bossLib;
  open wordsTheory;
  open wordsSyntax;
val _ = new_theory "foo";
val _ = Parse.set_grammar_ancestry ["arithmetic", "list"];
val _ = HOL_Interactive.set_quietdec false;
```
My motivation for this request is that I’ve seen so many newcomers to HOL sit waiting for several minutes while `open` spews out a never-ending stream of all available variable bindings.

To match the `Begin`, one might have `EndTheory` at the end of the file. `EndTheory` would expand to `val _ = export_theory();`

**Comment by AndreasLoow** [comment]
If the aim is to not confuse beginners, then maybe `HOL_Interactive.set_quietdec false` should be invoked in an exception handler instead. (M-h C-r (not M-h M-r) in the HOL Emacs mode has the same problem as the suggested expanded code, which is why I thought of this.)

**Comment by mn200** [comment]
I think the emacs mode now handles all `open`s better than before.  I will close this and perhaps open a fresh issue to record thinking about nice syntax for theory headers, independently of how emacs handles `open` declarations.
