### ISSUE TITLE
Term equality error in HOL-k13

### ISSUE THREAD

**Issue by ahmedwaqar** [HOL-Theorem-Prover/HOL#759]
The term equality condition checking works fine upto HOL-k12

fun foo t =
 if t = ``($+):real->real->real`` then "b" else "c";

 > val foo = fn: term -> string

However, raising the following error in HOL-k13

 > poly: : error: Type error in function application.
   Function: = : ''a * ''a -> bool
   Argument: (t, (Parse.Term [QUOTE " (*#loc 18 11*)($+):real->real->real"]))
      : ''a * term

Any suggestions to make it working?

**Comment by mn200** [comment]
This is an intended change, as *per* the [release notes](https://hol-theorem-prover.org/kananaskis-13.release.html#incompatibilities).  You should use `~~` or `aconv`.

**Comment by ahmedwaqar** [comment]
Thanks!
