### ISSUE TITLE
DEP_REWRITE_TAC hangs with unbreakable loop

### ISSUE THREAD

**Issue by tanyongkiam** [HOL-Theorem-Prover/HOL#763]
Given:

```
 > LUPDATE_commutes;
val it =
   ⊢ ∀m n e1 e2 l.
         m ≠ n ⇒
         LUPDATE e1 m (LUPDATE e2 n l) = LUPDATE e2 n (LUPDATE e1 m l): thm

```
running this:

```

Theorem foo:
  (LUPDATE x n (LUPDATE y m ls)) = []
Proof
  dep_rewrite.DEP_REWRITE_TAC[LUPDATE_commutes]

```
causes an unbreakable/unrecoverable loop when working interactively (HOL4 has to be restarted)

**Comment by tanyongkiam** [comment]
From @konrad-slind on Slack:

It could be that, somewhere in the implementation of DEP_REWRITE_TAC, there is an occurrence of handle _ => .... If interrupts are mapped to exceptions, then this could lead to unbreakable loops in rewriting.  It's better style to handle HOL_ERR and other known exceptions explicitly.

Lots of handle _ => .... The ones I'd worry about are ORELSE_DEP and its use in REPEAT_DEP

**Comment by konrad-slind** [comment]
Modified the implementation of ORELSE_DEP to use "handle HOL_ERR _ => ..." instead of the wildcard pattern.
