### ISSUE TITLE
Change the precedence of $

### ISSUE THREAD

**Issue by AndreasLoow** [HOL-Theorem-Prover/HOL#780]
I think the precedence of $ should be changed such that definitions such as the following would work:

```
Definition foo_def:
 foo x = bar $ baz x
End
```

**Comment by mn200** [comment]
Totally agree.  Equality is a level 450 infix; $ needs to be tighter (a higher number) for the above to work.   500 is used for + (for example), so if $ is weaker than that, then 
```
   f x = bar $ x + 4
```
would apply `bar` to `x + 4`, which is probably what we want.  It also needs to be right-associative, so I'd maybe put it at 460, alongside a bunch of record-syntax related infixes (`with`, `:=`).
