### ISSUE TITLE
heapname and buildheap aren't found

### ISSUE THREAD

**Issue by yurivict** [HOL-Theorem-Prover/HOL#783]
I've built hol and installed it into /usr/local/share/hol.

But ```hol``` fails to find these executables because they don't exist:
```
$ HOLDIR=/usr/local/share/hol hol 
/usr/local/bin/hol: /wrkdirs/usr/ports/math/hol/work/HOL-kananaskis-13/bin/heapname: not found
/usr/local/bin/hol: /wrkdirs/usr/ports/math/hol/work/HOL-kananaskis-13/bin/buildheap: not found
```

Please note that ```hol``` also ignores the environment variable ```HOLDIR=/usr/local/share/hol``` and is still looking in directories it was built in.

How to make it not remember the directory where it builds and default ```HOLDIR``` to the directory it will be installed in?

Why ```heapname``` and ```buildheap``` aren't built?

**Comment by mn200** [comment]
HOL doesn't cope with being moved.  It doesn't use the environment variable `HOLDIR`. 

If you want it in `/usr/local` I'm afraid that's where you should build it.

**Comment by yurivict** [comment]
This means that it can't be packaged, which in turn means that many users can't easily install it. Only the most determined would build it manually.

**Comment by mn200** [comment]
I agree that this is unfortunate.  There is some work towards making it relocatable, but it's incomplete.

**Comment by binghe** [comment]
There should be some ways (e.g. `chroot`) to make HOL think it’s building in `/usr/local`, then after unpacking it’s really there and work normally.

**Comment by yurivict** [comment]
When the package is built it alwaysHOLDIR builds as a user in a specific temporary directory.

You should make the process to initialize HOLDIR from the environment variable when it is set in the beginning of the run.
