### ISSUE TITLE
unfortunate interaction between special preprocessing forms and existing SML structures

### ISSUE THREAD

**Issue by konrad-slind** [HOL-Theorem-Prover/HOL#785]
I think this relates to how hol-mode deals with regions dropped into HOL. But it might also touch the preprocessor.  Example:

   let open Datatype in () end

If I drop this into the interactive top-level from emacs, using standard emacs copy-paste, this is fine. But if I use the usual hol-mode M-h M-r (send-region-to-hol) it is not fine.

**Comment by mn200** [comment]
The issue has to do with the "keyword" `Datatype`.   Other module names in that position don't lead to the problem.  I just have to get the internal emacs search to properly honour the case of its strings.
