### ISSUE TITLE
Emacs mode handling of quoted things

### ISSUE THREAD

**Issue by AndreasLoow** [HOL-Theorem-Prover/HOL#811]
This is a note (and a suggestion) about how the new and improved Emacs mode handles input of quoted things: If I type \` + r I get ‘r’, but if I type \` + i I get ì (suggestion: I think ‘i’ would have been more useful here). Similarly, it seems that pasting using \` + C-y results in ‘’ rather than ‘\<whatever was in the paste buffer\>’.

**Comment by mn200** [comment]
Neither of those behaviours are apparent in my emacs.   Please investigate further if you think there's something that the emacs mode can do to help your configuration.

**Comment by AndreasLoow** [comment]
Sorry for this, apparently the behaviour depends on the keyboard layout used and something called "dead keys". I.e. OS things.
