### ISSUE TITLE
ex/mc/graph: RISC-V graph decompiler doesn't handle `jr` instruction

### ISSUE THREAD

**Issue by mbrcknl** [HOL-Theorem-Prover/HOL#836]
This issue concerns the RISC-V version of the binary-to-graph decompiler in [examples/machine-code/graph](https://github.com/HOL-Theorem-Prover/HOL/tree/develop/examples/machine-code/graph).

When compiling C `switch` statements on `enum` types, the RISC-V `gcc` compiler typically uses the `jr` (jump register) instruction, which is short-hand for `jalr` using the zero register as the link register.

For example, in the seL4 kernel, we have this function:
```
word_t getObjectSize(word_t t, word_t userObjSize)
{
    if (t >= seL4_NonArchObjectTypeCount) {
        return Arch_getObjectSize(t);
    } else {
        switch (t) {
        case seL4_TCBObject:
            return 10;
        case seL4_EndpointObject:
            return 4;
        case seL4_NotificationObject:
            return 5;
        case seL4_CapTableObject:
            return 5 + userObjSize;
        case seL4_UntypedObject:
            return userObjSize;
        default:
            halt();
            return 0;
        }
    }
}
```
which compiles to:
```
ffffffff8401195e <getObjectSize>:
ffffffff8401195e:       1141                    addi    sp,sp,-16
ffffffff84011960:       e406                    sd      ra,8(sp)
ffffffff84011962:       4791                    li      a5,4
ffffffff84011964:       00a7ef63                bltu    a5,a0,ffffffff84011982 <getObjectSize+0x24>
ffffffff84011968:       4791                    li      a5,4
ffffffff8401196a:       02a7e863                bltu    a5,a0,ffffffff8401199a <getObjectSize+0x3c>
ffffffff8401196e:       050a                    slli    a0,a0,0x2
ffffffff84011970:       00005717                auipc   a4,0x5
ffffffff84011974:       7dc70713                addi    a4,a4,2012 # ffffffff8401714c <ksDomScheduleLength+0x9c>
ffffffff84011978:       00e507b3                add     a5,a0,a4
ffffffff8401197c:       439c                    lw      a5,0(a5)
ffffffff8401197e:       97ba                    add     a5,a5,a4
ffffffff84011980:       8782                    jr      a5
ffffffff84011982:       ddcff0ef                jal     ra,ffffffff84010f5e <Arch_getObjectSize>
ffffffff84011986:       60a2                    ld      ra,8(sp)
ffffffff84011988:       0141                    addi    sp,sp,16
ffffffff8401198a:       8082                    ret
ffffffff8401198c:       4511                    li      a0,4
ffffffff8401198e:       bfe5                    j       ffffffff84011986 <getObjectSize+0x28>
ffffffff84011990:       00558513                addi    a0,a1,5 # fffffffff8000005 <ki_end+0x73fd2005>
ffffffff84011994:       bfcd                    j       ffffffff84011986 <getObjectSize+0x28>
ffffffff84011996:       852e                    mv      a0,a1
ffffffff84011998:       b7fd                    j       ffffffff84011986 <getObjectSize+0x28>
ffffffff8401199a:       9b1fe0ef                jal     ra,ffffffff8401034a <halt>
ffffffff8401199e:       4529                    li      a0,10
ffffffff840119a0:       b7dd                    j       ffffffff84011986 <getObjectSize+0x28>
ffffffff840119a2:       4515                    li      a0,5
ffffffff840119a4:       b7cd                    j       ffffffff84011986 <getObjectSize+0x28>
```
The instructions between `ffffffff8401196e` and `ffffffff8401197e` load a jump address into `a5`, and the `jr` instruction jumps to that address. These instructions make use of some extra jump vectors found elsewhere in the read-only data of the binary:
```
ffffffff8401714c:       a84a                    fsd     fs2,16(sp)
ffffffff8401714e:       ffff                    0xffff
ffffffff84017150:       a852                    fsd     fs4,16(sp)
ffffffff84017152:       ffff                    0xffff
ffffffff84017154:       a840                    fsd     fs0,144(s0)
ffffffff84017156:       ffff                    0xffff
ffffffff84017158:       a856                    fsd     fs5,16(sp)
ffffffff8401715a:       ffff                    0xffff
ffffffff8401715c:       a844                    fsd     fs1,144(s0)
ffffffff8401715e:       ffff                    0xffff
```
The result is that we end up at one of the instructions past the `ret`, which otherwise appear to be unreachable in `getObjectSize`.

However, the decompiler output tells a different story:
```
0x84011980 Cond 0xD Err Op And Bool 2 Op Equals Bool 2 Op BWAnd Word 64 2 Num 18446744073709551614 Word 64 Var r15 Word 64 Var ret Word 64 Op Equals Bool 2 Op BWAnd Word 64 2 Op BWAnd Word 64 2 Num 18446744073709551614 Word 64 Var r15 Word 64 Num 1 Word 64 Num 0 Word 64
0xD Basic Ret 0 
```
Essentially, the graph code asserts that `a5` contains the return address (which is not true), and then returns from `getObjectSize` to its caller. Clearly, the assertion would be necessary to get through the decompiler's refinement proof, but since the assertion is false, it makes it very difficult for any higher-level refinement to work.

I can see how this happened: The `ret` instruction is just short-hand for `jr` using the conventional return-address register. Since `ret` instructions are far more common than `jr` instructions, the examples used in the decompiler development were all about returning to the caller.

Fixing this looks nontrivial. Tracing the jump vectors requires data from outside the function, which seems to go against the grain of the current decompiler design. It would also need some dataflow analysis to figure out the range of possible jump vectors.

I shall attach the complete files containing the above excerpts.

**Comment by mbrcknl** [comment]
[target.zip](https://github.com/HOL-Theorem-Prover/HOL/files/4900661/target.zip)

**Comment by mbrcknl** [comment]
I just realised that in the ZIP file attached above, we have manually adjusted the decompiler output, so you might see some differences if you rerun the decompiler with the given `kernel.elf.txt` and `kernel.sigs`, in particular in the nodes corresponding to `auipc` and `sfence.vma` instructions. For the reasons behind these adjustments, see these two issues:

https://github.com/HOL-Theorem-Prover/HOL/issues/839
https://github.com/HOL-Theorem-Prover/HOL/issues/840

**Comment by mbrcknl** [comment]
We found a way to avoid the issue with the `jr` instruction, although it's not a particularly pleasant one: The GCC option `-fno-jump-tables` compiles `switch` statements using ordinary branch instructions, avoiding `jr` altogether. Obviously, this will slow down binary execution.

**Comment by myreen** [comment]
@mbrcknl reports that commits 21b7f4a1f740bb1e6c9202770f16c66f174885ef, a954d906021b3d5ec2b9dee8724abeca0d7fbd1c, 13783a902ca4e4ad0ff8374fffd55bb84968588a fix this issue.
