### ISSUE TITLE
ex/mc/graph: RISC-V graph decompiler misinterprets non-tail self-recursive call as a tail call

### ISSUE THREAD

**Issue by mbrcknl** [HOL-Theorem-Prover/HOL#837]
This issue concerns the RISC-V version of the binary-to-graph decompiler in [examples/machine-code/graph](https://github.com/HOL-Theorem-Prover/HOL/tree/develop/examples/machine-code/graph).

In the RISC-V seL4 kernel, we have a trio of mutually-recursive functions. With inlining, the compiler reduces this trio to a single self-recursive function. The binary for this function is rather long, but the crucial bits look like this:
```
ffffffff84012f74 <cteDelete>:
ffffffff84012f74:       7135                    addi    sp,sp,-160
...
ffffffff840130d0:       ea5ff0ef                jal     ra,ffffffff84012f74 <cteDelete>
...
```

The decompiler output includes this:
```
0x84012F74 Basic 0x84012F76 1 r2 Word 64 Op Plus Word 64 2 Var r2 Word 64 Num 18446744073709551456 Word 64
...
0x840130D0 Basic 0x84012F74 1 r1 Word 64 Num 2214670548 Word 64
```

While the graph code indeed performs the jump and the link, it fails to recognise that this isn't a tail call. Indeed, you can see that the instruction that we jump to allocates another stack frame. The result is that in the graph semantics, the return from a recursive call will effectively return from the outermost call to `cteDelete`. In contrast, the binary continues to execute instructions beyond the `jal` instruction. Therefore, I believe this particular `jal` instruction should be rendered as a `Call` node.

I am attaching source files from which the above excerpts were taken:
[target.zip](https://github.com/HOL-Theorem-Prover/HOL/files/4900726/target.zip)

Side note: I am aware that in @talsewell's original work on binary verification for the ARM kernel, inlining was disabled for this trio of functions. IIUC, that was primarily to support stack usage analysis. We have a stack bounds analysis that works with the inlining, so we're still evaluating whether we need to disable it for other reasons.

**Comment by myreen** [comment]
I'm hoping commit 3014c2bcd563eeb9441af677b369fe2f113229bb fixes this issue.

**Comment by mn200** [comment]
I will close because I haven't heard otherwise.   Feel free to re-open if an issue remains.
