### ISSUE TITLE
Real simplification produces strange terms

### ISSUE THREAD

**Issue by HeikoBecker** [HOL-Theorem-Prover/HOL#838]
With the latest master, on a subgoal similar to `1/x <= 1/y` where `x` and `y` are arbitrarily complex, running `simp[GSYM REAL_INV_1OVER]` turns the goal into `NZ x <= ...` which cannot be further simplified/ makes applying theorems like `REAL_INV_LE_ANTIMON_IMPR` impossible.

Running `val _ = temp_delsimps ["RMUL_LEQNORM"]` seems to fix the problem

MWE:

    open bossLib realLib RealArith realTheory;
    
    Theorem err_prop_inversion_pos:
      !(nF:real) (nR:real) (err:real) (elo:real) (ehi:real).
          0 < elo - err  /\ 0 < elo /\
          abs (nR - nF) <= err /\
          elo <= nR /\
          nR <= ehi /\
          elo - err <= nF /\
          nF <= ehi + err /\
          0 <= err ==>
          abs (inv nR - inv nF) <= err * inv ((elo - err) * (elo - err))
    Proof
      rpt strip_tac
      \\ `! (x:real). ((abs x = x) /\ 0 < x) \/ ((abs x = - x) /\ x <= 0)`
         by (REAL_ASM_ARITH_TAC)
      \\ qpat_x_assum `!x. (A /\ B) \/ C` (qspecl_then [`nR - nF` ] assume_tac)
      \\ fs[]
      >- (
        `nF <= nR` by REAL_ASM_ARITH_TAC
        \\ `0 < nF` by REAL_ASM_ARITH_TAC
        \\ `0 < nR` by REAL_ASM_ARITH_TAC
        \\ `inv nR <= inv nF` by fs [REAL_INV_LE_ANTIMONO]
        \\ `inv nR - inv nF <= 0` by REAL_ASM_ARITH_TAC
        \\ `0 <= - (inv nR - inv nF) ` by REAL_ASM_ARITH_TAC
        \\ `abs (- (inv nR - inv nF)) = - (inv nR - inv nF)` by fs [ABS_REFL]
        \\ `abs (inv nR - inv nF) = - (inv nR - inv nF)` by metis_tac[ABS_NEG]
        \\ simp[REAL_INV_1OVER, real_sub, REAL_NEG_ADD]
        \\ rpt (qpat_x_assum `abs v = v'` kall_tac)
        \\ `- (1 / nR) = 1 / - nR`
           by (fs [real_div] \\ irule REAL_NEG_INV \\ REAL_ASM_ARITH_TAC)
        \\ simp[]
        \\ irule REAL_LE_TRANS
        \\ qexists_tac `1 / -nR + 1 / (nR - err)` \\ conj_tac
        >- (match_mp_tac REAL_LE_LADD_IMP
            \\ simp[GSYM REAL_INV_1OVER]
    ...

Running the above proof without the `temp_delsimps` produces a `NZ` subgoal, whereas removing the simpset does not.

**Comment by binghe** [comment]
I think this issue can be resolved by adding the following lemma into `realTheory`:

```
Theorem nonzerop_EQ1_I'[simp]:
  0 < r ==> (nonzerop r = 1)
Proof
  rw[nonzerop_def]
QED
```
in addition to the existing simplification rule `nonzerop_EQ1_I` (`r <> 0 ==> (nonzerop r = 1)`). Heiko's previous goal now becomes:

```
        1 <= nF * realinv (nR - err)
   ------------------------------------
    0.  0 < elo - err
    1.  0 < elo
    2.  abs (nR - nF) <= err
    3.  elo <= nR
    4.  nR <= ehi
    5.  elo - err <= nF
    6.  nF <= ehi + err
    7.  0 <= err
    8.  0 <= nR - nF
    9.  0 < nR - nF
   10.  nF <= nR
   11.  0 < nF
   12.  0 < nR
   13.  realinv nR <= realinv nF
   14.  realinv nR - realinv nF <= 0
   15.  0 <= -(realinv nR - realinv nF)
   16.  -(1 / nR) = 1 / -nR
   
   : proof
```
after the tactic `simp[GSYM REAL_INV_1OVER]` which I think is in the right direction.

Besides, it may helps to also have a dual version:

```
Theorem nonzerop_EQ1_I''[simp]:
  r < 0 ==> (nonzerop r = 1)
Proof
  rw[nonzerop_def]
QED
```
to handle the case where `r < 0` is in the assumption list.

Regards,

Chun Tian

**Comment by HeikoBecker** [comment]
@binghe Thanks for looking into this. Are your changes only on a forked HOL version or did you already commit them to develop/master?

**Comment by mn200** [comment]
If this is all that's needed, I'd rather suggest that you fold the arithmetic d.p. into your simpset so that `0 < r` in the assumption list automatically proves `r <> 0` in the conditional rewrite.  You can do this with something like
```
val _ = augment_srw_ss [realSimps.REAL_ARITH_ss];
```

**Comment by HeikoBecker** [comment]
Thanks for the suggestion @mn200 . I will test it and report back how it went.

**Comment by HeikoBecker** [comment]
If I add the theorem suggested by @binghe, the proof succeeds after some minor reordering.
Extending the simpset with `realSimps.REAL_ARITH_ss` throws a strange exception:

    Exception raised at Tactical.VALID:
    Invalid tactic: theorem has wrong conclusion ∀nF nR err elo ehi.
        0 < elo − err ∧ 0 < elo ∧ abs (nR − nF) ≤ err ∧ elo ≤ nR ∧ nR ≤ ehi ∧
        elo − err ≤ nF ∧ nF ≤ ehi + err ∧ 0 ≤ err ⇒
        abs (nR'⁻¹ − nF'⁻¹) ≤ err * ((elo − err) * (elo − err))⁻¹

I am growing suspicious that the theorem may just be too old/brittle by now and should be redone with the new simplification sets...

**Comment by mn200** [comment]
Things shouldn't be creating invalid tactics though.  Can you reproduce that too?  It sounds like a separate bug.

**Comment by HeikoBecker** [comment]
Ok, then let me close this issue and open another one for the exception.
