### ISSUE TITLE
What is the difference between HOL (e.g. HOL4) and Isabelle?

### ISSUE THREAD

**Issue by brando90** [HOL-Theorem-Prover/HOL#847]
How is HOL (e.g. HOL4) different from Isabelle? Why are there so many theorem provers? even HOL light exists.

Thanks!

**Comment by AndreasLoow** [comment]
[From LCF to HOL: A short history](https://www.cl.cam.ac.uk/archive/mjcg/papers/HolHistory.html) provides some short information on different versions and implementations of HOL. For Isabelle specifically you have e.g. [From LCF to Isabelle/HOL](https://doi.org/10.1007/s00165-019-00492-1).

**Comment by mn200** [comment]
This is not an issue, *per se*.  Please use mailing lists rather than the issue tracker.
