### ISSUE TITLE
Polyscripter reads ~/.hol-config.sml when building manual PDFs

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#851]
Hi,

when I try to build HOL manuals, the `polyscripter` command reads my local `~/.hol-config.sml` file which may contain custom settings like `Globals.linewidth` which may change the final typesetting results.  As a workaround, I have to comment all harmful settings in my `~/.hol-config.sml` to make sure that I see the same manual PDFs as those built by others.

Is it possible to let `polyscripter` ignore `~/.hol-config.sml`?

Regards,

Chun Tian

**Comment by mn200** [comment]
Good point.   Note that I think the options from your config file may be read at compile time, not runtime.

**Comment by binghe** [comment]
Thanks.
