### ISSUE TITLE
Cannot checkout on Windows

### ISSUE THREAD

**Issue by ice1000** [HOL-Theorem-Prover/HOL#868]
Hi, I was pulling this repo on Windows, and this file: https://github.com/HOL-Theorem-Prover/HOL/blob/develop/help/Docfiles/Type.--%3E.doc

is causing Windows unhappy with the file name:

```
~/git-repos/ProofAssistants/HOL (master) λ> git reset origin/master --hard
error: invalid path 'help/Docfiles/Type.-->.doc'
fatal: Could not reset index file to revision 'origin/master'.
```

Can we rename it to `Type.arrow.doc` or something?

**Comment by mn200** [comment]
Thanks for this report.  I will fix before making our next "official release".
