### ISSUE TITLE
`¬` parsed as numeric negation

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#871]
Theories that overload numeric operators other than `numTheory` make `¬` parse as numeric negation in some contexts.

Reproduction: With only the default heap loaded `x + ¬y` gives type error when parsing. This is the expected behavior. With `integerTheory`,  `ratTheory` or `realTheory` loaded it parses as `x + -y`.

**Comment by mn200** [comment]
Thanks for the report

**Comment by mn200** [comment]
I can't reproduce this for integerTheory:
```
> load "integerTheory";
val it = (): unit
> ``p + ¬q``;
Exception-
   HOL_ERR
     {message =
      "at line 9, character 2:\nCouldn't infer type for overloaded name +",
      origin_function = "type-analysis", origin_structure = "Preterm"} raised
```

Nor can I see it for any of the numeric types, except for the words, where the negation symbol is interpreted as `word_1comp`.  

Can you describe how to reproduce the behaviour you saw?

**Comment by marioxcc** [comment]
I tested it in kananaskis-13 at the time of report.

```
---------------------------------------------------------------------
       HOL-4 [Kananaskis 13 (expknl, built Fri Jul 10 14:46:58 2020)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------
> load "integerTheory";
val it = (): unit
> “x + ¬y”;
val it = “x + -y”: term
```

Now I tested it in a more recent development build and it does not reproduce.

**Comment by mn200** [comment]
Thanks for checking.
