### ISSUE TITLE
Consider whether `Makefile` for manual requires HOL binaries in `PATH` 

### ISSUE THREAD

**Issue by marioxcc** [HOL-Theorem-Prover/HOL#872]
Running `make` fails from the directory `Manual` if HOL4’s `bin` is not in `PATH`. Most HOL components work without a need to change `PATH`. If it is intended that building the LaTeX documentation is the exception it would be good to state that it in the documentation; e.g.: the `INSTALL` file. Better is to change it to know the path to the HOL binaries needed, like the Emacs mode. 

Tested in 6c0c2409ecdbd7195911f674a77bfdd39c83816e.

**Comment by mn200** [comment]
That `Makefile` should absolutely be turned into a `Holmakefile` with `INCLUDES` specifications to control the building of the sub-directories.  I don’t remember when I last used it, though I can see from the log that I created it (in 1999).
