### ISSUE TITLE
Adding a certain parse rule breaks parsing of seemingly unrelated strings

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#885]
```
open HolKernel boolLib bossLib Parse

(* parsing succeeds *)
val tm = ``n < LENGTH ls ==> n >= 0``

(* note: this parsing rule is copied from examples/category/categoryScript.sml *)

val HS = HardSpace 1;

val _ = add_rule {
  term_name = "iso_pair_between_objs_syntax",
  fixity = Infix(NONASSOC,451),
  pp_elements = [HS, TOK "<", TM, TOK "\226\137\131", TM, TOK ">", HS, TM, HS, TOK "-:"],
  paren_style = OnlyIfNecessary,
  block_style = (AroundEachPhrase, (PP.INCONSISTENT, 0))
};

(* parsing of the same string now fails *)
val tm = ``n < LENGTH ls ==> n >= 0``
```

**Comment by mn200** [comment]
I think this is working as intended, I'm afraid.  In particular, when you have adjacent tokens in a rule such as yours, every other token must be made less-than the first and greater than the second.  So, in the given phrase, `==>` is seen as the first token in a new phrase (the one expected to fall between the `<` and `>`) which starts to the right of the `<`. 

For a different look at the same situation, imagine trying to have `[` as a list-delimiter and an infix.  That's effectively what your rule is trying to do with `<`.  Then, try parsing 
```
    x [ foo ==> bar ...
```
The treatment of the `[` as a list delimiter forces the `foo ==> bar` to be grouped as a phrase.

I think you'll just have to use Unicode-ish angle brackets: 〈 and 〉, say.
