### ISSUE TITLE
Remaining issues on FreeBSD (minisat, zc2hs)

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#899]
For the records, after 9bceeb0943cf71103527d68d69a659cb3c78c74e (#898) I've seen the following remaining issues when building HOL4:

```
Building directory src/HolSat/sat_solvers/minisat [09 Mar, 08:56:40]
make: "/usr/home/binghe/ML/HOL/src/HolSat/sat_solvers/minisat/Makefile" line 88: Could not find depend.mak
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/binghe/ML/HOL/src/HolSat/sat_solvers/minisat
*** Build failed in directory /usr/home/binghe/ML/HOL/src/HolSat/sat_solvers/minisat (make failed).

MiniSat has NOT been built!! (continuing anyway).

Uploading files to /usr/home/binghe/ML/HOL/sigobj
Building directory src/HolSat/sat_solvers/zc2hs [09 Mar, 08:56:40]
ln -fs ../minisat/Proof.o
ln -fs ../minisat/File.o
ln -fs ../minisat/File.h
ln -fs ../minisat/Proof.h
ln -fs ../minisat/Global.h
ln -fs ../minisat/Sort.h
ln -fs ../minisat/SolverTypes.h
g++ -O3 Proof.o File.o zc2hs.cpp -o zc2hs
make: exec(g++) failed (No such file or directory)
*** Error code 1

Stop.
make: stopped in /usr/home/binghe/ML/HOL/src/HolSat/sat_solvers/zc2hs
*** Build failed in directory /usr/home/binghe/ML/HOL/src/HolSat/sat_solvers/zc2hs (make failed).

zc2hs has NOT been built!! (continuing anyway).

Uploading files to /usr/home/binghe/ML/HOL/sigobj
```

**Comment by mn200** [comment]
Does FreeBSD provide a `c++` executable?  If this is sufficiently common, I'd happily adjust the Makefile.  

I will also make the Makefile look at a plausible environment variable so the user can specify things that way.

**Comment by mn200** [comment]
Ubuntu and MacOS provide `c++` (by observation). [FreeBSD documentation](https://docs.freebsd.org/en_US.ISO8859-1/books/developers-handbook/tools-compiling.html) claims it does as well so I'm hopeful a survey with sample size three solves all our problems here.

**Comment by binghe** [comment]
Thanks!

**Comment by mn200** [comment]
I did think of the standard `CXX` sort of approach but decided against it because I wanted to give the user the flexibility of not "contaminating" their standard environment (if they set an environment variable to handle minisat, they have also then suddenly set something that will affect all other compilations). 

But I'll certainly change `MINISAT_CPP` to `MINISAT_CXX`.
