### ISSUE TITLE
The function list_mk_forall fails unexpectedly

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#902]
The following code fails unexpectedly.

val t = \`\`(Q :α -> bool) (a :α)\`\`;
val t' = list_mk_forall (free_vars_lr t,t);

Repetitive applications of mk_forall or reversing the list of variables produces a result.

**Comment by mn200** [comment]
Great find!

**Comment by mn200** [comment]
Closed by a03eacf5edb.
