### ISSUE TITLE
vimhol not working with PolyML 5.8.2

### ISSUE THREAD

**Issue by acjf3** [HOL-Theorem-Prover/HOL#917]
When HOL is built with PolyML 5.8.2 it fails to work with vimhol. We get

tail: ‘/dev/null’: Permission denied
tail: invalid option -- 'f'
Try 'tail --help' for more information.
Vimhol's tail gave eof

and then it loops with the same errors.

The problem seems to be caused by PolyML changing its implementation of Unix.execute. For example, this means that

Unix.execute("/usr/bin/env",["tail", "/dev/null"])

now fails. Things work if it is changed to

Unix.execute("/usr/bin/tail",["/dev/null"])

but that is not ideal. Not sure if there is a better workaround, or if this is simply a bug in PolyML itself.

**Comment by acjf3** [comment]
Correction, changing things to

Unix.execute("/usr/bin/tail", ["-f", fifoPath]

still doesn't help. HOL is unresponsive after this change.

**Comment by mn200** [comment]
It sounds like this is a Poly/ML problem; particularly if it's just Poly/ML changing that induces the change in behaviour.

No?

**Comment by acjf3** [comment]
Yes, it's looking likely that this is a PolyML issue which needs reporting. I don't know enough about the expected behaviour of Unix.execute to know whether it "shouldn't have worked before", but I doubt that's the case.

**Comment by acjf3** [comment]
I've reported the issue. Can close #917 if it becomes clear that no changes are needed to vimhol.src.

**Comment by acjf3** [comment]
This was a PolyML issue that has now been resolved: https://github.com/polyml/polyml/issues/151
