### ISSUE TITLE
Not able builld HOL from source using poly on linux subsystem with ubuntu distribution on windows 64-bit

### ISSUE THREAD

**Issue by shamEiNew** [HOL-Theorem-Prover/HOL#922]
I added the file but still getting the error.

```
`smoothcriminal@Neo:~/HOL$ poly < tools/smart-configure.sml
Poly/ML 5.7.1 Release

HOL smart configuration.

Determining configuration parameters: holdir OS poly GNUMAKE polymllibdir

Looked in poly's sister lib directory /usr/lib
and couldn't find libpolymain.a
Please write file tools-poly/poly-includes.ML to specify it.
This file should include a line of the form

  val polymllibdir = "path-to-dir-containing-libpolymain.a";'
```

**Comment by binghe** [comment]
You must be using Linux, `libpolyml.a` and `libpolyml.so.*` are in "/usr/lib/x86_64-linux-gnu" (I assume you're using a 64-bit Linux on PC).

Try first to set the correct path with `val polymllibdir`, and if it still doesn't work, you may need to use "ln -s" to manually link `libpolyml.a` and `libpolyml.so.*` back to "/usr/lib"...

**Comment by jeremydaw** [comment]
I think this info might be specific to Ubuntu.

On Fedora I get

***@***.*** ~]$ ldd /usr/bin/poly
	linux-vdso.so.1 (0x00007ffd8fb4a000)
	libpolyml.so.11 => /lib64/libpolyml.so.11 (0x00007f8111e0b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8111c3c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8111c1b000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f8111c10000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007f8111b6e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8111b67000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f8111946000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8111802000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f81117e7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8111e9a000)

On Ubuntu I get

***@***.*** ~]$ which poly
/home/users/jeremy/polyml-5.7/bin/poly
***@***.*** ~]$ ldd /home/users/jeremy/polyml-5.7/bin/poly
	linux-vdso.so.1 (0x00007ffc6cdcd000)
	libpolyml.so.9 => /home/users/jeremy/polyml-5.7/lib/libpolyml.so.9 
(0x00007f1c1475b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1c1436a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 
(0x00007f1c1414b000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f1c13eca000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1c13cc6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 
(0x00007f1c1393d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1c1359f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1c13387000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1c149e6000)

Cheers,

Jeremy

**Comment by shamEiNew** [comment]
I failed to mention I was using linux subsytem with ubuntu distribution on windows.
But the issue is resolved. There was some mistake in file path and further I had to manually link `sudo ln -s ` as suggested by @binghe . 

Thanks,
Sham
