### ISSUE TITLE
floating-point sqrt is undefined for negative zero

### ISSUE THREAD

**Issue by HeikoBecker** [HOL-Theorem-Prover/HOL#926]
The IEEE-754 standard defines that the `sqrt` instruction computes the mathematical square root for positive operands, and it further states that `squareRoot(-0) = -0`.
However, `binary_ieeeScript` defines the square root operation only if the sign is `0w`, i.e. positive, and similarly the theorems in `lift_ieeeScript` prove error bounds only when sign  is `0w`.

**Comment by mn200** [comment]
I'd be happy to field a pull request that fixed this!
