### ISSUE TITLE
Cannot start "hol" session in "$(HOLDIR)/src/boss"

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#941]
Hi,

after HOL building finished, if I go to "$(HOLDIR)/src/boss" and start "hol", I got the following error saying **Structure (bossLib) has not been declared**, although bossLib is just in the same directory:
```
binghe@binghe-mac6:~/ML/HOL/src/boss$ hol

---------------------------------------------------------------------
       HOL-4 [Kananaskis 14 (stdknl, built Thu Jul 29 17:16:26 2021)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------
[Use-ing configuration file /Users/binghe/.hol-config.sml]
/Users/binghe/ML/HOL/tools-poly/prelude2.ML:4: error: Structure (bossLib) has not been declared Found near open bossLib
Uncaught exception: Fail "Static Errors"
```

The same issue doesn't happen in any other "$(HOLDIR)/src/" subfolder that I randomly tried.  Can you reproduce it?

Regards,

Chun Tian

**Comment by barakeel** [comment]
Yes got the same error.
---------------------------------------------------------------------
       HOL-4 [Kananaskis 14 (stdknl, built Mon Jul 26 16:44:29 2021)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------
/home/thibault/HOL/tools-poly/prelude2.ML:4: error: Structure (bossLib) has not been declared Found near open bossLib
Uncaught exception: Fail "Static Errors"

**Comment by mn200** [comment]
This is a known problem with the way the `Holmakefile` in that directory interacts with starting up a session.  You will get similar problems in directories that refer to the internal `numheap` (roughly, between building arithmetic and boss).

**Comment by binghe** [comment]
> This is a known problem with the way the `Holmakefile` in that directory interacts with starting up a session. You will get similar problems in directories that refer to the internal `numheap` (roughly, between building arithmetic and boss).

But sometimes I need to debug "src/boss/prove_base_assumsScript.sml", which needs to read two OpenTheory articles in current directory. If I don't start "hol" session in "src/boss" there seems no way to replay the scripts without manually changing the path of OT articles.   To workaround of this present issue (in another ongoing PR) I'm moving OT-files outside of "src/boss" to somewhere else.

**Comment by mn200** [comment]
In these circumstances, you can use `hol.bare` and suffer a slightly slower startup time.

**Comment by binghe** [comment]
> In these circumstances, you can use `hol.bare` and suffer a slightly slower startup time.

Thanks. But I ever tried `hol.bare` and it still refuse to load `bossLib`. Am I making mistakes when using `hol.bare` (never need it before)?

```
binghe@binghe-mac6:~/ML/HOL.otknl/src/boss$ ../../bin/hol.bare 

---------------------------------------------------------------------
       HOL-4 [Kananaskis 14 (otknl, built Wed Aug 18 02:30:31 2021)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------
[Use-ing configuration file /Users/binghe/.hol-config.sml]
> open bossLib;
poly: : error: Structure (bossLib) has not been declared Found near open bossLib
Static Errors
```

Chun

**Comment by mn200** [comment]
You can't `open` it from the outset because `bossLib` is not present in the heap that `hol.bare` uses.  You have to `load` it first:
```
$ hol.bare

---------------------------------------------------------------------
       HOL-4 [Kananaskis 14 (stdknl, built Fri Jul 23 10:20:24 2021)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------
> load "bossLib";
<<HOL message: inventing new type variable names: 'a, 'b>>
<<HOL message: inventing new type variable names: 'a, 'b>>
<<HOL message: inventing new type variable names: 'a>>
<<HOL message: inventing new type variable names: 'a>>
<<HOL message: inventing new type variable names: 'a>>
<<HOL message: inventing new type variable names: 'a, 'b>>
<<HOL message: inventing new type variable names: 'a, 'b>>
<<HOL message: inventing new type variable names: 'a>>
Meson search level: ................................................................................
Meson search level: ................................
Meson search level: 
Meson search level: 
Meson search level: ........
Meson search level: ............................................
val it = (): unit
```

I can’t say I’m very enthusiastic about all those messages; normally, of course, they occur only when the `hol.state` heap is built.  Nonetheless, it works.

**Comment by binghe** [comment]
Ah! I must have used "hol-mode.el" (in Emacs) too much, to have forgotten some basic things!   Thanks, and sorry for disturbing you on this matter!
