### ISSUE TITLE
Possible issues on Linux/ARM64

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#962]
Hi,

I don't have any ARM64 hardware, but I have an ARM64 version of Ubuntu 20.04 LTS driven by QEMU (you can easily get one with my scripts [1], also learnt from others) on Mac (it's a pity that currently I have no way to run macOS on Apple M1), mainly for building ARM64 releases of my other programs.

Since Poly/ML 5.9 is coming with native ARM64 support, I tried to build HOL in my ARM64 Linux box, and it strangely stops in `src/relation` with strange errors from `TAUT_PROVE` (?!):
```
Building directory src/relation [02 Nov, 09:27:47]
Holmake: Linking /home/binghe/ML/HOL/src/relation/relationScript.uo to produce theory-builder executable
error in quse /home/binghe/ML/HOL/src/refute/Canon.sml : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
error in load $(HOLDIR)/src/refute/Canon : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
error in load $(HOLDIR)/sigobj/refuteLib : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
error in load $(HOLDIR)/src/IndDef/InductiveDefinition : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
error in load $(HOLDIR)/sigobj/IndDefLib : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
error in load $(HOLDIR)/sigobj/BasicProvers : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
error in load /home/binghe/ML/HOL/src/relation/relationScript : HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
Uncaught exception: HOL_ERR {message = "", origin_function = "TAUT_PROVE", origin_structure = "tautLib"}
Holmake: Failed script build for /home/binghe/ML/HOL/src/relation/relationScript - exited with code 1
*** FATAL: Build failed in directory /home/binghe/ML/HOL/src/relation (exited with code 1)
```

It's a little surprised that other more advanced tactics tools all work well but a relatively simple one broke.  Can any other user with real ARM64 hardware also reproduce this issue?

Regards,

Chun Tian

[1] https://github.com/binghe/qemu-macos-x86-arm64

**Comment by mn200** [comment]
I’m afraid I don’t have any hardware to test this on, but note that `tautLib` is probably trying to call out to the `minisat` SAT-solver.  Perhaps there is a bug in the way this interaction is happening, or even in the compilation of `minisat`.

**Comment by mn200** [comment]
Incidentally, I suspect the PolyML mailing list may be the best place for this: David Matthews won’t see this otherwise.

**Comment by binghe** [comment]
> Incidentally, I suspect the PolyML mailing list may be the best place for this: David Matthews won’t see this otherwise.

Today I tried using PolyML 5.8 on Linux/ARM, and the building process stopped even earlier:
```
Building directory src/1 [03 Nov, 14:14:23]
Holmake: Linking /home/binghe/ML/HOL/src/1/ConseqConvScript.uo to produce theory-builder executable
/home/binghe/ML/HOL/src/parse/Parse.sml:641: warning: Matches are not exhaustive.
Found near
  fun
     ParenStyleToString Always = "Always" |
        ParenStyleToString OnlyIfNecessary = "OnlyIfNecessary" |
        ParenStyleToString ... = "ParoundName" |
        ParenStyleToString ... = ... |
        ...
error in quse /home/binghe/ML/HOL/src/bool/boolTheory.sml : TheoryReader "Exception raised: mlyAction"
error in load $(HOLDIR)/sigobj/boolTheory : TheoryReader "Exception raised: mlyAction"
error in load /home/binghe/ML/HOL/src/1/ConseqConvScript : TheoryReader "Exception raised: mlyAction"
Uncaught exception: TheoryReader "Exception raised: mlyAction"
Holmake: Failed script build for /home/binghe/ML/HOL/src/1/ConseqConvScript - exited with code 1
*** FATAL: Build failed in directory /home/binghe/ML/HOL/src/1 (exited with code 1)
```

Meanwhile I saw another HOL4 user (Oskar Abrahamsson) is reporting issues on building HOL4 with PolyML 5.9 on Apple M1 Mac, and David Matthews has already fixed several related issues.  I'm watching the process and I plan to wait until Oskar managed to fully build HOL4 on his M1 Mac.

**Comment by oskarabrahamsson** [comment]
Some updates on this problem: It does not occur on macOS, and it doesn't seem to be related to Poly/ML: I think the version of minisat shipped with HOL just doesn't work on Linux:

TAUT_LIB generates the following CNF problem to prove `~(p /\ q) <=> ~p \/ ~q`:
```
c File /var/tmp//MLTEMPyGcstg.cnf generated by HolSatLib
c
p cnf 9 19
2 -1 
0
2 -3 
0
1 3 -2 
0
5 4 2 
0
5 -2 -4 
0
4 -2 -5 
0
2 -4 -5 
0
8 -7 -6 
0
7 -8 
0
6 -8 
0
9 5 
0
-5 -9 
0
4 8 
0
-8 -4 
0
3 6 
0
-6 -3 
0
1 7 
0
-7 -1 
0
9 
0
```
and here is what I get from the HOL minisat on macOS (both when compiled for arm64 and x86_64):
```
==================================[MINISAT]===================================
| Conflicts |     ORIGINAL     |              LEARNT              | Progress |
|           | Clauses Literals |   Limit Clauses Literals  Lit/Cl |          |
==============================================================================
|         0 |      15       34 |       5       0        0     nan |  0.000 % |
==============================================================================
restarts              : 1
conflicts             : 3              (448 /sec)
decisions             : 2              (299 /sec)
propagations          : 16             (2389 /sec)
conflict literals     : 3              (0.00 % deleted)
CPU time              : 0.006696 s

UNSATISFIABLE
```
and here is what I get from the HOL minisat on Linux:
```
==================================[MINISAT]===================================
| Conflicts |     ORIGINAL     |              LEARNT              | Progress |
|           | Clauses Literals |   Limit Clauses Literals  Lit/Cl |          |
==============================================================================
|         0 |      17       40 |       5       0        0     nan |  0.000 % |
==============================================================================
restarts              : 1
conflicts             : 0              (0 /sec)
decisions             : 3              (893 /sec)
propagations          : 9              (2680 /sec)
conflict literals     : 0              ( nan % deleted)
Memory used           : 4.66 MB
CPU time              : 0.003358 s

SATISFIABLE
```

**Comment by binghe** [comment]
Amazing ... thanks for tracking it down @oskarabrahamsson  So this is actually a MiniSat issue specific to Linux/ARM64, right? (as sometimes I also use HOL4 on Linux/x86_64, it works well.)

**Comment by mn200** [comment]
We probably have a pretty stale version of minisat, so it's possible there's an updated version of that we might use instead.  (Alternatively, the version we have is being miscompiled, which would be a bug in `gcc`.)

**Comment by binghe** [comment]
Some updates: I'm using GCC 9.3.0 on Ubuntu 20.04 LTS (ARM64). The last MiniSAT official release (2.2.0) [1] cannot be built with this compiler. The problem of MiniSAT is that the official releases have stopped for more than 10 years and different unofficial patches and releases are everywhere on Internet (even in my office).   I found a simple one [2] (2.2.1 unofficial), which basically just fixed the fetal compilation issues, and built it on my Ubuntu ARM64 box, then test the CNF file provided by Oskar, and this time the result seems correct:
```
============================[ Problem Statistics ]=============================
|                                                                             |
|  Number of variables:             9                                         |
|  Number of clauses:              18                                         |
|  Parse time:                   0.01 s                                       |
|  Eliminated clauses:           0.00 Mb                                      |
|  Simplification time:          0.01 s                                       |
|                                                                             |
===============================================================================
Solved by simplification
restarts              : 0
conflicts             : 0              (0 /sec)
decisions             : 0              ( nan % random) (0 /sec)
propagations          : 3              (106 /sec)
conflict literals     : 0              ( nan % deleted)
Memory used           : 5.43 MB
CPU time              : 0.028187 s

UNSATISFIABLE
```

By a quick comparison on source files found on MiniSAT official site [1]. I think the version of MiniSAT currently shipped with HOL4 is the original (or some variants) of version 1.1.4. Yes, it's stable, but it's too old to support recent versions of C++ compilers (from GCC and LLVM). Even the latest official release (2.2.0) cannot be directly used without third-party patches.

I also tried to put the "minisat" v2.2.1 binary in place of the old "minisat" in HOL working directory and try to continue the previously stopped building process, however it doesn't work, because minisat V1 and V2 has different command-line formats: V1 uses "-r result" to write the results into a file, while V2 put the result file directly as the last optional parameter: `[options] <input-file> <result-output-file>`.   However, I believe if the corresponding ML files are modified to adapt for minisat V2, all the issues I met here would have been resolved.

I'm not sure if I'm the right person to submit a PR to upgrade HOL's builtin MiniSAT to some variant of V2 (with necessary patches), but I think this upgrade should be the direction.  e.g. Isabelle also uses a version of "minisat-2.2.1" in its "contrib" directory, perhaps we can just take the same source code from Isabelle repository.

Regards,

Chun Tian

[1] http://minisat.se/MiniSat.html
[2] https://github.com/msoos/minisat/releases/tag/2.2.1

**Comment by binghe** [comment]
Ah, I guess HOL doesn't (and also shouldn't) blindly trust the (UNSAT) result from MiniSAT - its proof logging feature have been used. But I didn't see any "proof logging" options from MiniSAT V2 command line help: 
```
$ ./minisat --help
USAGE: ./minisat [options] <input-file> <result-output-file>

  where input may be either in plain or gzipped DIMACS.

CORE OPTIONS:

  -luby, -no-luby                         (default: on)
  -rnd-init, -no-rnd-init                 (default: off)

  -gc-frac      = <double> (   0 ..  inf) (default: 0.2)
  -rinc         = <double> (   1 ..  inf) (default: 2)
  -rnd-seed     = <double> (   0 ..  inf) (default: 9.16483e+07)
  -rnd-freq     = <double> [   0 ..    1] (default: 0)
  -cla-decay    = <double> (   0 ..    1) (default: 0.999)
  -var-decay    = <double> (   0 ..    1) (default: 0.95)

  -rfirst       = <int32>  [   1 .. imax] (default: 100)
  -ccmin-mode   = <int32>  [   0 ..    2] (default: 2)
  -phase-saving = <int32>  [   0 ..    2] (default: 2)
  -min-learnts  = <int32>  [   0 .. imax] (default: 0)

MAIN OPTIONS:

  -strict, -no-strict                     (default: off)
  -solve, -no-solve                       (default: on)
  -pre, -no-pre                           (default: on)

  -mem-lim      = <int32>  [   0 .. imax] (default: 0)
  -cpu-lim      = <int32>  [   0 .. imax] (default: 0)
  -verb         = <int32>  [   0 ..    2] (default: 1)

  -dimacs     = <string>

SIMP OPTIONS:

  -elim, -no-elim                         (default: on)
  -rcheck, -no-rcheck                     (default: off)
  -asymm, -no-asymm                       (default: off)

  -simp-gc-frac = <double> (   0 ..  inf) (default: 0.5)

  -grow         = <int32>  [imin .. imax] (default: 0)
  -sub-lim      = <int32>  [  -1 .. imax] (default: 1000)
  -cl-lim       = <int32>  [  -1 .. imax] (default: 20)

HELP OPTIONS:

  --help        Print help message.
  --help-verb   Print verbose help message.
```

The lacking of "proof logging" should be a blocking issue, right?

**Comment by mn200** [comment]
Yeah, we do want proofs out so that we can check them.  I’d assume Isabelle would too though…

**Comment by binghe** [comment]
> Yeah, we do want proofs out so that we can check them. I’d assume Isabelle would too though…

I asked about SAT solvers with "proof logging" to my colleague (Alberto Griggio), who is the main author of MathSAT. Here is his answer:
```
luckily, basically all modern SAT solvers (i.e. those participating in
the latest SAT competitions) support the generation of proofs in DRAT
format. These proofs can then be checked with DRAT tools and converted
to more conventional resolution proofs if needed. For more info, you can
check the github page: https://github.com/marijnheule/drat-trim
```

MiniSAT (even V2) is too old to support DRAT, but other more recent/updated SAT solvers all do.  But integrating any of them (with the DRAT tool) into HOL4 as the replacements of the current MiniSAT looks like a big project.    I guess this is not urgent, as long as the current MiniSAT still works on mainstream systems...

**Comment by mn200** [comment]
I assume minisat is not multi-threaded (meaning no weak memory issue).  But then, perhaps it's making undue assumptions about signedness / endianness.  (Ugh; this is why C is such a terrible language.)

**Comment by oskarabrahamsson** [comment]
I found some undefined behavior using UBSan: https://github.com/HOL-Theorem-Prover/HOL/blob/develop/src/HolSat/sat_solvers/minisat/Solver.C#L478

Here, `assign` is something of type `vec<char>` and the right hand side can be negative, and apparently chars are unsigned on this platform.

**Comment by oskarabrahamsson** [comment]
I guess replacing all byte:y (i.e. non-string) uses of `char` with `int8_t` is one way to resolve this issue.

**Comment by binghe** [comment]
> I guess replacing all byte:y (i.e. non-string) uses of `char` with `int8_t` is one way to resolve this issue.

Great finding!!! I'm confirming your idea now.

**Comment by binghe** [comment]
> I guess replacing all byte:y (i.e. non-string) uses of `char` with `int8_t` is one way to resolve this issue.

I was rebuilding latest PolyML and then HOL4 in my Linux/ARM VM.  The building process now has just passed `relationTheory` (the previous failing point) without any issue. This mean your proposed fixes worked.

Given that it spent 104s on `relationTheory`, I guess it will take many hours (or a day) for the entire HOL4 to be built. I have faith on it.

Thanks for tracking this issue and fixing it!

**Comment by binghe** [comment]
```
Finished $(HOLDIR)/src/probability [#theories: 15]                 (5752.809s) 
Uploading files to /home/binghe/ML/HOL/sigobj

Number of states = 83
Number of distinct rows = 55
Approx. memory size of trans. table = 14080 bytes
Generating ASCII versions of Docfiles...
Directory /home/binghe/ML/HOL/help/Docfiles:  100%
...ASCII Docfiles done
Generating HTML versions of Docfiles...
Directory /home/binghe/ML/HOL/help/Docfiles:  100%
...HTML Docfiles done
Building Help DB
Reading signatures in directory /home/binghe/ML/HOL/sigobj
and writing help database in file /home/binghe/ML/HOL/help/HOL.Help

Processed 35597 entries in total.
Building database...
Writing database to file /home/binghe/ML/HOL/help/HOL.Help

Writing ASCII signature index in file index.txt

Writing Latex signature index in file index.tex

Creating HTML versions of signature files
Created directory htmlsigs

Writing HTML signature index in file /home/binghe/ML/HOL/help/src-sml/htmlsigs/idIndex.html

Writing HTML theory signature index in file /home/binghe/ML/HOL/help/src-sml/htmlsigs/TheoryIndex.html

Writing HOLPage
*** If you had a copy of the dot tool installed, I might try
*** to build a theory graph at this point

Hol built successfully.
binghe@ubuntu-arm64:~/ML/HOL$ uname -a
Linux ubuntu-arm64 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:29:20 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by binghe** [comment]
I think we can close this issue now.
