### ISSUE TITLE
Weird «HOL Description» sub-section names

### ISSUE THREAD

**Issue by binghe** [HOL-Theorem-Prover/HOL#963]
Hi,

In «The HOL System Description», the section "DERIVATION OF THE STANDARD RULES", there are two weird (identical) sub-section names: (around page 61-62)

- 2.3.21 Use of a definition (the content is `RIGHT_BETA`)
- 2.3.22 Use of a definition (the content is `RIGHT_LIST_BETA`)

I hardly can connect these drules with "use of a definition". What are the correct subsection names supposed to be?  I think this is an old issue, because they were like now even in this manual for Kananaskis-7 that I found on Internet.

Also, I occasionally found this issue when searching "definition" in the manual, aiming to find out what's the corresponding "modern" syntax for `zDefine` (something like `Definition[...]` "without computation"?). Can we document this somewhere in the manual?

Thanks.

Chun Tian

**Comment by konrad-slind** [comment]
Re: making definitions. The new syntactic forms for declaring
definitions, theorems, overloading, etc are really nice, but
their documentation is scattered over the Description. Pointers
are given in the Index, under

  special syntactic forms for scripts

However, I think what you are looking for is the
nocompute "pseudo-attribute", and I eventually found it
documented in the computeLib part of the manual. The example
given is

  Definition f_def[nocompute]:
    f x = x + 10
  End

Note there is no space allowed between the definition name and
the pseudo-attribute list, and the "Definition" and "End"
keywords need to be in the first column.

Konrad.

**Comment by mn200** [comment]
I'll look at the manual soon.  As for the syntax; Konrad is right. 

(It does seem unnecessarily fussy to require the square brackets to be up against the identifier; I'll change that to allow intervening whitespace.)

**Comment by binghe** [comment]
Thanks for your answer and manual changes!
