### ISSUE TITLE
Name clash for EXP_ADD

### ISSUE THREAD

**Issue by dwRchyngqxs** [HOL-Theorem-Prover/HOL#986]
There is a name clash between transcTheory and arithmeticTheory on `EXP_ADD`. The first is about the real exponential function and the second about the numeral exponentiation. Maybe the transcTheory one could be renamed `REAL_EXP_ADD` and the arithmeticTheory one could be renamed `NUM_EXP_ADD` (even though both actually go from `f (a + b)` to `f a * f b` unlike `INT_EXP_ADD_EXPONENTS`).

**Comment by mn200** [comment]
Thanks for alerting me to this.  I agree the situation is clearly sub-optimal.  In the interests of backwards compatibility I'm tempted to leave both names as they are, but to add aliases as well (for at least one of them), so that both theorems can be accessed when both theories are `open`.
