### ISSUE TITLE
KERNELID variable

### ISSUE THREAD

**Issue by konrad-slind** [HOL-Theorem-Prover/HOL#991]
bin/build fails in src/relation when trying to build bisimulationTheory. Complains that it can't find bin/hol.state. Removing src/bisimulationScript.sml allows the build to complete (after a cleanAll in src/relation).

This is on arm64 on MacBook, poly 5.9.1.

Seems odd that this hasn't been a problem to-date.

**Comment by mn200** [comment]
I am on a similar setup (Apple Silicon MacBook Pro and poly v5.9-159-g67384d30), and totally don't see this.  This is the sort of thing that `Holmake` in that directory might cause to happen (you need to pass the `--holstate=...` option), but `build` knows to pass the right `holstate` option in those early directories (and successfully building `relation` suggests it was doing just this).

**Comment by konrad-slind** [comment]
After bin/build failed there was no hol.state file to be found in `bin`. At what point in the build does hol.state get created?

**Comment by mn200** [comment]
After `src/boss`.  It happens at the `[poly]bin/hol` line in `tools/sequences/core-theories`.

**Comment by mn200** [comment]
Well, actually, it's just built in `src/boss` (the `Holmakefile` there arranges it).  The line in the sequence file is telling `build` to call `Holmake` appropriately from there on.

**Comment by konrad-slind** [comment]
Thanks. Since src/relation is built well before src/boss, this is puzzling. I pulled down fresh copies of polyML and HOL, so it's probably some other aspect of my set-up.

**Comment by konrad-slind** [comment]
Looking further ... it's possible the access to $KERNELID variable in the
ifeq test of the Holmakefile. If I change the conditional to

ifeq ($(KERNELID),$(KERNELID))
endif

the build fails. Is there some kind of access to an environment variable
happening? (My env. on the Macbook is still being sorted out.)

Konrad.

**Comment by mn200** [comment]
It's not an environment variable, it's set automatically by the build process (based on whether you're `--expk` or `--otknl` or `--stdknl` (latter is default)) and `Holmake` reads it from the path `<holdir>/.kernelidstr`.  It's not surprising that changing the test the way you did caused an error: it makes the system try to generate OpenTheory files.

**Comment by konrad-slind** [comment]
Thanks, I am still confused. Following is a series of ifeq ... endif
directives.  The following two are fine:

ifeq "$(HOLDIR)" "$(HOLDIR)"
endif

iifeq "$(KERNELID)" "otknl"
endif

But both of the following make

  bin/build --stdknl

fail in src/relation:

ifeq "$(KERNELID)" "$(KERNELID)"
endif

ifeq "$(KERNELID)" "otknl"
all: $(patsubst %Script.sml,%.ot.art,$(wildcard *Script.sml))

relation.art: relation.otd

endif

The first failure is puzzling since it's basically the same as the
HOLDIR comparison above.
The second is puzzling because the test should be failing, but processing
seems to be happening in the body of the ifeq.

Konrad.

**Comment by mn200** [comment]
What happens if you make a target in the `Holmakefile` along the lines of
```
foo: 
     echo $(KERNELID)
```
and you then call `Holmake --holstate=HOL/bin/hol.state0 foo` in that directory?

**Comment by konrad-slind** [comment]
Adding that target is fine: the directory builds But then if I go and add

# ifeq ($(KERNELID),otknl)
# all: $(patsubst %Script.sml,%.ot.art,$(wildcard *Script.sml))
# relation.art: relation.otd
# endif

it fails. Not sure why adding commented-out stuff would make any difference.

**Comment by mn200** [comment]
How does it fail?  What error message?  Just the thing about not having `hol.state`?  And do you get the expected `KERNELID` (`stdknl`, I assume) when you get it echoed?

**Comment by konrad-slind** [comment]
Following Holmakefile builds relationTheory then fails on
bisimulationTheory:

THYFILES = $(patsubst %Script.sml,%Theory.uo,$(wildcard *.sml))
TARGETS = $(patsubst %.sml,%.uo,$(THYFILES))

all: $(TARGETS)
.PHONY: all

foo:
echo $(KERNELID) > kid

# ifeq ($(KERNELID),otknl)
# all: $(patsubst %Script.sml,%.ot.art,$(wildcard *Script.sml))
#
# relation.art: relation.otd
#
# endif

Failure message:

bisimulationTheory
                   (1s)FAIL<Signal B>

The string "stdknl" gets printed to file "kid" when the commented-out stuff
is removed and the build is invoked with

Holmake --holstate=/Users/konradslind/Projects/HOL/bin/hol.state0  foo

**Comment by mn200** [comment]
Signal B is a segmentation fault (look at output of `kill -l`), and thus a Poly/ML bug.  In my experience, such files do eventually build if you keep trying (i.e., it happens non-deterministically).  Hopefully, David Matthews eventually fixes the compiler error.

**Comment by konrad-slind** [comment]
OK. It's not a show-stopper by any means. I was just perplexed at some of
the weird behaviors. Thanks for looking into it.

Konrad.
