### ISSUE TITLE
vim-mode can no longer send contents of regular .sml files to HOL

### ISSUE THREAD

**Issue by oskarabrahamsson** [HOL-Theorem-Prover/HOL#999]
I used to be able to send the contents of any buffer of any filetype into the HOL4 session, not just proof scripts. This is useful when e.g. debugging library code.

I'm guessing this feature disappeared somewhere around 544d89da.

**Comment by arolle** [comment]
If that is a desired feature, then the alternatives are to revert said commit or to change `*?Script.sml` to `*?.sml` in the [`filetype.vim`](https://github.com/HOL-Theorem-Prover/HOL/blob/b46e29d269344e1d2981f1c850969b4f6ff7a0ac/tools-poly/configure.sml#L519).

**Comment by mn200** [comment]
It'd be good if the `vim` community could figure out what they want here.

**Comment by mn200** [comment]
Closed by 8413d64
